import test from 'node:test';
import assert from 'node:assert/strict';
const mod=await import('../public/hq/family-model.mjs').catch(()=>({}));
const person=(id,data={})=>({id,kind:'person',data:{name:id,...data}}),rel=(from,to,type)=>({id:from+to+type,kind:'relationship',data:{from,to,type,evidence:'family'}});
test('family dates preserve month and year precision, including unknown text',()=>{assert.equal(typeof mod.familyDate,'function');assert.equal(mod.familyDate('2010-01').label,'Jan 2010');assert.equal(mod.familyDate('1929').label,'1929');assert.equal(mod.familyDate('Year disputed').sort,null);assert.equal(mod.familyDate('2019-02-30').sort,null);});
test('timeline has chronological careers, no duplicate birth events or assumed dates',()=>{assert.equal(typeof mod.familyTimeline,'function');const p=person('p',{birth:'1962-10-25'});const e={id:'b',kind:'lifeEvent',data:{personId:'p',eventType:'birth',title:'Born',start:'1962-10-25'}};const career={id:'c',kind:'lifeEvent',data:{personId:'p',eventType:'career',title:'Work',start:'2010-01'}};const rows=mod.familyTimeline([p],[career,e]);assert.deepEqual(rows.map(x=>x.id),['b','c']);});
test('tree includes distinct biological and adopted parent branches',()=>{assert.equal(typeof mod.familyLayout,'function');const p=[person('root',{isRoot:true}),person('birth-parent'),person('adopt-parent'),person('partner'),person('sister'),person('unrelated')];const r=[rel('birth-parent','root','parent'),rel('adopt-parent','root','adoptive-parent'),rel('root','partner','partner'),rel('root','sister','adoptive-sibling')];const m=mod.familyLayout(p,r,'root');assert.ok(m.nodes.find(x=>x.id==='root'));assert.equal(m.nodes.find(x=>x.id==='sister').generation,0);assert.equal(m.nodes.find(x=>x.id==='adopt-parent').generation,-1);assert.ok(m.edges.find(x=>x.type==='adoptive-parent'));assert.equal(m.nodes.some(x=>x.id==='unrelated'),false);});
test('map queries encode supplied text and never execute javascript',()=>{assert.equal(typeof mod.mapLink,'function');assert.ok(mod.mapLink('Town & County').startsWith('https://www.google.com/maps/search/?api=1&query='));assert.ok(mod.mapLink('javascript:alert(1)').includes('query=javascript%3A'));});
test('a child birth event must not hide the parent birth date',()=>{const rows=mod.familyTimeline([person('parent',{birth:'1990-10-11'}),person('child')],[{id:'child-birth',data:{title:'Child born',personId:'child',participants:['parent'],eventType:'birth',start:'2023-04-20'}}]);assert.ok(rows.some(r=>r.id==='parent-birth'));});
