import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './helpers/hq-fixture.mjs';
import {initialise} from '../src/hq/schema.mjs';
import {createRecord,updateRecord,listRecords} from '../src/hq/records.mjs';
const mod=await import('../src/hq/family-import.mjs').catch(()=>({}));
const owner={id:'owner',role:'admin'},guest={id:'guest',role:'member'};
const pkg=()=>({format:'duck-bear-family',version:1,namespace:'example',records:[{key:'s',kind:'familySource',data:{title:'Family account',sourceType:'family',evidence:'family'}},{key:'p',kind:'person',data:{name:'Example Parent',sourceIds:['@s'],birth:'1929-12-02',evidence:'family'}},{key:'c',kind:'person',data:{name:'Example Child',sourceIds:['@s'],evidence:'family'}},{key:'r',kind:'relationship',data:{from:'@p',to:'@c',type:'adoptive-parent',evidence:'family'}},{key:'e',kind:'lifeEvent',data:{personId:'@c',title:'Adopted',eventType:'adoption',start:'1963-05-17',sourceIds:['@s'],evidence:'family'}},{key:'x',kind:'familyPrivate',data:{personId:'@c',address:'Synthetic private address',sourceIds:['@s']}}]});
async function setup(){const f=await fixture();await initialise(f.env,owner);return f;}
test('family import resolves new linked records, is transactional and idempotent',async()=>{assert.equal(typeof mod.previewFamilyImport,'function');const f=await setup();try{const a=await mod.previewFamilyImport(f.env,owner,pkg());assert.equal(a.createCount,6);const r=await mod.applyFamilyImport(f.env,owner,pkg(),{signature:a.signature});assert.equal(r.created,6);const b=await mod.previewFamilyImport(f.env,owner,pkg());assert.equal(b.createCount,0);assert.equal(b.updateCount,0);assert.equal(b.keepCount,6);const privateRows=await listRecords(f.env,owner,{kind:'familyPrivate'});assert.equal(privateRows.records[0].section,'intimate');}finally{f.close();}});
test('import refuses unresolved links and parent cycles before writing',async()=>{assert.equal(typeof mod.previewFamilyImport,'function');const f=await setup();try{let p=pkg();p.records.push({key:'loop',kind:'relationship',data:{from:'@c',to:'@p',type:'parent'}});await assert.rejects(mod.previewFamilyImport(f.env,owner,p),/loop/i);p=pkg();p.records[4].data.personId='@missing';await assert.rejects(mod.previewFamilyImport(f.env,owner,p),/linked|reference|missing/i);assert.equal((await listRecords(f.env,owner,{section:'family'})).records.length,0);}finally{f.close();}});
test('only owner can preview or apply an import',async()=>{assert.equal(typeof mod.previewFamilyImport,'function');const f=await setup();try{await assert.rejects(mod.previewFamilyImport(f.env,guest,pkg()),/Owner access/);}finally{f.close();}});
test('alias match preserves photos; conflicting filled fields need explicit overwrite',async()=>{assert.equal(typeof mod.previewFamilyImport,'function');const f=await setup();try{const old=await createRecord(f.env,owner,'person',{name:'Earlier Full Name',birth:'1930',notes:'Existing family note'});const p=pkg();p.records[1].data.aliases=['Earlier Full Name'];let preview=await mod.previewFamilyImport(f.env,owner,p);assert.equal(preview.conflicts.length,1);await assert.rejects(mod.applyFamilyImport(f.env,owner,p,{signature:preview.signature}),/conflict/i);preview=await mod.previewFamilyImport(f.env,owner,p,{overwrite:true});await mod.applyFamilyImport(f.env,owner,p,{signature:preview.signature,overwrite:true});const people=await listRecords(f.env,owner,{kind:'person'});assert.equal(people.records.length,2);assert.equal(people.records.find(x=>x.id===old.id).data.birth,'1929-12-02');assert.equal(people.records.find(x=>x.id===old.id).data.notes,'Existing family note');}finally{f.close();}});
test('a stale preview cannot overwrite a subsequent edit',async()=>{assert.equal(typeof mod.previewFamilyImport,'function');const f=await setup();try{const a=await mod.previewFamilyImport(f.env,owner,pkg());await createRecord(f.env,owner,'person',{name:'Concurrent addition'});await assert.rejects(mod.applyFamilyImport(f.env,owner,pkg(),{signature:a.signature}),/changed|preview/i);assert.equal((await listRecords(f.env,owner,{kind:'person'})).records.length,1);}finally{f.close();}});
test('at signs in family memories are text, not import references',async()=>{const f=await setup();try{const p=pkg();p.records[1].data.notes='@home with the family';const preview=await mod.previewFamilyImport(f.env,owner,p);assert.equal(preview.createCount,6);}finally{f.close();}});
test('import writes linked records atomically without assuming REST batch transactions',async()=>{const f=await setup();try{const p=pkg(),preview=await mod.previewFamilyImport(f.env,owner,p);f.env.DB.batch=async()=>{throw Error('REST batch atomicity is not assumed');};const result=await mod.applyFamilyImport(f.env,owner,p,{signature:preview.signature});assert.equal(result.created,6);}finally{f.close();}});
