"""Real browser acceptance against a local worker fixture. No production credentials."""
import os,json,pathlib
from playwright.sync_api import sync_playwright
BASE=os.environ.get('BASE_URL','http://127.0.0.1:8789')
OUT=pathlib.Path(os.environ.get('HQ_REPORT','/mnt/data/hq-browser'));OUT.mkdir(parents=True,exist_ok=True)
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True,**({'executable_path':os.environ['CHROMIUM']} if os.environ.get('CHROMIUM') else {}),args=['--no-sandbox'])
 page=browser.new_page(viewport={'width':1440,'height':1000})
 errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 try:
  page.goto(BASE+'/sign-in/')
  page.get_by_label('Username or email',exact=True).fill('owner')
  page.get_by_label('Password',exact=True).fill('test-password-123')
  page.get_by_role('button',name='Sign in',exact=True).click()
  page.wait_for_url('**/our-space/')
  page.get_by_role('heading',name='Our little corner',exact=True).wait_for()
  page.goto(BASE+'/family-tree/people/new/')
  page.get_by_label('Name',exact=True).fill('Test family person')
  page.get_by_label('Other names',exact=True).fill('家人')
  page.get_by_role('button',name='Save person',exact=True).click()
  page.get_by_role('heading',name='Test family person',exact=True).wait_for()
  person_url=page.url
  page.reload();page.get_by_role('heading',name='Test family person',exact=True).wait_for()
  page.get_by_role('link',name='Edit person',exact=True).click()
  page.get_by_label('Notes',exact=True).fill('A real saved family note.')
  page.get_by_role('button',name='Save person',exact=True).click()
  page.get_by_text('A real saved family note.',exact=True).wait_for()
  page.goto(BASE+'/scrapbook/albums/new/')
  page.get_by_label('Title',exact=True).fill('Our test album')
  page.get_by_role('button',name='Save album',exact=True).click()
  page.get_by_role('heading',name='Our test album',exact=True).wait_for()
  page.get_by_role('link',name='Add memory',exact=True).click()
  page.get_by_label('Title',exact=True).fill('First memory')
  page.get_by_label('Story',exact=True).fill('A day worth keeping.')
  page.get_by_role('button',name='Save memory',exact=True).click()
  page.get_by_role('heading',name='First memory',exact=True).wait_for()
  page.get_by_role('link',name='Comments',exact=True).click()
  page.get_by_label('Your comment',exact=True).fill('Saved and private.')
  page.get_by_role('button',name='Post comment',exact=True).click()
  page.get_by_text('Saved and private.',exact=True).wait_for()
  page.goto(BASE+'/menus/planner/new/')
  page.get_by_label('Week beginning',exact=True).fill('2026-10-05')
  page.get_by_label('Title',exact=True).fill('Next week')
  page.get_by_role('button',name='Save week',exact=True).click()
  page.get_by_role('heading',name='Next week',exact=True).wait_for()
  page.get_by_role('link',name='Add meal',exact=True).click()
  page.get_by_label('Title',exact=True).fill('Noodles')
  page.get_by_label('Date',exact=True).fill('2026-10-05')
  page.get_by_role('button',name='Save meal',exact=True).click()
  page.get_by_role('heading',name='Noodles',exact=True).wait_for()
  page.goto(BASE+'/plans/polls/new/')
  page.get_by_label('Title',exact=True).fill('Saturday?')
  page.get_by_label('Choices (one per line)',exact=True).fill('Beach\nHome')
  page.get_by_role('button',name='Save poll',exact=True).click()
  page.get_by_role('button',name='Vote: Beach',exact=True).click()
  page.get_by_text('Your vote: Beach',exact=True).wait_for()
  page.goto(BASE+'/settings/profile/')
  page.get_by_label('Display name',exact=True).fill('Bear Test')
  page.get_by_role('button',name='Save profile',exact=True).click()
  page.get_by_role('status').filter(has_text='Saved').wait_for()
  page.goto(BASE+'/family-tree/tree/');page.screenshot(path=str(OUT/'family-desktop.png'),full_page=True)
  page.goto(BASE+'/scrapbook/');page.screenshot(path=str(OUT/'scrapbook-desktop.png'),full_page=True)
  page.goto(BASE+'/menus/planner/');page.screenshot(path=str(OUT/'planner-desktop.png'),full_page=True)
  page.set_viewport_size({'width':390,'height':844});page.goto(BASE+'/our-space/')
  assert page.evaluate('document.documentElement.scrollWidth <= innerWidth+1'),'Mobile horizontal overflow'
  page.screenshot(path=str(OUT/'private-mobile.png'),full_page=True)
  page.goto(BASE+'/');page.screenshot(path=str(OUT/'public-mobile.png'),full_page=True)
  # A third user has no private sections by default and cannot load a private record.
  ctx=browser.new_context();guest=ctx.new_page();ctx.add_cookies([{'name':'db_session','value':'guest-token','url':BASE}])
  guest.goto(BASE+'/family-tree/people/');guest.get_by_role('heading',name='This section is private',exact=True).wait_for()
  assert ctx.request.get(BASE+'/api/hq/records/'+person_url.rstrip('/').split('/')[-1]).status==403
  assert not errors,errors
  (OUT/'report.json').write_text(json.dumps({'status':'passed','browserErrors':errors,'tested':['login','deep links and refresh','family CRUD','scrapbook albums/memories/comments','weekly planner','polls','profile','mobile overflow','permission denial']},indent=2))
  print('HQ browser acceptance passed')
 except Exception as error:
  page.screenshot(path=str(OUT/'failure.png'),full_page=True)
  (OUT/'failure.json').write_text(json.dumps({'error':str(error),'url':page.url,'browserErrors':errors,'body':page.locator('body').inner_text()},ensure_ascii=False,indent=2))
  raise
 finally:
  browser.close()
