import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,call} from './helpers/hq-fixture.mjs';import {createHqHandler} from '../src/hq/handler.mjs';
const zipmod=await import('../public/hq/zip.mjs').catch(()=>({}));const h=createHqHandler({fetch:async()=>new Response('legacy')});
const PNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aL1kAAAAASUVORK5CYII=','base64');
async function start(){const f=await fixture();await call(h,f.env,'/api/hq/me');return f;}
test('backup includes original and preview files and restores into an empty household without restoring public visibility',async()=>{const a=await start(),b=await start();try{const form=new FormData();form.set('section','scrapbook');form.set('file',new File([PNG],'original.png',{type:'image/png'}));form.set('preview',new File([PNG],'preview.png',{type:'image/png'}));let x=await call(h,a.env,'/api/hq/assets',{method:'POST',body:form});const asset=x.data.asset;x=await call(h,a.env,'/api/hq/records',{method:'POST',body:{kind:'album',data:{title:'Precious memories',coverId:asset.id}}});const album=x.data.record;x=await call(h,a.env,'/api/hq/backup');assert.equal(x.status,200);assert.ok(zipmod.readZip,'A real ZIP reader is available for restore');const files=zipmod.readZip(new Uint8Array(await x.response.arrayBuffer()));const manifest=JSON.parse(new TextDecoder().decode(files.get('manifest.json')));assert.ok(manifest.assets.some(z=>z.id===asset.id));assert.deepEqual(Buffer.from(files.get('files/'+asset.id+'/original')),PNG);
 x=await call(h,b.env,'/api/hq/restore/preview',{method:'POST',body:{manifest}});assert.equal(x.status,200);assert.deepEqual(x.data.conflicts,[]);const job=x.data.jobId;
 for(const z of manifest.assets){for(const variant of ['original','preview']){const req=new Request('https://duck-bear.test/api/hq/restore/'+job+'/files/'+z.id+'/'+variant,{method:'POST',headers:{Origin:'https://duck-bear.test',Cookie:'db_session=owner-token','content-type':'application/octet-stream'},body:files.get('files/'+z.id+'/'+variant)});const r=await h.fetch(req,b.env);assert.equal(r.status,200,await r.clone().text());}}
 x=await call(h,b.env,'/api/hq/restore/'+job+'/apply',{method:'POST',body:{confirm:'RESTORE'}});assert.equal(x.status,200);x=await call(h,b.env,'/api/hq/records/'+album.id);assert.equal(x.data.record.data.title,'Precious memories');x=await call(h,b.env,asset.url+'?original=1');assert.deepEqual(Buffer.from(await x.response.arrayBuffer()),PNG);x=await call(h,b.env,'/api/public/hq/assets/'+asset.id,{user:null});assert.equal(x.status,404);
 }finally{a.close();b.close();}});
test('backup rejects guests without export permission and restore refuses conflicting existing records',async()=>{const f=await start();try{let x=await call(h,f.env,'/api/hq/backup',{user:'guest'});assert.equal(x.status,403);x=await call(h,f.env,'/api/hq/records',{method:'POST',body:{kind:'person',data:{name:'Original'}}});const r=x.data.record;const manifest={format:'duck-bear-hq',version:1,records:[{...r,data:{name:'Overwritten'}}],assets:[],revisions:[]};x=await call(h,f.env,'/api/hq/restore/preview',{method:'POST',body:{manifest}});assert.equal(x.status,200);assert.equal(x.data.conflicts.length,1);x=await call(h,f.env,'/api/hq/restore/'+x.data.jobId+'/apply',{method:'POST',body:{confirm:'RESTORE'}});assert.equal(x.status,409);}finally{f.close();}});
