import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,call} from './helpers/hq-fixture.mjs';import {createHqHandler} from '../src/hq/handler.mjs';
const h=createHqHandler({fetch:async()=>new Response('legacy')});
const PNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aL1kAAAAASUVORK5CYII=','base64');
async function start(){const f=await fixture();await call(h,f.env,'/api/hq/me');return f;}
function form(section='scrapbook',bytes=PNG,type='image/png',name='photo.png'){const f=new FormData();f.set('section',section);f.set('file',new File([bytes],name,{type}));if(type==='image/png')f.set('preview',new File([bytes],'preview.png',{type}));return f;}
test('private upload rejects signed-out and wrong-section access, including original and preview URLs',async()=>{const f=await start();try{let x=await call(h,f.env,'/api/hq/assets',{method:'POST',body:form(),user:null});assert.equal(x.status,401);x=await call(h,f.env,'/api/hq/assets',{method:'POST',body:form()});assert.equal(x.status,201);const a=x.data.asset;assert.ok(a.url);x=await call(h,f.env,a.url,{user:'guest'});assert.equal(x.status,403);await call(h,f.env,'/api/hq/access/family/guest',{method:'PUT',body:{role:'read',export:false}});x=await call(h,f.env,a.url+'?original=1',{user:'guest'});assert.equal(x.status,403);x=await call(h,f.env,a.url,{user:'partner'});assert.equal(x.status,200);assert.match(x.response.headers.get('cache-control'),/no-store/);assert.deepEqual(Buffer.from(await x.response.arrayBuffer()),PNG);}finally{f.close();}});
test('image uploads check signature, size and actual dimensions, not just extension',async()=>{const f=await start();try{let x=await call(h,f.env,'/api/hq/assets',{method:'POST',body:form('family',Buffer.from('<svg onload="alert(1)"/>'),'image/png')});assert.equal(x.status,400);const bomb=Buffer.from(PNG);bomb.writeUInt32BE(30000,16);bomb.writeUInt32BE(30000,20);x=await call(h,f.env,'/api/hq/assets',{method:'POST',body:form('family',bomb)});assert.equal(x.status,400);}finally{f.close();}});
test('public artwork requires deliberate owner publication and never exposes the original',async()=>{const f=await start();try{let x=await call(h,f.env,'/api/hq/assets',{method:'POST',body:form()});const a=x.data.asset;x=await call(h,f.env,'/api/public/hq/assets/'+a.id,{user:null});assert.equal(x.status,404);x=await call(h,f.env,'/api/hq/assets/'+a.id,{method:'PUT',body:{isPublic:true},user:'partner'});assert.equal(x.status,403);x=await call(h,f.env,'/api/hq/assets/'+a.id,{method:'PUT',body:{isPublic:true,confirm:'PUBLISH'}});assert.equal(x.status,200);x=await call(h,f.env,'/api/public/hq/assets/'+a.id+'?original=1',{user:null});assert.equal(x.status,404);x=await call(h,f.env,'/api/public/hq/assets/'+a.id,{user:null});assert.equal(x.status,200);}finally{f.close();}});
test('a used cover cannot be deleted; replacing a cover does not delete its original',async()=>{const f=await start();try{const up=await call(h,f.env,'/api/hq/assets',{method:'POST',body:form()});const a=up.data.asset;let x=await call(h,f.env,'/api/hq/records',{method:'POST',body:{kind:'album',data:{title:'A first album',coverId:a.id}}});assert.equal(x.status,201);const album=x.data.record;x=await call(h,f.env,'/api/hq/assets/'+a.id,{method:'DELETE',body:{}});assert.equal(x.status,409);x=await call(h,f.env,'/api/hq/records/'+album.id,{method:'PUT',body:{revision:1,data:{title:'A first album',coverId:''}}});assert.equal(x.status,200);x=await call(h,f.env,a.url);assert.equal(x.status,200);}finally{f.close();}});
