import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,call} from './helpers/hq-fixture.mjs';
// Optional import lets the first red run show the missing feature, not a module-load crash.
const mod=await import('../src/hq/handler.mjs').catch(()=>({}));
const fallback={fetch:async()=>new Response('legacy')};
const handler=mod.createHqHandler?mod.createHqHandler(fallback):fallback;

async function ready(options){const f=await fixture(options);const me=await call(handler,f.env,'/api/hq/me');assert.equal(me.status,200,JSON.stringify(me.data));assert.ok(me.data?.user,'HQ response must include an authenticated user');return f;}
const add=(env,kind,data,user='owner')=>call(handler,env,'/api/hq/records',{method:'POST',user,body:{kind,data}});
test('HQ initialises only the evidenced household pair; unrelated members receive only the signed-in Info Library',async()=>{const f=await ready();try{let x=await call(handler,f.env,'/api/hq/me',{user:'partner'});assert.equal(x.data.pair,true);x=await call(handler,f.env,'/api/hq/me',{user:'guest'});assert.equal(x.data.pair,false);assert.deepEqual(Object.keys(x.data.access).filter(k=>x.data.access[k].read),['library']);x=await call(handler,f.env,'/api/hq/me',{user:null});assert.equal(x.status,401);}finally{f.close();}});
test('legacy APIs, private media, exports and private ratings are not available to invited users',async()=>{const f=await ready();try{for(const path of ['/api/bootstrap','/api/fun','/api/menus/dashboard','/api/export/backup.json','/media/memories/any.jpg','/api/admin/dashboard']){const x=await call(handler,f.env,path,{user:'guest'});assert.equal(x.status,403,path);}const x=await call(handler,f.env,'/api/hq/records?kind=review',{user:'guest'});assert.equal(x.status,403);}finally{f.close();}});
test('family read and contribute grants do not give scrapbook access or permission to change another author',async()=>{const f=await ready();try{let x=await call(handler,f.env,'/api/hq/access/family/guest',{method:'PUT',body:{role:'read',export:false}});assert.equal(x.status,200);x=await add(f.env,'person',{name:'Family member'},'guest');assert.equal(x.status,403);x=await call(handler,f.env,'/api/hq/records?kind=album',{user:'guest'});assert.equal(x.status,403);await call(handler,f.env,'/api/hq/access/family/guest',{method:'PUT',body:{role:'contribute',export:false}});x=await add(f.env,'person',{name:'My entry'},'guest');assert.equal(x.status,201);const own=x.data.record;x=await add(f.env,'person',{name:'Owner entry'});const other=x.data.record;x=await call(handler,f.env,'/api/hq/records/'+other.id,{method:'PUT',user:'guest',body:{revision:other.revision,data:{name:'Hijack'}}});assert.equal(x.status,403);x=await call(handler,f.env,'/api/hq/records/'+own.id,{method:'PUT',user:'guest',body:{revision:own.revision,data:{name:'My corrected entry'}}});assert.equal(x.status,200);}finally{f.close();}});
test('record revisions reject simultaneous stale saves and preserve history and recycle bin',async()=>{const f=await ready();try{let x=await add(f.env,'person',{name:'Original'});assert.equal(x.status,201);const r=x.data.record;const saves=await Promise.all(['A','B'].map(name=>call(handler,f.env,'/api/hq/records/'+r.id,{method:'PUT',body:{revision:r.revision,data:{name}}})));assert.deepEqual(saves.map(x=>x.status).sort(),[200,409]);x=await call(handler,f.env,'/api/hq/records/'+r.id+'/history');assert.equal(x.data.revisions.length,2);x=await call(handler,f.env,'/api/hq/records/'+r.id,{method:'DELETE',body:{revision:2}});assert.equal(x.status,200);x=await call(handler,f.env,'/api/hq/records/'+r.id);assert.equal(x.status,404);x=await call(handler,f.env,'/api/hq/records/'+r.id+'/restore',{method:'POST',body:{revision:3}});assert.equal(x.status,200);}finally{f.close();}});
test('same-origin checks and unsupported routes fail closed',async()=>{const f=await ready();try{let x=await call(handler,f.env,'/api/hq/records',{method:'POST',body:{kind:'person',data:{name:'Bad'}},headers:{Origin:'https://evil.test'}});assert.equal(x.status,403);x=await call(handler,f.env,'/api/hq/nothing');assert.equal(x.status,404);}finally{f.close();}});
test('a family graph rejects self links and parent cycles without inventing dates',async()=>{const f=await ready();try{const a=(await add(f.env,'person',{name:'A',birth:'circa 1950'})).data.record;const b=(await add(f.env,'person',{name:'B'})).data.record;let x=await add(f.env,'relationship',{from:a.id,to:b.id,type:'parent'});assert.equal(x.status,201);x=await add(f.env,'relationship',{from:b.id,to:a.id,type:'adoptive-parent'});assert.equal(x.status,400);x=await add(f.env,'relationship',{from:a.id,to:a.id,type:'partner'});assert.equal(x.status,400);}finally{f.close();}});
test('published weeks are immutable, copies are new drafts, and archives remain intact',async()=>{const f=await ready();try{let x=await add(f.env,'week',{start:'2026-10-05',title:'A new week'});assert.equal(x.status,201);const w=x.data.record;const serving=(await add(f.env,'serving',{weekId:w.id,date:'2026-10-05',course:'dinner',title:'Thai salmon',description:'With rice'})).data.record;x=await call(handler,f.env,'/api/hq/weeks/'+w.id+'/publish',{method:'POST',body:{revision:w.revision}});assert.equal(x.status,200);x=await call(handler,f.env,'/api/hq/records/'+serving.id,{method:'PUT',body:{revision:serving.revision,data:{...serving.data,title:'Changed'}}});assert.equal(x.status,409);x=await call(handler,f.env,'/api/public/hq/menus/2026-10-05',{user:null});assert.equal(x.status,200);assert.equal(x.data.week.meals[0].title,'Thai salmon');x=await call(handler,f.env,'/api/hq/weeks/'+w.id+'/copy',{method:'POST',body:{start:'2026-10-12'}});assert.equal(x.status,201);assert.equal(x.data.week.data.status,'draft');assert.notEqual(x.data.week.id,w.id);}finally{f.close();}});
test('one poll vote per user and favourites recheck permission after revocation',async()=>{const f=await ready();try{await call(handler,f.env,'/api/hq/access/plans/guest',{method:'PUT',body:{role:'contribute',export:false}});const p=(await add(f.env,'poll',{title:'Dinner?',options:['Thai','Greek']})).data.record;let x=await call(handler,f.env,'/api/hq/polls/'+p.id+'/vote',{method:'POST',user:'guest',body:{choice:0}});assert.equal(x.status,200);x=await call(handler,f.env,'/api/hq/polls/'+p.id+'/vote',{method:'POST',user:'guest',body:{choice:1}});assert.equal(x.data.totals.reduce((a,b)=>a+b,0),1);await call(handler,f.env,'/api/hq/favourites/'+p.id,{method:'PUT',user:'guest',body:{saved:true}});await call(handler,f.env,'/api/hq/access/plans/guest',{method:'PUT',body:{role:'none',export:false}});x=await call(handler,f.env,'/api/hq/favourites',{user:'guest'});assert.equal(x.data.records.length,0);}finally{f.close();}});
