import test from 'node:test';import assert from 'node:assert/strict';import {existsSync} from 'node:fs';
const mod=new URL('../src/last-luas/routes.mjs',import.meta.url);
test('private game route exists',()=>assert.ok(existsSync(mod),'Missing Last Luas owner route'));
if(existsSync(mod)){
 const {createLastLuasHandler}=await import(mod);
 const req=(p,method='GET')=>new Request('https://example.test'+p,{method});
 function fixture(user=null,owner={ownerId:'owner-1'}){const seen=[];const env={MEDIA:{get:async key=>{seen.push(key);if(key==='last-luas/access.json')return owner?{json:async()=>owner}:null;if(key.endsWith('/brands/hodges.png'))return {body:new Uint8Array([1,2,3]),size:3};return null;}},ASSETS:{fetch:async r=>{seen.push(new URL(r.url).pathname);const p=new URL(r.url).pathname;return new Response(p.endsWith('.mjs')?'export const x=1':p.endsWith('.css')?'body{}':'<canvas id="gameCanvas"></canvas>',{headers:{'Content-Type':p.endsWith('.mjs')?'text/javascript':p.endsWith('.css')?'text/css':'text/html'}});}}};return {env,seen,h:createLastLuasHandler({fetch:async()=>new Response('unchanged',{status:209})},async()=>user?{user}:null)};}
 test('public cards and other games do not invoke private storage',async()=>{const f=fixture();assert.equal((await f.h.fetch(req('/games/'),f.env)).status,209);assert.equal((await f.h.fetch(req('/games/mango-mayhem/'),f.env)).status,209);assert.equal(f.seen.length,0);});
 test('anonymous GET and HEAD cannot read page, code, session or private logos',async()=>{const f=fixture();for(const method of ['GET','HEAD'])for(const p of ['/games/last-luas/','/games/last-luas/inked/main.mjs','/games/last-luas/session','/games/last-luas/private/brands/hodges.png']){const r=await f.h.fetch(req(p,method),f.env);assert.equal(r.status,401,p);if(method==='HEAD')assert.equal(await r.text(),'');assert.match(r.headers.get('cache-control'),/private, no-store/);}assert.equal(f.seen.length,0);});
 test('another active admin is not the configured owner and inactive owner is blocked',async()=>{for(const user of [{id:'other',role:'admin',active:1},{id:'owner-1',role:'admin',active:0}]){const f=fixture(user);assert.equal((await f.h.fetch(req('/games/last-luas/private/brands/hodges.png'),f.env)).status,403);assert.ok(!f.seen.some(k=>k.endsWith('.png')));}});
 test('missing or malformed owner configuration fails closed',async()=>{for(const owner of [null,{}, {ownerId:''}]){const f=fixture({id:'owner-1',active:1},owner);assert.equal((await f.h.fetch(req('/games/last-luas/'),f.env)).status,503);}});
 test('owner receives proper asset type and no public cache, HEAD has no body',async()=>{const f=fixture({id:'owner-1',active:1});for(const method of ['GET','HEAD']){const r=await f.h.fetch(req('/games/last-luas/private/brands/hodges.png?set=inked-20260919-a',method),f.env);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/png');assert.match(r.headers.get('content-security-policy'),/default-src 'self'/);if(method==='HEAD')assert.equal(await r.text(),'');}assert.ok(f.seen.every(k=>k==='last-luas/access.json'||k==='last-luas/inked/inked-20260919-a/brands/hodges.png'));});
 test('unknown file and unsafe asset key never become homepage HTML',async()=>{const f=fixture({id:'owner-1',active:1});for(const p of ['/games/last-luas/missing.js','/games/last-luas/private/brands/unknown.png','/games/last-luas/private/secret.json','/games/last-luas/game.mjs']){assert.equal((await f.h.fetch(req(p),f.env)).status,404,p);}assert.equal((await f.h.fetch(req('/games/last-luas/private/brands/hodges.png?set=other'),f.env)).status,409);});
 test('encoded directory aliases are protected before static delivery',async()=>{const f=fixture();for(const p of ['/g%61mes/last-luas/','/games/last%2Dluas/index.html','/games/last%252Dluas/private/brands/hodges.png','/games%2Flast-luas%2Finked%2Fmain.mjs'])assert.equal((await f.h.fetch(req(p),f.env)).status,401,p);});
 test('directory/index canonicalization and unsupported methods are explicit',async()=>{const f=fixture({id:'owner-1',active:1});assert.equal((await f.h.fetch(req('/games/last-luas'),f.env)).status,308);assert.equal((await f.h.fetch(req('/games/last-luas/index.html'),f.env)).status,200);assert.ok(f.seen.includes('/games/last-luas/'));assert.equal((await f.h.fetch(req('/games/last-luas/','POST'),f.env)).status,405);});
 test('public release marker includes build but no owner/session identity',async()=>{const f=fixture();const r=await f.h.fetch(req('/api/last-luas/release'),f.env);assert.equal(r.status,200);const data=await r.json();assert.equal(data.version,'1.0.0');assert.equal(data.engine,'Canvas 2D');assert.equal(data.access,'owner-only');assert.ok(!JSON.stringify(data).includes('owner-1'));assert.equal(f.seen.length,0);});
}
