import test from 'node:test';import assert from 'node:assert/strict';import {database} from './helpers/mango-db.mjs';import {routeMangoApi} from '../src/mango/api.mjs';import {LocalProfiles} from '../public/games/mango-mayhem/platform/local.mjs';import {recordPickup,emptyProgress} from '../public/games/mango-mayhem/core/progress.mjs';
const load=()=>import('../public/games/mango-mayhem/platform/cloud.mjs');
function storage(){const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};}
function server(){const db=database();let owner='owner-a',offline=false;return {db,setOwner:v=>owner=v,setOffline:v=>offline=v,async fetch(path,options={}){if(offline)throw Error('Offline');return routeMangoApi(new Request('https://example.test'+path,{...options,headers:{...(options.headers||{}),...(options.method&&options.method!=='GET'?{Origin:'https://example.test'}:{})}}),{DB:db},owner?{id:owner,active:1}:null);}};}
test('cloud sync client exists',async()=>assert.ok(await load().catch(()=>null),'Cloud client required'));
test('two devices keep disjoint collected mango IDs through revision conflicts',async()=>{const {CloudProfiles}=await load();const api=server();const a=new LocalProfiles(storage()),b=new LocalProfiles(storage());const ca=new CloudProfiles(a,{fetch:api.fetch}),cb=new CloudProfiles(b,{fetch:api.fetch});const p=a.create('Player','mango');await ca.refresh();await ca.upload(p.id);await cb.refresh();const q=cb.download(cb.remote[0].id);a.saveProgress(p.id,recordPickup(a.get(p.id).progress,'dublin','m001'));b.saveProgress(q.id,recordPickup(b.get(q.id).progress,'dublin','m002'));await ca.flush();await cb.flush();await ca.refresh();assert.deepEqual(a.get(p.id).progress.levels.dublin.mangoIds,['m001','m002']);api.db.close();});
test('offline dirty progress survives reopening and then syncs',async()=>{const {CloudProfiles}=await load();const api=server(),m=storage(),a=new LocalProfiles(m),c=new CloudProfiles(a,{fetch:api.fetch});const p=a.create('Player','mango');await c.refresh();await c.upload(p.id);api.setOffline(true);a.saveProgress(p.id,recordPickup(a.get(p.id).progress,'dublin','m010'));await c.flush();assert.equal(a.get(p.id).cloud.dirty,true);const b=new LocalProfiles(m),d=new CloudProfiles(b,{fetch:api.fetch});api.setOffline(false);await d.refresh();await d.flush();assert.equal(b.get(p.id).cloud.dirty,false);assert.equal(d.remote[0].progress.levels.dublin.mangoIds[0],'m010');api.db.close();});
test('account changes never send the previous owner’s queued save into the next account',async()=>{const {CloudProfiles}=await load();const api=server(),s=new LocalProfiles(storage()),c=new CloudProfiles(s,{fetch:api.fetch});const p=s.create('Player','mango');await c.refresh();await c.upload(p.id);s.saveProgress(p.id,recordPickup(p.progress,'dublin','m030'));api.setOwner('owner-b');await c.refresh();await c.flush();assert.equal(c.ownerId,'owner-b');assert.equal(c.remote.length,0);assert.equal(s.get(p.id).cloud.dirty,true);api.db.close();});
test('deleted cloud profiles retain local copy but do not resurrect on reconnect',async()=>{const {CloudProfiles}=await load();const api=server(),s=new LocalProfiles(storage()),c=new CloudProfiles(s,{fetch:api.fetch});const p=s.create('Player','mango');await c.refresh();await c.upload(p.id);const linked=s.get(p.id);await api.fetch('/api/mango/profiles/'+linked.cloud.id,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:linked.cloud.revision})});s.saveProgress(p.id,recordPickup(p.progress,'dublin','m035'));await c.flush();assert.equal(s.get(p.id).cloud.deleted,true);await c.refresh();assert.equal(c.remote.length,0);assert.deepEqual(s.get(p.id).progress.levels.dublin.mangoIds,['m035']);api.db.close();});
test('a cookie account switch between refresh and save does not mark the old owner’s profile deleted',async()=>{const {CloudProfiles}=await load();const api=server(),s=new LocalProfiles(storage()),c=new CloudProfiles(s,{fetch:api.fetch});const p=s.create('Player','mango');await c.refresh();await c.upload(p.id);s.saveProgress(p.id,recordPickup(p.progress,'dublin','m041'));api.setOwner('owner-b');await c.flush();assert.equal(s.get(p.id).cloud.deleted,false);assert.equal(s.get(p.id).cloud.dirty,true);assert.equal(c.ownerId,'owner-b');api.db.close();});
