import test from 'node:test';import assert from 'node:assert/strict';import {database} from './helpers/mango-db.mjs';import {emptyProgress,recordPickup} from '../public/games/mango-mayhem/core/progress.mjs';
const load=()=>import('../src/mango/repository.mjs');
test('owner-scoped repository exists',async()=>assert.ok(await load().catch(()=>null),'Protected repository required'));
test('two owners cannot read, save, rename or delete one another’s profiles',async()=>{const {createProfileRepository}=await load();const db=database(),r=createProfileRepository(db);const a=await r.create('owner-a',{nickname:'Apple','avatarId':'duck'});assert.equal((await r.list('owner-b')).length,0);assert.equal(await r.get('owner-b',a.id),null);for(const fn of [()=>r.save('owner-b',a.id,{revision:0,progress:emptyProgress()}),()=>r.rename('owner-b',a.id,{revision:0,nickname:'Other',avatarId:'mango'}),()=>r.remove('owner-b',a.id,{revision:0})])await assert.rejects(fn,e=>e.status===404);assert.equal((await r.get('owner-a',a.id)).nickname,'Apple');db.close();});
test('compare-and-swap refuses stale saves and exposes only own current progress',async()=>{const {createProfileRepository}=await load();const db=database(),r=createProfileRepository(db);const a=await r.create('owner-a',{nickname:'Apple','avatarId':'duck'});const p=recordPickup(a.progress,'dublin','m001');const saved=await r.save('owner-a',a.id,{revision:0,progress:p});assert.equal(saved.revision,1);await assert.rejects(()=>r.save('owner-a',a.id,{revision:0,progress:emptyProgress()}),e=>e.status===409&&e.current.revision===1&&e.current.progress.levels.dublin.mangoIds[0]==='m001');db.close();});
test('deleted profiles never resurrect from an old save',async()=>{const {createProfileRepository}=await load();const db=database(),r=createProfileRepository(db);const p=await r.create('owner-a',{nickname:'Delete','avatarId':'mango'});await r.remove('owner-a',p.id,{revision:0});await assert.rejects(()=>r.save('owner-a',p.id,{revision:0,progress:p.progress}),e=>e.status===404);assert.equal((await r.list('owner-a')).length,0);db.close();});
test('six profiles per owner with atomic unique slots',async()=>{const {createProfileRepository}=await load();const db=database(),r=createProfileRepository(db);await Promise.all(Array.from({length:6},(_,i)=>r.create('owner-a',{nickname:'P'+i,avatarId:'star'})));assert.equal((await r.list('owner-a')).length,6);await assert.rejects(()=>r.create('owner-a',{nickname:'Seven','avatarId':'duck'}),e=>e.status===409);assert.equal((await r.create('owner-b',{nickname:'Separate','avatarId':'duck'})).slot,0);db.close();});
test('invalid canonical progress is rejected rather than stored',async()=>{const {createProfileRepository}=await load();const db=database(),r=createProfileRepository(db);const p=await r.create('owner-a',{nickname:'Mango','avatarId':'mango'});const corrupt=emptyProgress();corrupt.levels.liaoning.cleared=true;await assert.rejects(()=>r.save('owner-a',p.id,{revision:0,progress:corrupt}),e=>e.status===400);assert.equal((await r.get('owner-a',p.id)).revision,0);db.close();});
test('durable fixed-window write and create limits expire',async()=>{const {createProfileRepository}=await load();const db=database();let now=180000;const r=createProfileRepository(db,{clock:()=>now});for(let i=0;i<60;i++)await r.limit('owner-a','write');await assert.rejects(()=>r.limit('owner-a','write'),e=>e.status===429);await r.limit('owner-b','write');now+=60000;await r.limit('owner-a','write');for(let i=0;i<10;i++)await r.limit('owner-a','create');await assert.rejects(()=>r.limit('owner-a','create'),e=>e.status===429);db.close();});
