const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function cls(){const file=__dirname+'/../src/kart-assets/motion.js.txt';assert.ok(fs.existsSync(file),'motion module missing');const box={};vm.runInNewContext(fs.readFileSync(file,'utf8'),box);return box.WackyTilt;}
test('portrait calibrates neutral and positive screen-right is positive steering',()=>{const T=cls(),t=new T();t.enabled=true;t.sample({beta:30,gamma:12},0,1000);t.sample({beta:30,gamma:30},0,1100);assert.ok(t.read(1100)>0);});
test('both landscape orientations map consistently',()=>{const T=cls();for(const a of [90,270]){const t=new T();t.enabled=true;t.sample({beta:0,gamma:0},a,1000);t.sample({beta:a===90?20:-20,gamma:0},a,1200);assert.ok(t.read(1200)>0);}});
test('missing readings never become false zeros and cannot steer',()=>{const T=cls(),t=new T();t.enabled=true;t.sample({beta:null,gamma:null},0,1000);assert.equal(t.read(1000),0);assert.equal(t.ready,false);});
test('stale sensor drops steering and recalibration centres it',()=>{const T=cls(),t=new T();t.enabled=true;t.sample({beta:0,gamma:0},0,1000);t.sample({beta:0,gamma:20},0,1200);assert.ok(t.read(1200)>0);assert.equal(t.read(2100),0);t.calibrate();assert.equal(t.read(1200),0);});
test('rotating the screen resets calibration rather than steering wildly',()=>{const T=cls(),t=new T();t.enabled=true;t.sample({beta:40,gamma:10},0,1000);t.sample({beta:40,gamma:40},0,1200);t.sample({beta:40,gamma:40},90,1300);assert.equal(t.read(1300),0);});
test('permission denial fails safely and installs no listener',async()=>{const T=cls(),t=new T();let listens=0;const ok=await t.enable({isSecureContext:true,DeviceOrientationEvent:{requestPermission:async()=> 'denied'},addEventListener(){listens++;}});assert.equal(ok,false);assert.equal(t.enabled,false);assert.equal(listens,0);assert.match(t.status,/denied/i);});
test('insecure context and missing sensor retain button controls',async()=>{const T=cls();for(const env of [{isSecureContext:false},{isSecureContext:true}]){const t=new T();assert.equal(await t.enable(env),false);assert.equal(t.enabled,false);}});
test('permission granted listens once and disable removes sensor callback',async()=>{const T=cls(),t=new T();let added=0,removed=0;const env={isSecureContext:true,DeviceOrientationEvent:{requestPermission:async()=> 'granted'},addEventListener(){added++;},removeEventListener(){removed++;}};assert.equal(await t.enable(env),true);await t.enable(env);assert.equal(added,1);t.disable();assert.equal(removed,1);assert.equal(t.read(0),0);});
