const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const box={};vm.runInNewContext(fs.readFileSync(__dirname+'/../src/kart-assets/core.js.txt','utf8'),box);const C=box.KartCore;
function race(opts={}){const r=C.newRace({seed:77,mode:'trial',assist:false,...opts});r.countdown=0;return r;}
function run(r,input,seconds){for(let i=0;i<seconds*120;i++)C.stepRace(r,input,1/120);return r.racers[0];}
test('six tracks have country-prefixed names',()=>{assert.equal(C.TRACKS.length,6);C.TRACKS.slice(0,5).forEach(t=>assert.match(t.name,/^London - /));assert.match(C.TRACKS[5].name,/^Dublin - /);});
test('continuous closed track and right-positive lateral sampling on all courses',()=>{for(let i=0;i<C.TRACKS.length;i++){const t=C.buildTrack(i);assert.ok(t.length>900);for(let s=0;s<t.length;s+=21){const a=C.sampleTrack(t,s,0),b=C.sampleTrack(t,s,3);assert.ok(Math.abs(Math.hypot(b.x-a.x,b.z-a.z)-3)<1e-6);assert.ok((b.x-a.x)*-a.tz+(b.z-a.z)*a.tx>0);}const a=C.sampleTrack(t,0),b=C.sampleTrack(t,t.length);assert.ok(Math.hypot(a.x-b.x,a.z-b.z)<.001);}});
test('vehicle classes have distinct arcade handling character',()=>{assert.equal(Object.keys(C.VEHICLES||{}).length,4);const k=C.VEHICLES.kart,b=C.VEHICLES.bus,p=C.VEHICLES.police,a=C.VEHICLES.ambulance;assert.ok(b.mass>k.mass);assert.ok(b.top<k.top);assert.ok(k.steer>p.steer&&p.steer>a.steer&&a.steer>b.steer);assert.ok(b.roll>a.roll&&a.roll>p.roll&&p.roll>=k.roll);assert.ok(k.driftGrip<b.driftGrip);});
test('right steering produces positive momentum not instantaneous lane teleport',()=>{const r=race(),p=r.racers[0];p.x=0;p.speed=20;C.stepRace(r,{gas:1,steer:1},1/120);assert.ok(p.vx>0);assert.ok(p.x>0&&p.x<.1);run(r,{gas:1,steer:1},.4);const old=p.x;C.stepRace(r,{gas:1,steer:0},1/120);assert.ok(p.x>old);});
test('drift grip blends in and out instead of snapping',()=>{const r=race(),p=r.racers[0];p.x=0;p.speed=22;C.stepRace(r,{gas:1,steer:.35,drift:true},1/120);assert.ok(p.driftBlend>0&&p.driftBlend<.2);run(r,{gas:1,steer:.35,drift:true},.35);assert.ok(p.driftBlend>.75);run(r,{gas:1,steer:0,drift:false},.35);assert.ok(p.driftBlend<.15);});
test('braking stops faster than coasting',()=>{let a=race(),b=race();a.racers[0].speed=b.racers[0].speed=25;run(a,{brake:1},.5);run(b,{},.5);assert.ok(a.racers[0].speed<b.racers[0].speed-8);});
test('immobile forward input recovers, brakes and idle do not',()=>{const r=race(),p=r.racers[0];p.x=50;p.speed=0;run(r,{gas:1},3);assert.ok(Math.abs(p.x)<r.track.width/2);assert.ok(p.speed>3);assert.ok(p.recoveries>0);const b=race();run(b,{brake:1},5);assert.equal(b.racers[0].recoveries,0);});
test('manual recovery never increases progress or grants a lap',()=>{const r=race(),p=r.racers[0];p.s=r.track.length-1;p.x=20;p.vx=8;p.heading=2.4;const old=p.s;C.recover(r,p);assert.ok(p.s<=old);assert.equal(p.lapTimes.length,0);assert.equal(p.heading,0);assert.equal(p.vx,0);assert.ok(p.immune>0);});
test('all four snacks exist on track with pizza and whiskey hazards',()=>{const r=race({mode:'race'});for(const type of ['mango','icecream','blueberry','strawberry'])assert.ok(r.pickups.some(p=>p.type===type),type);for(const type of ['pizza','whiskey'])assert.ok(r.traps.some(p=>p.type===type),type);});
test('pickup grants boost and is not collected twice',()=>{const r=race({mode:'race'}),p=r.racers[0];r.pickups=[{s:100,x:0,type:'mango',cooldown:0}];r.traps=[];r.traffic=[];p.s=99;p.x=0;p.speed=15;C.stepRace(r,{gas:1},1/60);assert.ok(p.boost>0);assert.equal(p.coins,2);C.stepRace(r,{gas:1},1/60);assert.equal(p.coins,2);});
test('pizza slip loses grip and shield absorbs one hit',()=>{const r=race(),p=r.racers[0];p.speed=25;C.hit(r,p,'pizza');assert.ok(p.slip>0);assert.ok(p.speed<25);p.immune=0;p.shield=4;p.slip=0;assert.equal(C.hit(r,p,'whiskey'),false);assert.equal(p.shield,0);assert.equal(p.slip,0);});
test('the seven-racer grid contains local service vehicles without extra moving traffic',()=>{for(const track of [0,5]){const r=race({mode:'race',track});for(const vehicle of ['police','ambulance','bus'])assert.ok(r.racers.some(t=>t.vehicle===vehicle));assert.equal(r.traffic.length,0);assert.equal(r.track.country,track===5?'IE':'GB');}});
test('trial has no pickups, traps or traffic',()=>{const r=race();assert.equal(r.pickups.length+r.traps.length+(r.traffic?.length||0),0);});
test('paused state freezes physics and timers',()=>{const r=race();r.phase='paused';const before=JSON.stringify(r);run(r,{gas:1,steer:1},2);assert.equal(JSON.stringify(r),before);});
test('deterministic fixed-step simulation for identical inputs',()=>{const a=race({mode:'race'}),b=race({mode:'race'});run(a,{gas:1},12);run(b,{gas:1},12);assert.equal(JSON.stringify(a),JSON.stringify(b));});
test('30,60,120Hz calls have equivalent outcomes',()=>{const states=[];for(const hz of [30,60,120]){const r=race({assist:true});for(let i=0;i<4*hz;i++)C.stepRace(r,{gas:1},1/hz);states.push(r.racers[0]);}for(const p of states){assert.ok(Math.abs(p.s-states[0].s)<.05);assert.ok(Math.abs(p.x-states[0].x)<.05);}});
test('all six circuits can be finished by AI including the bus',()=>{for(let track=0;track<C.TRACKS.length;track++){const r=race({track,vehicle:'bus',difficulty:'normal'});r.racers[0].ai=true;run(r,{},220);assert.equal(r.phase,'results','track '+track);assert.equal(r.racers[0].lapTimes.length,3);assert.ok(Number.isFinite(r.racers[0].finishTime));}});
test('cup points unique and six rounds can accumulate',()=>{const a=Array(8).fill(0);for(let i=0;i<6;i++)C.addCupPoints(a,[0,1,2,3,4,5,6,7]);assert.equal(a[0],90);});
