import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
let PortalStore;
try { ({PortalStore}=await import('../src/portal/store.mjs')); } catch {}
const owner={id:'owner',displayName:'Bear',role:'admin',active:true};
const duck={id:'duck',displayName:'Duck',role:'member',active:true};
const guest={id:'guest',displayName:'Guest',role:'member',active:true};
export function context(){
 const db=new DatabaseSync(':memory:');
 return {db,storage:{sql:{exec(query,...values){const s=db.prepare(query);const rows=s.all(...values);return {toArray:()=>rows,[Symbol.iterator]:()=>rows[Symbol.iterator]()};}},transactionSync(fn){db.exec('BEGIN');try{const x=fn();db.exec('COMMIT');return x;}catch(e){db.exec('ROLLBACK');throw e;}}}};
}
async function fixture(){
 assert.equal(typeof PortalStore,'function','SQLite workspace store must exist');
 const ctx=context(),store=new PortalStore(ctx,{});
 const call=async(cmd,payload={},actor=owner)=>{const r=await store.fetch(new Request('https://internal',{method:'POST',body:JSON.stringify({cmd,payload,actor})}));return {status:r.status,...await r.json()};};
 assert.equal((await call('boot',{ownerId:'owner',companionId:'duck'})).status,200);
 return {store,call,ctx};
}
const person=(title)=>({section:'family',kind:'person',title,data:{alternateName:'',birth:'unknown',notes:''}});
test('new members have no private access; original companion does',async()=>{const {call}=await fixture();assert.equal((await call('list',{section:'scrapbook'},guest)).status,403);assert.equal((await call('list',{section:'family'},duck)).status,200);assert.equal((await call('session',{},guest)).permissions.isCore,false);});
test('read contributor editor and own-record rules are checked on the server',async()=>{
 const {call}=await fixture();const a=await call('put',person('Ancestor'));assert.equal(a.status,201);
 await call('grant',{userId:'guest',scope:'family',level:1});
 assert.equal((await call('get',{id:a.record.id},guest)).status,200);
 assert.equal((await call('put',person('Blocked'),guest)).status,403);
 await call('grant',{userId:'guest',scope:'family',level:2});
 const b=await call('put',person('Contribution'),guest);assert.equal(b.status,201);
 assert.equal((await call('put',{...person('Edit other'),id:a.record.id,revision:1},guest)).status,403);
 assert.equal((await call('put',{...person('Own update'),id:b.record.id,revision:1},guest)).status,200);
 assert.equal((await call('grant',{userId:'guest',scope:'family',level:3},guest)).status,403);
});
test('scrapbook and intimate reviews cannot be granted to other users',async()=>{const {call}=await fixture();assert.equal((await call('grant',{userId:'guest',scope:'scrapbook',level:1})).status,400);await call('grant',{userId:'guest',scope:'menus',level:3});assert.equal((await call('list',{section:'menus',kind:'review'},guest)).records.length,0);});
test('edits require revision and preserve history; delete can be restored',async()=>{const {call}=await fixture();const {record:r}=await call('put',person('Before'));assert.equal((await call('put',{...person('One'),id:r.id,revision:1})).status,200);assert.equal((await call('put',{...person('Stale'),id:r.id,revision:1})).status,409);assert.equal((await call('history',{id:r.id})).history.length,2);assert.equal((await call('delete',{id:r.id,revision:2})).status,200);assert.equal((await call('get',{id:r.id})).status,404);assert.equal((await call('restore',{id:r.id,revision:3})).status,200);assert.equal((await call('get',{id:r.id})).record.title,'One');});
test('family contributor cannot use or read a private scrapbook photo',async()=>{const {call}=await fixture();const {record:m}=await call('put',{section:'scrapbook',kind:'media',title:'Private',data:{key:'portal/private.jpg',mime:'image/jpeg',size:20}});await call('grant',{userId:'guest',scope:'family',level:3});assert.equal((await call('get',{id:m.id},guest)).status,404);assert.equal((await call('put',{...person('Leak'),data:{photos:[m.id]}},guest)).status,403);});
test('parent relationships reject cycles and support non-biological parents',async()=>{const {call}=await fixture();const {record:a}=await call('put',person('A'));const {record:b}=await call('put',person('B'));const relation=(from,to,type)=>({section:'family',kind:'relation',title:type,data:{from,to,type}});assert.equal((await call('put',relation(a.id,b.id,'adoptive-parent'))).status,201);assert.equal((await call('put',relation(b.id,a.id,'parent'))).status,400);});
test('published weeks remain unchanged and future weeks keep old snapshots',async()=>{const {call}=await fixture();const {record:w}=await call('put',{section:'menus',kind:'week',title:'Week one',data:{startDate:'2026-10-05',status:'draft'}});const {record:m}=await call('put',{section:'menus',kind:'meal',title:'Rice',parentId:w.id,data:{weekId:w.id,date:'2026-10-05',mealType:'dinner',description:'Rice and vegetables'}});assert.equal((await call('publish',{id:w.id,revision:1})).status,200);assert.equal((await call('put',{...m,revision:1,title:'Overwrite'})).status,409);const pub=await call('publicWeek',{startDate:'2026-10-05'},null);assert.equal(pub.week.meals[0].title,'Rice');assert.equal((await call('delete',{id:w.id,revision:2})).status,409);assert.equal((await call('put',{section:'menus',kind:'week',title:'Next',data:{startDate:'2026-10-12'}})).status,201);assert.equal((await call('publicWeek',{startDate:'2026-10-05'},null)).week.meals[0].title,'Rice');});
test('one-use challenges are consumed atomically; expired challenge is rejected',async()=>{const {call}=await fixture();await call('issueChallenge',{hash:'hash',purpose:'invite',userId:'guest',expires:Date.now()+60000});const got=await Promise.all([call('consumeChallenge',{hash:'hash',purpose:'invite'},null),call('consumeChallenge',{hash:'hash',purpose:'invite'},null)]);assert.deepEqual(got.map(x=>x.status).sort(),[200,400]);await call('issueChallenge',{hash:'expired',purpose:'invite',userId:'guest',expires:1});assert.equal((await call('consumeChallenge',{hash:'expired',purpose:'invite'},null)).status,400);});
test('votes are one per person; nonreaders cannot vote or favourite records',async()=>{const {call}=await fixture();const {record:r}=await call('put',{section:'plans',kind:'poll',title:'Weekend',data:{options:['Zoo','Beach']}});await call('vote',{id:r.id,choice:'Zoo'},duck);await call('vote',{id:r.id,choice:'Beach'},duck);assert.equal((await call('get',{id:r.id})).record.votes.length,1);assert.equal((await call('vote',{id:r.id,choice:'Zoo'},guest)).status,404);assert.equal((await call('favourite',{id:r.id,value:true},guest)).status,404);});
test('record-granted reader cannot see neighbours or private search results',async()=>{const {call}=await fixture();const {record:a}=await call('put',person('Visible'));const {record:b}=await call('put',person('Hidden'));await call('grant',{userId:'guest',scope:'record:'+a.id,level:1});assert.equal((await call('get',{id:a.id},guest)).status,200);assert.equal((await call('get',{id:b.id},guest)).status,404);assert.deepEqual((await call('search',{query:''},guest)).records.map(x=>x.id),[a.id]);});
test('boot cannot replace the original couple; disabled actor denied',async()=>{const {call}=await fixture();assert.equal((await call('boot',{ownerId:'guest',companionId:'x'})).status,409);assert.equal((await call('list',{section:'family'},{...owner,active:false})).status,403);});
test('backup contains all records and revisions; restore rejects missing references',async()=>{const {call}=await fixture();const {record:r}=await call('put',person('Preserved'));const b=await call('export');assert.ok(b.backup.records.some(x=>x.id===r.id));assert.ok(b.backup.history.length);assert.equal((await call('export',{},guest)).status,403);const bad={version:7,records:[{id:'x',section:'family',kind:'relation',title:'Bad',data:{from:'missing',to:'no',type:'parent'}}],weeks:[]};assert.equal((await call('import',{backup:bad})).status,400);});
test('meal-review photos stay private even with menu editing access',async()=>{const {call}=await fixture();const {record:m}=await call('put',{section:'menus',kind:'media',title:'Review photo',data:{key:'portal/private-menu.jpg',mime:'image/jpeg',size:12}});await call('grant',{userId:'guest',scope:'menus',level:3});assert.equal((await call('get',{id:m.id},guest)).status,404);});
test('copying a published week creates an independent draft atomically',async()=>{const {call}=await fixture();const {record:w}=await call('put',{section:'menus',kind:'week',title:'Original',data:{startDate:'2026-10-05'}});await call('put',{section:'menus',kind:'meal',title:'Noodles',parentId:w.id,data:{weekId:w.id,date:'2026-10-06',mealType:'dinner'}});await call('publish',{id:w.id,revision:1});const c=await call('copyWeek',{id:w.id,startDate:'2026-10-12'});assert.equal(c.status,201);assert.equal(c.record.data.status,'draft');assert.equal((await call('list',{section:'menus',kind:'meal',parentId:c.record.id})).records[0].data.date,'2026-10-13');});
test('saved covers cannot be recycled and game favourites are validated',async()=>{const {call}=await fixture();const {record:m}=await call('put',{section:'images',kind:'media',title:'Cover',data:{key:'portal/cover',mime:'image/png',size:20}});assert.equal((await call('preferences',{coverId:m.id,favouriteGames:['wacky-races']})).status,200);assert.equal((await call('delete',{id:m.id,revision:1})).status,409);assert.equal((await call('preferences',{favouriteGames:['../../private']})).status,400);});
test('read-only records expose no comment capability',async()=>{const {call}=await fixture();const {record:r}=await call('put',person('Read me'));await call('grant',{userId:'guest',scope:'family',level:1});assert.equal((await call('get',{id:r.id},guest)).record.canContribute,false);await call('grant',{userId:'guest',scope:'family',level:2});assert.equal((await call('get',{id:r.id},guest)).record.canContribute,true);});
test('restored menu snapshots never expose arbitrary private fields',async()=>{const {call}=await fixture();const b={version:7,records:[],weeks:[{start:'2026-10-05',record_id:'unknown',snapshot:JSON.stringify({startDate:'2026-10-05',title:'Public',secret:'NO',meals:[{id:'m',title:'Rice',date:'2026-10-05',mealType:'dinner',description:'Nice',private:'NEVER'}]})}]};const out=await call('import',{backup:b});if(out.status===200)assert.doesNotMatch(JSON.stringify((await call('publicWeek',{startDate:'2026-10-05'},null)).week),/NEVER|secret/);else assert.equal(out.status,400);});
test('site appearance is owner-managed and only public text reaches visitors',async()=>{const {call}=await fixture();assert.equal((await call('appearance',{headline:'Our home',intro:'Good times',theme:'bold'},duck)).status,403);assert.equal((await call('appearance',{headline:'Our home',intro:'Good times',theme:'bold',password:'NO'})).status,400);assert.equal((await call('appearance',{headline:'Our home',intro:'Good times',theme:'bold'})).status,200);const pub=await call('publicAppearance',{},null);assert.equal(pub.appearance.headline,'Our home');assert.doesNotMatch(JSON.stringify(pub),/ownerId|password/);});
