import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {PortalStore} from '../src/portal/store.mjs';
let createPortalHandler;try{({createPortalHandler}=await import('../src/portal/server.mjs'));}catch{}
const origin='https://duck-bear.test';
function database(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,username TEXT UNIQUE,display_name TEXT,role TEXT,password_hash TEXT,password_salt TEXT,password_iterations INTEGER,active INTEGER DEFAULT 1,created_at TEXT,updated_at TEXT);CREATE TABLE sessions(id TEXT PRIMARY KEY,user_id TEXT,token_hash TEXT UNIQUE,expires_at TEXT,created_at TEXT,last_seen_at TEXT,user_agent TEXT,ip_hash TEXT);CREATE TABLE audit_log(id TEXT PRIMARY KEY,actor_user_id TEXT,action TEXT,entity_type TEXT,entity_id TEXT,detail_json TEXT,created_at TEXT);CREATE TABLE memories(id TEXT,user_id TEXT,title TEXT,body TEXT,happened_on TEXT,attachment_key TEXT,attachment_name TEXT,attachment_type TEXT,attachment_size INTEGER,created_at TEXT);`);const prepare=sql=>({values:[],bind(...v){this.values=v;return this;},async first(){return db.prepare(sql).get(...this.values)||null;},async all(){return {results:db.prepare(sql).all(...this.values)};},async run(){const x=db.prepare(sql).run(...this.values);return {meta:{changes:Number(x.changes)}};}});return {db,prepare,async batch(items){const out=[];for(const x of items)out.push(await x.run());return out;}};}
const base64=buf=>Buffer.from(buf).toString('base64url');const sha=async s=>base64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));
async function fixture(){assert.equal(typeof createPortalHandler,'function','HTTP integration must exist');const DB=database(),sql=new DatabaseSync(':memory:');const store=new PortalStore({storage:{sql:{exec(q,...v){const rows=sql.prepare(q).all(...v);return {toArray:()=>rows};}},transactionSync(fn){sql.exec('BEGIN');try{const r=fn();sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}}},{});const files=new Map();const env={DB,SITE_ORIGIN:origin,PORTAL:{idFromName:()=>1,get:()=>store},MEDIA:{async get(k){return files.get(k)||null;},async put(k,bytes,opts){const buf=typeof bytes==='string'?new TextEncoder().encode(bytes):bytes;files.set(k,{body:buf,httpMetadata:opts?.httpMetadata,size:buf.byteLength,async text(){return new TextDecoder().decode(buf);},async arrayBuffer(){return buf;}});},async delete(k){files.delete(k);}},ASSETS:{async fetch(){return new Response('<!doctype html><title>Portal</title>',{headers:{'Content-Type':'text/html'}});}}};
for(const [id,role] of [['owner','admin'],['duck','member'],['guest','member'],['disabled','member']]){DB.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,id,id,role,'hash','salt',100000,id==='disabled'?0:1,'2026-09-28','2026-09-28');DB.db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?,?,?,?)').run(id+'session',id,await sha(id),new Date(Date.now()+86400000).toISOString(),'2026-09-28','2026-09-28','','');}
DB.db.prepare('INSERT INTO audit_log VALUES(?,?,?,?,?,?,?)').run('setup','owner','setup.complete','system',null,JSON.stringify({memberUserId:'duck'}),'2026-09-28');const handler=createPortalHandler({async fetch(){return new Response('LEGACY PRIVATE',{status:209});}});
const call=async(path,{user='owner',method='GET',body,headers={}}={})=>{const h=new Headers({Origin:origin,...headers});if(user)h.set('Cookie','db_session='+user);let payload;if(body instanceof FormData)payload=body;else if(body!==undefined){h.set('Content-Type','application/json');payload=JSON.stringify(body);}const r=await handler.fetch(new Request(origin+path,{method,headers:h,body:payload}),env,{});return {res:r,status:r.status,data:(r.headers.get('Content-Type')||'').includes('json')?await r.json():await r.text()};};await call('/api/portal/session');return {env,handler,call,store,files};}
test('all legacy media, menu, bootstrap and export paths deny added users',async()=>{const {call}=await fixture();for(const path of ['/media/memories/private.jpg','/media/menu-reviews/private.jpg','/api/bootstrap','/api/menus/dashboard','/api/fun','/api/export/backup.json','/api/admin/dashboard'])assert.ok([401,403,404].includes((await call(path,{user:'guest'})).status),path);assert.equal((await call('/api/bootstrap',{user:'duck'})).status,209);});
test('disabled and signed-out users cannot fetch private records',async()=>{const {call}=await fixture();assert.equal((await call('/api/portal/records?section=family',{user:null})).status,401);assert.equal((await call('/api/portal/records?section=family',{user:'disabled'})).status,403);});
test('direct page deep links return the portal shell without private data',async()=>{const {call}=await fixture();for(const path of ['/family-tree/people/abc/','/settings/email/','/admin/users/abc/permissions/','/scrapbook/albums/abc/','/menus/planner/']){const x=await call(path,{user:null});assert.equal(x.status,200,path);assert.match(x.data,/<!doctype html>/);assert.doesNotMatch(x.data,/LEGACY PRIVATE/);}});
test('POST rejects cross-site request; actor spoofing in body cannot bypass ACL',async()=>{const {call}=await fixture();const body={section:'family',kind:'person',title:'Spoof',data:{},actor:{id:'owner'}};assert.equal((await call('/api/portal/records',{method:'POST',body,user:'guest'})).status,403);assert.equal((await call('/api/portal/records',{method:'POST',body,headers:{Origin:'https://evil.test'}})).status,403);});
test('owner can invite with no default access; invitation is single use',async()=>{const {call}=await fixture();const x=await call('/api/portal/users',{method:'POST',body:{username:'familyfriend',displayName:'Family Friend'}});assert.equal(x.status,201);const token=new URL(x.data.invitationUrl).hash.slice(1);assert.ok(token.length>30);const joined=await call('/api/portal/auth/invite',{method:'POST',user:null,body:{token,password:'a-new-long-password'}});assert.equal(joined.status,200);assert.equal((await call('/api/portal/auth/invite',{method:'POST',user:null,body:{token,password:'another-password'}})).status,400);assert.equal((await call('/api/portal/users',{method:'POST',user:'duck',body:{username:'intruder',displayName:'No'}})).status,403);});
test('private upload bytes are checked and file URL enforces record permission',async()=>{const {call}=await fixture();let form=new FormData();form.set('file',new File(['not an image'],'fake.png',{type:'image/png'}));form.set('section','scrapbook');assert.equal((await call('/api/portal/media',{method:'POST',body:form})).status,400);form=new FormData();form.set('file',new File([Buffer.from('89504e470d0a1a0a0000000d49484452','hex')],'photo.png',{type:'image/png'}));form.set('section','scrapbook');const x=await call('/api/portal/media',{method:'POST',body:form});assert.equal(x.status,201);const url='/media/portal/'+x.data.record.id;assert.equal((await call(url,{user:'duck'})).status,200);assert.equal((await call(url,{user:'guest'})).status,404);assert.equal((await call(url,{user:null})).status,401);});
test('public menus do not expose reviews photos or principal IDs',async()=>{const {call}=await fixture();const x=await call('/api/portal/public/weeks/2026-09-28',{user:null});assert.equal(x.status,200);assert.doesNotMatch(JSON.stringify(x.data),/password|review|kiss|fuck|creator|token_hash|ownerId/);});
test('missing email sender is reported, never claims a reset email was sent',async()=>{const {call}=await fixture();const x=await call('/api/portal/auth/recover',{method:'POST',user:null,body:{email:'nobody@example.com'}});assert.equal(x.status,202);assert.equal(x.data.deliveryReady,false);assert.doesNotMatch(x.data.message,/has been sent/i);});
