const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const sandbox={};for(const f of ['core','models','scenery','shaders','renderer']){const path=__dirname+'/../src/kart-assets/'+f+'.js.txt';if(fs.existsSync(path))vm.runInNewContext(fs.readFileSync(path,'utf8'),sandbox);}
const C=sandbox.KartCore,G=sandbox.KartGeometry;
test('rounded surfaces use continuous finite unit normals',()=>{const m=new G.Mesh();assert.equal(typeof m.roundBox,'function');m.roundBox(0,0,0,2,1,3,'#ffffff');m.cylinder([0,0,0],[0,2,0],1,'#ffffff',18);for(let i=0;i<m.data.length;i+=10){assert.ok(m.data.slice(i,i+10).every(Number.isFinite));const n=m.data.slice(i+3,i+6);assert.ok(Math.abs(Math.hypot(...n)-1)<1e-6);}});
test('every requested snack and hazard has a distinct mesh',()=>{assert.ok(sandbox.WackyModels);const shapes=[];for(const type of ['mango','icecream','blueberry','strawberry','pizza','whiskey']){const m=sandbox.WackyModels.item(type,false);assert.ok(m.data.length>500);shapes.push(JSON.stringify(m.data));}assert.equal(new Set(shapes).size,6);});
test('London and Dublin service vehicles differ in geometry, not only colour',()=>{assert.ok(sandbox.WackyModels);const positions=m=>{const a=[];for(let i=0;i<m.data.length;i+=10)a.push(m.data[i],m.data[i+1],m.data[i+2]);return JSON.stringify(a);};for(const vehicle of ['police','ambulance','bus']){const gb=sandbox.WackyModels.vehicle({vehicle,color:'#cc2244',avatar:'bald-beard'},true,'GB'),ie=sandbox.WackyModels.vehicle({vehicle,color:'#cc2244',avatar:'bald-beard'},true,'IE');assert.notEqual(positions(gb),positions(ie),vehicle);assert.ok(gb.data.every(Number.isFinite));assert.ok(ie.data.every(Number.isFinite));}});
test('Dublin contains named landmark geometry and jokes away from the track',()=>{const t=C.buildTrack(5),m=new G.Mesh(true),info=sandbox.KartScene.build(m,t);for(const name of ['The Spire','GPO','Temple Bar','Ha’penny Bridge','Samuel Beckett Bridge','Poolbeg'])assert.ok(info.labels.some(l=>l.text.includes(name)),name);assert.ok(info.objects.some(o=>o.kind==='sheep'));assert.ok(m.data.every(Number.isFinite));});
test('every circuit exposes a staged hero landmark',()=>{const expected=['BIG BEN','CAMDEN MARKET','TOWER BRIDGE','HYDE PARK','REGENT STREET','The Spire'];for(let i=0;i<6;i++){const m=new G.Mesh(true),info=sandbox.KartScene.build(m,C.buildTrack(i));assert.ok(info.labels.some(l=>l.text.includes(expected[i])),C.TRACKS[i].name+' '+expected[i]);}});
test('parked service scenery is country-correct',()=>{const london=sandbox.KartScene.build(new G.Mesh(true),C.buildTrack(0)).objects.map(o=>o.kind),dublin=sandbox.KartScene.build(new G.Mesh(true),C.buildTrack(5)).objects.map(o=>o.kind);for(const name of ['London bus','London police','London ambulance'])assert.ok(london.includes(name),name);for(const name of ['Dublin bus','Garda car','Irish ambulance'])assert.ok(dublin.includes(name),name);assert.ok(!dublin.includes('London bus'));});
test('every circuit builds within a bounded mesh budget',()=>{for(let i=0;i<6;i++){const m=new G.Mesh(true),info=sandbox.KartScene.build(m,C.buildTrack(i));assert.ok(info.triangles>1000);assert.ok(info.triangles<500000,'triangle budget '+i+': '+info.triangles);}});
