import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync,statSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import vm from 'node:vm';
import {fixture} from './helpers/hq-fixture.mjs';
import * as schema from '../src/hq/schema.mjs';
import {SECTIONS} from '../src/hq/core.mjs';
const root=resolve(import.meta.dirname,'..');
const source=path=>readFileSync(resolve(root,path),'utf8');
const markers=['private-home-imported-v1','legacy-imported-v1','recent-menu-recipes-v1','cooked-korean-fish-chips-2026-10-02-v1','info-library-v1'];
function staticGraph(entry){const found=new Set();function visit(path){if(found.has(path))return;found.add(path);for(const m of source(path).matchAll(/(?:import|export)\s+(?:[^;'"\n]*?\s+from\s*)?['"](\.[^'"]+)['"]/g))visit(resolve(root,dirname(path),m[1]).slice(root.length+1));}visit(entry);return {files:[...found],bytes:[...found].reduce((n,p)=>n+statSync(resolve(root,p)).size,0)};}
function countQueries(env){let calls=0;const original=env.DB.prepare.bind(env.DB);env.DB.prepare=sql=>{calls++;return original(sql);};return ()=>calls;}
test('sign-in static dependency graph fits a 65KB source budget and excludes section code',()=>{const graph=staticGraph('public/hq/app.mjs');assert.ok(graph.bytes<65000,`sign-in loads ${graph.bytes} source bytes before selection`);for(const name of ['trips','views','settings','adults','shop','forms','images'])assert.ok(!graph.files.includes(`public/hq/${name}.mjs`),name);});
test('read-only views do not import editor and image picker modules',()=>{const graph=staticGraph('public/hq/views.mjs');assert.ok(!graph.files.includes('public/hq/forms.mjs'));assert.ok(!graph.files.includes('public/hq/images.mjs'));});
test('each existing route view has an explicit lazy loader',()=>{const path='public/hq/lazy-views.mjs';assert.ok(existsSync(resolve(root,path)));const text=source(path);for(const name of ['recordForm','collectionView','recordView','familyView','scrapbookView','plansView','homeView','tripsView','settingsView','adminView','accessView','imagesView','imageView','shopView','adultsView'])assert.match(text,new RegExp(`export const ${name}\\s*=`));});
test('permission snapshot equals existing policy for owner, partner and guest',async()=>{assert.equal(typeof schema.permissionsForUser,'function');const f=await fixture();try{await schema.initialise(f.env,{id:'owner'});await f.env.DB.prepare("INSERT INTO hq_grants VALUES('guest','family','contribute',0,'owner','now'),('guest','menus','manage',1,'owner','now'),('guest','plans','read',0,'owner','now')").run();for(const id of ['owner','partner','guest']){const actual=await schema.permissionsForUser(f.env,{id});for(const section of SECTIONS)assert.deepEqual(actual[section],await schema.permission(f.env,{id},section),`${id}:${section}`);}}finally{f.close();}});
test('snapshot uses at most two queries and revocations apply immediately',async()=>{assert.equal(typeof schema.permissionsForUser,'function');const f=await fixture();try{await schema.initialise(f.env,{id:'owner'});await f.env.DB.prepare("INSERT INTO hq_grants VALUES('guest','plans','edit',0,'owner','now')").run();const count=countQueries(f.env);const first=await schema.permissionsForUser(f.env,{id:'guest'});assert.equal(first.plans.edit,true);assert.ok(count()<=2);await f.env.DB.prepare("DELETE FROM hq_grants WHERE user_id='guest'").run();const after=await schema.permissionsForUser(f.env,{id:'guest'});assert.equal(after.plans.read,false);assert.equal(after.scrapbook.read,false);assert.equal(after.intimate.read,false);}finally{f.close();}});
test('completed migrations cost one query and no private reads or writes',async()=>{assert.ok(existsSync(resolve(root,'src/hq/readiness.mjs')));const {migrate}=await import('../src/hq/readiness.mjs');const f=await fixture();try{await schema.initialise(f.env,{id:'owner'});for(const key of markers)await f.env.DB.prepare('INSERT INTO hq_meta VALUES(?,?)').bind(key,'done').run();f.env.MEDIA.get=()=>{throw Error('warm request must not read legacy objects');};const count=countQueries(f.env);await migrate(f.env,{id:'owner'});assert.equal(count(),1);}finally{f.close();}});
test('missing markers retry safely and guests cannot run household imports',async()=>{assert.ok(existsSync(resolve(root,'src/hq/readiness.mjs')));const {migrate}=await import('../src/hq/readiness.mjs');const f=await fixture();try{await schema.initialise(f.env,{id:'owner'});await migrate(f.env,{id:'guest'});let result=await f.env.DB.prepare("SELECT COUNT(*) AS n FROM hq_meta WHERE key IN ('private-home-imported-v1','legacy-imported-v1','recent-menu-recipes-v1','info-library-v1')").first();assert.equal(result.n,0);await migrate(f.env,{id:'owner'});result=await f.env.DB.prepare("SELECT COUNT(*) AS n FROM hq_meta WHERE key IN ('private-home-imported-v1','legacy-imported-v1','recent-menu-recipes-v1','info-library-v1')").first();assert.equal(result.n,4);const count=countQueries(f.env);await migrate(f.env,{id:'owner'});assert.equal(count(),1);}finally{f.close();}});
test('me does not repeat authenticated-handler migration work',()=>{const text=source('src/hq/handler.mjs'),body=text.slice(text.indexOf('async function me('),text.indexOf('async function changeGrant'));assert.doesNotMatch(body,/await migrate\(/);assert.match(body,/permissionsForUser/);assert.match(body,/Promise\.all/);});
function homepageContext(){const requests=[],idle=[],timers=[],listeners={};let observe;const document={getElementById:id=>({id}),querySelectorAll:()=>[],readyState:'loading'};const window={addEventListener:(type,fn)=>listeners[type]=fn,requestIdleCallback:fn=>idle.push(fn),IntersectionObserver:true};const context={document,window,navigator:{serviceWorker:{register:()=>Promise.resolve()}},location:{hash:'',replace:()=>{}},fetch:url=>{requests.push(url);return Promise.resolve({ok:false});},IntersectionObserver:class{constructor(fn){observe=fn;}observe(){}disconnect(){}},requestIdleCallback:window.requestIdleCallback,setTimeout:fn=>timers.push(fn)};vm.runInNewContext(source('public/home.js'),context);return {requests,idle,timers,listeners,observe:()=>observe};}
test('offscreen gift catalogue is not fetched at idle when IntersectionObserver exists',async()=>{const c=homepageContext();for(const fn of [...c.idle,...c.timers])fn();await Promise.resolve();assert.ok(!c.requests.includes('/api/public/catalogue'));c.observe()([{isIntersecting:true}]);assert.equal(c.requests.filter(x=>x==='/api/public/catalogue').length,1);c.observe()([{isIntersecting:true}]);assert.equal(c.requests.filter(x=>x==='/api/public/catalogue').length,1);});
test('service-worker installation waits until the first page has loaded',()=>{assert.equal(typeof homepageContext().listeners.load,'function');});
test('shared shells use Causeway favicon, apple icon and manifest',()=>{for(const path of ['public/index.html','public/hq/index.html','public/games/index.html','public/menus/index.html']){const text=source(path);assert.match(text,/rel="icon"[^>]*causeway-v1-32\.png/,path);assert.match(text,/rel="apple-touch-icon"[^>]*causeway-v1-180\.png/,path);assert.match(text,/rel="manifest"/,path);}const m=JSON.parse(source('public/manifest.webmanifest'));assert.ok(m.icons.every(i=>i.src.includes('causeway-v1')));for(const icon of m.icons)assert.ok(existsSync(resolve(root,'public',icon.src.replace(/^\//,''))));});
test('homepage uses responsive WebP with correct intrinsic aspect ratio',()=>{const html=source('public/index.html');assert.match(html,/srcset="[^\"]*causeway-v1-480\.webp 480w, [^\"]*causeway-v1-768\.webp 768w"/);assert.match(html,/width="768" height="576"/);assert.match(html,/fetchpriority="high"/);assert.doesNotMatch(html,/sketch-world\.svg/);assert.ok(statSync(resolve(root,'public/hq/causeway-v1-480.webp')).size<50000);assert.ok(statSync(resolve(root,'public/hq/causeway-v1-768.webp')).size<80000);assert.doesNotMatch(source('public/hq/sketch.css'),/url\(['"]\/hq\/sketch-world\.svg/);});
test('only versioned artwork is immutable; private API responses remain no-store',()=>{const h=source('public/_headers');for(const path of ['/assets/causeway-v1-*','/hq/causeway-v1-*'])assert.ok(h.includes(path+'\n  Cache-Control: public, max-age=31536000, immutable'));assert.match(source('src/hq/core.mjs'),/'cache-control':'private, no-store'/);assert.doesNotMatch(h,/\/api\/\*\s+Cache-Control: public/);});
