"""Real-control acceptance suite against the local Site 1 fixture (not production).
Run: node tests/helpers/site-server.mjs, then python tests/site-browser.py
"""
import json, os, pathlib, base64
from playwright.sync_api import sync_playwright, expect
BASE=os.environ.get('BASE_URL','http://127.0.0.1:8765')
OUT=pathlib.Path(os.environ.get('SITE_SCREENSHOTS','/mnt/data/site-1-previews'));OUT.mkdir(parents=True,exist_ok=True)
errors=[]
def visit(page,path):
    page.goto(BASE+path,wait_until='networkidle')
def login(page,username,password):
    visit(page,'/signin/')
    page.get_by_label('Username or registered email').fill(username)
    page.get_by_label('Password',exact=True).fill(password)
    page.get_by_role('button',name='Come on in').click()
    page.wait_for_url('**/our-space/')
    expect(page.locator('#content h1')).to_contain_text('Hello,')
def no_overflow(page):
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth+1'), 'Horizontal document overflow: '+page.url
with sync_playwright() as p:
    browser=p.chromium.launch(**({'executable_path':os.environ['CHROMIUM_PATH']} if os.environ.get('CHROMIUM_PATH') else {}),headless=True,args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1440,'height':1000},service_workers='block')
    page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
    visit(page,'/');no_overflow(page);page.screenshot(path=str(OUT/'home-desktop.png'),full_page=True)
    login(page,'duck','partner-password-123')
    page.screenshot(path=str(OUT/'our-space-desktop.png'),full_page=True)
    visit(page,'/menus/library/')
    page.get_by_role('button',name='Add a meal').click()
    page.get_by_label('Meal name',exact=True).fill('Browser-test sesame noodles')
    page.get_by_label('Ingredients',exact=True).fill('Noodles, sesame, spring onions')
    page.get_by_label('Description & plating notes').fill('A test meal for checking the editor.')
    page.get_by_role('button',name='Save',exact=True).click()
    expect(page.locator('#editor')).not_to_be_visible()
    page.reload(wait_until='networkidle')
    expect(page.get_by_role('heading',name='Browser-test sesame noodles')).to_be_visible()
    visit(page,'/menus/planner/')
    page.get_by_role('button',name='Start a week').click()
    page.get_by_label('Week title').fill('Browser-test cosy week')
    page.get_by_label('Week starting Monday').fill('2026-10-05')
    page.get_by_role('button',name='Add a meal slot').click()
    page.get_by_label('Choose from your notebook').select_option(label='Browser-test sesame noodles')
    page.get_by_role('button',name='Save',exact=True).click()
    page.wait_for_url('**/menus/planner/?week=*')
    expect(page.locator('#week-content')).to_contain_text('Browser-test sesame noodles')
    page.get_by_role('button',name='Publish to readers').click()
    expect(page.locator('#week-content')).to_contain_text('Published to menu readers')
    page.screenshot(path=str(OUT/'planner-desktop.png'),full_page=True)
    page.get_by_role('button',name='Copy to another week').click()
    page.get_by_label('New week starting Monday').fill('2026-10-12')
    page.get_by_role('button',name='Copy week',exact=True).click()
    expect(page.locator('#editor')).not_to_be_visible()
    page.wait_for_load_state('networkidle')
    expect(page.locator('#week-content')).to_contain_text('Draft · contributors only')
    visit(page,'/family/')
    for name in ['Example parent','Example child']:
        page.get_by_role('button',name='Add a person').click()
        page.get_by_label('Name',exact=True).fill(name)
        page.get_by_role('button',name='Save',exact=True).click()
        expect(page.locator('#editor')).not_to_be_visible()
        expect(page.get_by_role('heading',name=name,exact=True)).to_be_visible()
    page.get_by_role('button',name='Connect two people').click()
    page.get_by_label('First person (parent for a parent-child link)').select_option(label='Example parent')
    page.get_by_label('Second person (child for a parent-child link)').select_option(label='Example child')
    page.get_by_role('button',name='Add connection').click()
    expect(page.locator('#editor')).not_to_be_visible()
    expect(page.locator('#family-tree')).to_contain_text('Generation 2')
    visit(page,'/scrapbook/')
    page.get_by_role('button',name='Keep a memory').click()
    page.get_by_label('Title',exact=True).fill('Browser-test garden afternoon')
    page.get_by_label('The story').fill('Illustrative test data, not a real personal memory.')
    page.get_by_label('Where',exact=True).fill('Example garden')
    page.locator('#editor input[type=file]').set_input_files({'name':'fixture.png','mimeType':'image/png','buffer':base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAFklEQVR4nGNo3jqRJMQwqmFUw/DVAADmBckQ4HocmQAAAABJRU5ErkJggg==')})
    page.get_by_label('Tags (separated by commas)').fill('test, garden')
    page.get_by_role('button',name='Save',exact=True).click()
    expect(page.locator('#editor')).not_to_be_visible()
    page.get_by_role('button',name='Open photo for Browser-test garden afternoon').click()
    expect(page.locator('#photo-viewer')).to_be_visible()
    page.get_by_role('button',name='Close photo',exact=True).click()
    page.get_by_role('button',name='♡ Favourite',exact=True).click()
    expect(page.get_by_role('button',name='♥ Favourite',exact=True)).to_have_attribute('aria-pressed','true')
    page.get_by_role('checkbox',name='Favourites only').check()
    expect(page.get_by_role('heading',name='Browser-test garden afternoon')).to_be_visible()
    page.reload(wait_until='networkidle')
    expect(page.get_by_role('heading',name='Browser-test garden afternoon')).to_be_visible()
    page.screenshot(path=str(OUT/'scrapbook-desktop.png'),full_page=True)
    # Mobile geometry and navigation use exactly the same persisted records.
    page.set_viewport_size({'width':390,'height':844})
    for path,name in [('/','home-mobile'),('/our-space/','our-space-mobile'),('/menus/planner/','planner-mobile'),('/family/','family-mobile'),('/scrapbook/','scrapbook-mobile'),('/settings/','settings-mobile')]:
        visit(page,path);no_overflow(page);page.screenshot(path=str(OUT/(name+'.png')),full_page=True)
    # A second browser context proves stored records are shared with the original owner.
    owner=browser.new_context(viewport={'width':1440,'height':1000},service_workers='block');op=owner.new_page();op.on('pageerror',lambda e:errors.append(str(e)))
    login(op,'bear','owner-password-123');visit(op,'/scrapbook/');expect(op.get_by_role('heading',name='Browser-test garden afternoon')).to_be_visible()
    visit(op,'/settings/users/');op.get_by_role('button',name='Add a user').click()
    op.get_by_label('Username (3–30 letters, numbers, dots or underscores)').fill('browserguest')
    op.get_by_label('Display name',exact=True).fill('Browser-test guest')
    op.get_by_label('Temporary password (12–128 characters)').fill('browser-guest-password')
    op.get_by_role('button',name='Create user').click();expect(op.locator('#editor')).not_to_be_visible()
    expect(op.get_by_role('heading',name='Browser-test guest')).to_be_visible()
    visit(op,'/settings/permissions/');card=op.locator('section').filter(has=op.get_by_role('heading',name='Browser-test guest'))
    card.locator('select[name="family"]').select_option('1');card.get_by_role('button',name='Save permissions').click()
    expect(op.locator('#toast')).to_contain_text('Permissions saved')
    op.screenshot(path=str(OUT/'permissions-desktop.png'),full_page=True)
    guest=browser.new_context(service_workers='block');gp=guest.new_page();login(gp,'browserguest','browser-guest-password')
    visit(gp,'/family/');expect(gp.get_by_role('heading',name='Example child',exact=True)).to_be_visible();expect(gp.get_by_role('button',name='Add a person')).to_have_count(0)
    visit(gp,'/scrapbook/');expect(gp.get_by_role('heading',name='A private little corner')).to_be_visible()
    # Email registration through the actual form, and cross-context email login.
    visit(page,'/settings/security/');email=page.locator('#email-form');email.get_by_label('Email address').fill('duck.fixture@example.test');email.get_by_label('Current password').fill('partner-password-123');email.get_by_role('button',name='Save email').click();expect(page.locator('#toast')).to_contain_text('Email registered')
    fresh=browser.new_context(service_workers='block');fp=fresh.new_page();login(fp,'duck.fixture@example.test','partner-password-123')
    assert not errors,errors
    report={'result':'passed','runtime':'local actual Worker handlers + SQLite/R2 test adapters','browser':'Chromium','viewports':[1440,390],'checks':['public/private navigation','real login and email registration','meal create and reload','week save/publish/copy','family parent connection','scrapbook photo upload/viewer/favourite/reload','cross-context persistence','user creation','read-only grant','unrelated user scrapbook denial','no horizontal overflow','no uncaught browser errors'],'screenshots':sorted(p.name for p in OUT.glob('*.png'))}
    (OUT/'browser-report.json').write_text(json.dumps(report,indent=2));print(json.dumps(report,indent=2));browser.close()
