import {fail,json,body,plain,now,uid,hash,query,boundedBytes,MAX_FILE_BYTES,privateHeaders,byteRange,downloadDisposition,BOOKS_BUILD} from './util.mjs';
import {cleanMetadata,formatFor,mimeFor,inspectZip} from './metadata.mjs';
import {connectionStatus,beginOAuth,finishOAuth,setLibraryRoot,pickerConfiguration,disconnectGoogle,verifyFileInLibrary,driveRequest} from './google.mjs';
import {startScan,stepScan,scanStatus} from './import.mjs';
import {fileRecord,readProgress,saveProgress,listAnnotations,saveAnnotation} from './state.mjs';
const PREFIX='/api/hq/books';
export async function bookData(env,user,id){const b=await env.DB.prepare('SELECT b.*,u.status,u.favourite,u.rating FROM books_catalogue b LEFT JOIN books_user_books u ON u.book_id=b.id AND u.user_id=? WHERE b.id=?').bind(user.id,id).first();if(!b)fail(404,'That book is not in the library.');const files=await query(env.DB,"SELECT id,name,mime,format,version,size,available FROM books_files WHERE book_id=? AND format NOT IN ('jpg','png','webp') ORDER BY CASE format WHEN 'epub' THEN 0 WHEN 'pdf' THEN 1 ELSE 2 END",id);return {...publicBook(b),files:files.map(f=>({...f,available:Boolean(f.available)})),progress:await Promise.all(files.map(f=>readProgress(env,user,f.id,f.version)))};}
function publicBook(b){return {id:b.id,title:b.title,authors:JSON.parse(b.authors_json),series:b.series,seriesIndex:b.series_index,description:b.description,language:b.language,tags:JSON.parse(b.tags_json),importedRating:b.imported_rating,cover:b.cover_file_id?PREFIX+'/files/'+b.cover_file_id+'/content':null,status:b.status||'none',favourite:Boolean(b.favourite),rating:b.rating??null,source:b.source,updatedAt:b.updated_at,unavailable:Boolean(b.unavailable)};}
export async function catalogue(env,user,url){const search=plain(url.searchParams.get('q'),150),filter=url.searchParams.get('filter')||'all',shelf=url.searchParams.get('shelf'),limit=Math.min(60,Math.max(1,Number(url.searchParams.get('limit'))||36)),offset=Math.max(0,Number(url.searchParams.get('offset'))||0);if(!Number.isSafeInteger(offset)||offset>100000)fail(400,'Invalid page.');const where=['1=1'],values=[user.id];if(search){where.push("(b.title LIKE ? ESCAPE '\\' OR b.authors_json LIKE ? ESCAPE '\\' OR b.series LIKE ? ESCAPE '\\')");const q='%'+search.replace(/[\\%_]/g,'\\$&')+'%';values.push(q,q,q);}if(['reading','finished','want'].includes(filter)){where.push('u.status=?');values.push(filter);}else if(filter==='favourites')where.push('u.favourite=1');if(shelf){where.push('EXISTS(SELECT 1 FROM books_shelf_items i JOIN books_shelves s ON s.id=i.shelf_id WHERE i.book_id=b.id AND i.shelf_id=? AND s.user_id=?)');values.push(shelf,user.id);}const from=' FROM books_catalogue b LEFT JOIN books_user_books u ON u.book_id=b.id AND u.user_id=? WHERE '+where.join(' AND ');const rows=await query(env.DB,'SELECT b.*,u.status,u.favourite,u.rating'+from+' ORDER BY b.title COLLATE NOCASE,b.id LIMIT ? OFFSET ?',...values,limit,offset);const total=(await env.DB.prepare('SELECT COUNT(*) AS n'+from).bind(...values).first()).n;return {books:rows.map(publicBook),total,offset,nextOffset:offset+rows.length<total?offset+rows.length:null};}
async function upload(env,user,request,url){if(!env.MEDIA)fail(503,'Book uploads have no storage binding.','storage_unavailable');const name=plain(url.searchParams.get('name'),240).replace(/[\\/]/g,'_'),format=formatFor(name);if(!['epub','pdf'].includes(format))fail(415,'Upload a DRM-free EPUB or PDF. Other formats can remain in Drive for download.');const bytes=await boundedBytes(request,MAX_FILE_BYTES);if(bytes.length<5)fail(400,'That file is empty or damaged.');if(format==='epub')inspectZip(bytes);else if(new TextDecoder().decode(bytes.subarray(0,5))!=='%PDF-')fail(400,'This file is not a PDF.');const checksum=await hash(bytes),fileId='u_'+checksum.slice(0,32);const existing=await env.DB.prepare('SELECT book_id FROM books_files WHERE id=?').bind(fileId).first();if(existing)return {book:await bookData(env,user,existing.book_id),duplicate:true};const bookId=uid('b_'),key='books/uploads/'+checksum,time=now();await env.MEDIA.put(key,bytes,{httpMetadata:{contentType:mimeFor(format)}});await env.DB.batch([
 env.DB.prepare('INSERT INTO books_catalogue(id,source,source_group,title,created_by,updated_at,created_at) VALUES(?,\'upload\',?,?,?,?,?)').bind(bookId,'upload:'+checksum,name.replace(/\.[^.]+$/,''),user.id,time,time),
 env.DB.prepare('INSERT INTO books_files(id,book_id,provider,name,mime,format,version,size,object_key,modified_at) VALUES(?,?,\'upload\',?,?,?,?,?,?,?)').bind(fileId,bookId,name,mimeFor(format),format,checksum,bytes.length,key,time)
 ]);return {book:await bookData(env,user,bookId),duplicate:false};}
async function updateMetadata(env,user,id,input){const existing=await bookData(env,user,id);if(existing.source!=='upload')fail(400,'Imported metadata remains sourced from Calibre. Edit that source and rescan.');const m=cleanMetadata(input);await env.DB.prepare('UPDATE books_catalogue SET title=?,authors_json=?,series=?,series_index=?,description=?,language=?,tags_json=?,identifiers_json=?,imported_rating=?,metadata_json=?,updated_at=? WHERE id=?').bind(m.title,JSON.stringify(m.authors),m.series,m.seriesIndex,m.description,m.language,JSON.stringify(m.tags),JSON.stringify(m.identifiers),m.importedRating,JSON.stringify(m),now(),id).run();return {book:await bookData(env,user,id)};}
async function uploadCover(env,user,id,request){const book=await bookData(env,user,id);if(book.source!=='upload')fail(400,'Drive covers remain read-only.');const bytes=await boundedBytes(request,3*1024*1024);let format;if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)format='jpg';else if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)format='png';else if(new TextDecoder().decode(bytes.subarray(0,4))==='RIFF'&&new TextDecoder().decode(bytes.subarray(8,12))==='WEBP')format='webp';else fail(415,'Covers must be JPEG, PNG or WebP.');const checksum=await hash(bytes),fileId='c_'+id,key='books/covers/'+id+'/'+checksum;await env.MEDIA.put(key,bytes,{httpMetadata:{contentType:mimeFor(format)}});await env.DB.batch([env.DB.prepare('INSERT INTO books_files(id,book_id,provider,name,mime,format,version,size,object_key,modified_at) VALUES(?,?,\'upload\',?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,mime=excluded.mime,format=excluded.format,version=excluded.version,size=excluded.size,object_key=excluded.object_key,modified_at=excluded.modified_at').bind(fileId,id,'cover.'+format,mimeFor(format),format,checksum,bytes.length,key,now()),env.DB.prepare('UPDATE books_catalogue SET cover_file_id=? WHERE id=?').bind(fileId,id)]);return {cover:PREFIX+'/files/'+fileId+'/content'};}
async function content(env,fileId,request,url){const f=await fileRecord(env,fileId);if(!f.available)fail(410,'The original file is no longer available.','file_unavailable');const requestedVersion=url.searchParams.get('version');if(requestedVersion&&requestedVersion!==f.version)fail(409,'The book file has changed. Reopen its details before downloading.','version_changed');const range=byteRange(request.headers.get('range'),f.size);let stream;const headers={...privateHeaders(f.mime),'accept-ranges':'bytes','cross-origin-resource-policy':'same-origin','x-frame-options':'SAMEORIGIN','x-books-version':f.version};if(url.searchParams.get('download')==='1')headers['content-disposition']=downloadDisposition(f.name);if(range){headers['content-range']=`bytes ${range.start}-${range.end}/${f.size}`;headers['content-length']=String(range.end-range.start+1);}else headers['content-length']=String(f.size);
 if(f.provider==='upload'){const object=await env.MEDIA.get(f.object_key,range?{range:{offset:range.start,length:range.end-range.start+1}}:{});if(!object)fail(410,'The uploaded file is no longer available.','file_unavailable');stream=object.body;}else{await verifyFileInLibrary(env,f.source_id,f.version);const response=await driveRequest(env,'files/'+f.source_id,{alt:'media',supportsAllDrives:true},{headers:range?{range:`bytes=${range.start}-${range.end}`}:{}});if(range&&response.status!==206)fail(502,'Google did not return the requested file range.','range_unavailable');stream=response.body;if(!range&&response.headers.get('content-length'))headers['content-length']=response.headers.get('content-length');}
 return new Response(request.method==='HEAD'?null:stream,{status:range?206:200,headers});}
async function userBook(env,user,id,b){await bookData(env,user,id);const current=await env.DB.prepare('SELECT * FROM books_user_books WHERE user_id=? AND book_id=?').bind(user.id,id).first();const status=b.status??current?.status??'none';if(!['none','want','reading','finished'].includes(status))fail(400,'Choose a valid reading status.');const rating=b.rating===undefined?(current?.rating??null):b.rating;if(rating!==null&&(!Number.isInteger(rating)||rating<1||rating>5))fail(400,'Rating must be between one and five.');const favourite=b.favourite===undefined?(current?.favourite||0):(b.favourite===true?1:0);await env.DB.prepare('INSERT INTO books_user_books(user_id,book_id,status,favourite,rating,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id,book_id) DO UPDATE SET status=excluded.status,favourite=excluded.favourite,rating=excluded.rating,updated_at=excluded.updated_at').bind(user.id,id,status,favourite,rating,now()).run();return {book:await bookData(env,user,id)};}
export async function booksApi(request,env,user,hooks,url){const path=url.pathname,method=request.method;let match;
 if(path.startsWith('/api/hq/integrations/google-drive/')){await hooks.requireOwner(env,user);const action=path.split('/').pop();if(action==='status'&&method==='GET')return json(await connectionStatus(env));if(action==='start'&&method==='POST')return beginOAuth(request,env,user,await body(request));if(action==='callback'&&method==='GET')return finishOAuth(request,env,user);if(action==='root'&&method==='PUT')return json(await setLibraryRoot(env,(await body(request)).folder));if(action==='picker'&&method==='GET')return json(await pickerConfiguration(env));if(action==='disconnect'&&method==='POST')return json(await disconnectGoogle(env));fail(404,'This connection action does not exist.');}
 if(path===PREFIX+'/me'&&method==='GET')return json({user:{id:user.id,displayName:user.display_name||user.username||'Reader'},owner:await hooks.isOwner(env,user),build:BOOKS_BUILD});
 if(path===PREFIX+'/catalogue'&&method==='GET')return json(await catalogue(env,user,url));
 if(path===PREFIX+'/uploads'&&method==='PUT')return json(await upload(env,user,request,url),201);
 if(path===PREFIX+'/scan'&&method==='POST'){await hooks.requireOwner(env,user);return json(await startScan(env),201);}
 if(path===PREFIX+'/scan/latest'&&method==='GET'){await hooks.requireOwner(env,user);const r=await env.DB.prepare('SELECT id FROM books_scan_jobs ORDER BY created_at DESC LIMIT 1').first();return json(r?await scanStatus(env,r.id):null);}
 match=path.match(/^\/api\/hq\/books\/scan\/([\w-]+)(\/step)?$/);if(match){await hooks.requireOwner(env,user);if(method==='GET'&&!match[2])return json(await scanStatus(env,match[1]));if(method==='POST'&&match[2])return json(await stepScan(env,match[1]));}
 match=path.match(/^\/api\/hq\/books\/files\/([\w-]+)\/(content|progress|annotations)$/);if(match){const [,id,action]=match;if(action==='content'&&['GET','HEAD'].includes(method))return content(env,id,request,url);const f=await fileRecord(env,id);if(action==='progress'&&method==='GET')return json(await readProgress(env,user,id,url.searchParams.get('version')||f.version));if(action==='progress'&&method==='PUT')return json(await saveProgress(env,user,id,await body(request)));if(action==='annotations'&&method==='GET')return json({annotations:await listAnnotations(env,user,id,url.searchParams.get('version')||f.version)});}
 match=path.match(/^\/api\/hq\/books\/annotations\/([\w-]+)$/);if(match&&method==='PUT')return json(await saveAnnotation(env,user,match[1],await body(request)));
 if(path===PREFIX+'/shelves'&&method==='GET')return json({shelves:await query(env.DB,'SELECT s.id,s.name,COUNT(i.book_id) AS count FROM books_shelves s LEFT JOIN books_shelf_items i ON i.shelf_id=s.id WHERE s.user_id=? GROUP BY s.user_id,s.id ORDER BY s.name',user.id)});
 if(path===PREFIX+'/shelves'&&method==='POST'){const name=plain((await body(request)).name,80);if(!name)fail(400,'Give the collection a name.');const id=uid('s_');await env.DB.prepare('INSERT INTO books_shelves VALUES(?,?,?,?)').bind(id,user.id,name,now()).run();return json({id,name},201);}
 match=path.match(/^\/api\/hq\/books\/shelves\/([\w-]+)(?:\/([\w-]+))?$/);if(match){const shelf=await env.DB.prepare('SELECT id FROM books_shelves WHERE id=? AND user_id=?').bind(match[1],user.id).first();if(!shelf)fail(404,'That collection is not yours.');if(match[2]&&method==='PUT'){await bookData(env,user,match[2]);const b=await body(request);if(b.saved===true)await env.DB.prepare('INSERT OR IGNORE INTO books_shelf_items VALUES(?,?)').bind(match[1],match[2]).run();else await env.DB.prepare('DELETE FROM books_shelf_items WHERE shelf_id=? AND book_id=?').bind(match[1],match[2]).run();return json({ok:true});}if(!match[2]&&method==='DELETE'){await env.DB.prepare('DELETE FROM books_shelves WHERE id=? AND user_id=?').bind(match[1],user.id).run();return json({ok:true});}}
 if(path===PREFIX+'/export'&&method==='GET'){const progress=await query(env.DB,'SELECT * FROM books_read_state WHERE user_id=?',user.id),annotations=await query(env.DB,'SELECT * FROM books_annotations WHERE user_id=?',user.id),choices=await query(env.DB,'SELECT * FROM books_user_books WHERE user_id=?',user.id),shelves=await query(env.DB,'SELECT * FROM books_shelves WHERE user_id=?',user.id),shelfItems=await query(env.DB,'SELECT i.* FROM books_shelf_items i JOIN books_shelves s ON s.id=i.shelf_id WHERE s.user_id=?',user.id);return json({schema:'duck-bear-reading-v1',exportedAt:now(),userId:user.id,progress,annotations,choices,shelves,shelfItems},200,{'content-disposition':downloadDisposition('duck-bear-reading.json')});}
 if(path===PREFIX+'/preferences'&&method==='GET'){const p=await env.DB.prepare('SELECT data_json FROM books_preferences WHERE user_id=?').bind(user.id).first();return json(p?JSON.parse(p.data_json):{});}
 if(path===PREFIX+'/preferences'&&method==='PUT'){const b=await body(request);const settings={theme:['light','dark','sepia'].includes(b.theme)?b.theme:'light',font:['serif','sans'].includes(b.font)?b.font:'serif',fontSize:Math.min(36,Math.max(14,Number(b.fontSize)||20)),lineHeight:Math.min(2.5,Math.max(1.2,Number(b.lineHeight)||1.7)),margin:Math.min(80,Math.max(8,Number(b.margin)||28)),flow:b.flow==='scrolled'?'scrolled':'paginated'};await env.DB.prepare('INSERT INTO books_preferences VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at').bind(user.id,JSON.stringify(settings),now()).run();return json(settings);}
 match=path.match(/^\/api\/hq\/books\/([\w-]+)(?:\/(user|metadata|cover))?$/);if(match){const [,id,action]=match;if(!action&&method==='GET')return json({book:await bookData(env,user,id)});if(action==='user'&&method==='PUT')return json(await userBook(env,user,id,await body(request)));if(action==='metadata'&&method==='PUT')return json(await updateMetadata(env,user,id,await body(request)));if(action==='cover'&&method==='PUT')return json(await uploadCover(env,user,id,request));}
 fail(404,'This book action does not exist.');}
