import {BooksError,fail,json,sameOrigin,privateHeaders} from './util.mjs';import {ensureBooksSchema} from './schema.mjs';import {booksApi} from './api.mjs';
export const booksEnabled=env=>['true','1'].includes(String(env.BOOKS_ENABLED||''));
export const isBooksPath=path=>path==='/books'||path.startsWith('/books/')||path.startsWith('/api/hq/books/')||path.startsWith('/api/hq/integrations/google-drive/');
export function createBooksHandler(fallback,hooks){return {async fetch(request,env,ctx){const url=new URL(request.url),path=url.pathname;if(!isBooksPath(path))return fallback.fetch(request,env,ctx);if(!booksEnabled(env))return json({error:'Books is not enabled on this environment.',code:'books_disabled'},404);try{const codeAsset=/^\/books\/(?:vendor\/|.*\.(?:mjs|js|css|json|svg|png|webp)$)/.test(path);if(codeAsset){if(!['GET','HEAD'].includes(request.method))fail(405,'Use GET.');const asset=await env.ASSETS.fetch(request);const h=new Headers(asset.headers);h.set('cache-control','public, max-age=300');if(path==='/books/sw.js'){h.set('cache-control','no-cache');h.set('service-worker-allowed','/books/');}return new Response(asset.body,{status:asset.status,headers:h});}
 const user=await hooks.authenticate(request,env);if(!user){if(path.startsWith('/books'))return new Response(null,{status:302,headers:{location:'/sign-in/?next='+encodeURIComponent(path+url.search),'cache-control':'no-store'}});fail(401,'Please sign in to Duck & Bear.','sign_in');}
 await hooks.requirePair(env,user);sameOrigin(request);await ensureBooksSchema(env);
 if(path.startsWith('/api/'))return await booksApi(request,env,user,hooks,url);
 if(!['GET','HEAD'].includes(request.method))fail(405,'Use GET.');const asset=await env.ASSETS.fetch(new Request(new URL('/books/',url)));const csp="default-src 'self'; script-src 'self' https://apis.google.com https://www.gstatic.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' blob: data:; connect-src 'self'; frame-src 'self' blob: https://docs.google.com https://drive.google.com https://accounts.google.com; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'";return new Response(request.method==='HEAD'?null:asset.body,{status:asset.status,headers:{...privateHeaders('text/html; charset=utf-8'),'content-security-policy':csp,'x-robots-tag':'noindex, nofollow, noarchive'}});
 }catch(e){if(e instanceof BooksError||Number.isInteger(e.status))return json({error:e.message,code:e.code||'books_error',details:e.details},e.status);console.error('Books request failed',e.name);return json({error:'The book request could not be completed. Your saved reading records have not been removed.',code:'books_internal'},500);}}};}
