import {fail,uid,now,query,hash,plain} from './util.mjs';
import {driveJson,opfFromDrive,verifyFileInLibrary} from './google.mjs';
import {formatFor,mimeFor,parseCalibreOpf,cleanMetadata} from './metadata.mjs';
const FOLDER='application/vnd.google-apps.folder',SHORTCUT='application/vnd.google-apps.shortcut';
export async function startScan(env){const c=await env.DB.prepare("SELECT root_id,token_cipher FROM books_connections WHERE id='google-drive'").first();if(!c?.token_cipher||!c.root_id)fail(409,'Connect Google Drive and choose the eBooks folder first.','not_connected');const running=await env.DB.prepare("SELECT id FROM books_scan_jobs WHERE status='running' AND root_id=?").bind(c.root_id).first();if(running)return scanStatus(env,running.id);const id=uid('scan_'),time=now();await env.DB.batch([
 env.DB.prepare('INSERT INTO books_scan_jobs(id,root_id,status,created_at,updated_at) VALUES(?,?,\'running\',?,?)').bind(id,c.root_id,time,time),
 env.DB.prepare('INSERT INTO books_scan_queue(job_id,folder_id) VALUES(?,?)').bind(id,c.root_id),
 env.DB.prepare('INSERT INTO books_manifest(file_id,parent_id,kind,metadata_json,seen_job) VALUES(?,NULL,\'folder\',\'{}\',?) ON CONFLICT(file_id) DO UPDATE SET parent_id=NULL,seen_job=excluded.seen_job').bind(c.root_id,id)
 ]);return scanStatus(env,id);}
export async function scanStatus(env,id){const job=await env.DB.prepare('SELECT * FROM books_scan_jobs WHERE id=?').bind(id).first();if(!job)fail(404,'This scan does not exist.');const counts=await env.DB.prepare("SELECT COUNT(*) AS total,SUM(CASE WHEN status='done' THEN 1 ELSE 0 END) AS done FROM books_scan_queue WHERE job_id=?").bind(id).first();return {id:job.id,status:job.status,filesSeen:job.files_seen,booksSeen:job.books_seen,foldersTotal:counts.total,foldersDone:counts.done||0,warnings:JSON.parse(job.errors_json),updatedAt:job.updated_at};}
async function warning(env,jobId,message){const r=await env.DB.prepare('SELECT errors_json FROM books_scan_jobs WHERE id=?').bind(jobId).first();const warnings=JSON.parse(r.errors_json);if(!warnings.includes(message))warnings.push(message);await env.DB.prepare('UPDATE books_scan_jobs SET errors_json=? WHERE id=?').bind(JSON.stringify(warnings.slice(-30)),jobId).run();}
export async function stepScan(env,id){const job=await env.DB.prepare('SELECT * FROM books_scan_jobs WHERE id=?').bind(id).first();if(!job)fail(404,'This scan does not exist.');if(job.status!=='running')return scanStatus(env,id);const c=await env.DB.prepare("SELECT root_id FROM books_connections WHERE id='google-drive'").first();if(c?.root_id!==job.root_id)fail(409,'The library folder changed. Start a new scan.','root_changed');if(job.files_seen>100000)fail(413,'This scan reached the 100,000-item safety limit.','scan_limit');const lease=uid(),until=Date.now()+45000;
 const claimed=await env.DB.prepare(`UPDATE books_scan_queue SET status='working',lease=?,locked_until=? WHERE job_id=? AND folder_id=(SELECT folder_id FROM books_scan_queue WHERE job_id=? AND (status='queued' OR (status='working' AND locked_until<?)) ORDER BY folder_id LIMIT 1) RETURNING *`).bind(lease,until,id,id,Date.now()).all();const queue=claimed.results?.[0];if(!queue){const pending=await env.DB.prepare("SELECT COUNT(*) AS n FROM books_scan_queue WHERE job_id=? AND status!='done'").bind(id).first();if(!pending.n){await env.DB.prepare("UPDATE books_scan_jobs SET status=CASE WHEN books_seen=0 THEN 'empty' ELSE 'complete' END,updated_at=? WHERE id=?").bind(now(),id).run();if(job.books_seen===0)await warning(env,id,'No books were visible to this app. The library may be empty or Google permissions may exclude existing nested files; no original files or reading records were removed.');}return scanStatus(env,id);}
 try{
  if(queue.folder_id!==job.root_id)await verifyFileInLibrary(env,queue.folder_id);
  const response=await driveJson(env,'files',{q:`'${queue.folder_id}' in parents and trashed=false`,pageSize:100,pageToken:queue.page_token||undefined,fields:'nextPageToken,files(id,name,mimeType,parents,size,md5Checksum,modifiedTime,trashed)',supportsAllDrives:true,includeItemsFromAllDrives:true});
  const statements=[];for(const f of response.files||[]){if(!/^[\w-]{10,200}$/.test(f.id)||f.trashed)continue;if(f.mimeType===SHORTCUT){await warning(env,id,'Shortcuts are not followed because they may point outside the selected library.');continue;}if(f.parents?.[0]&&f.parents[0]!==queue.folder_id)continue;const kind=f.mimeType===FOLDER?'folder':'file';statements.push(env.DB.prepare('INSERT INTO books_manifest(file_id,parent_id,kind,metadata_json,seen_job) VALUES(?,?,?,?,?) ON CONFLICT(file_id) DO UPDATE SET parent_id=excluded.parent_id,kind=excluded.kind,metadata_json=excluded.metadata_json,seen_job=excluded.seen_job').bind(f.id,queue.folder_id,kind,JSON.stringify(f),id));if(kind==='folder')statements.push(env.DB.prepare('INSERT OR IGNORE INTO books_scan_queue(job_id,folder_id) VALUES(?,?)').bind(id,f.id));}
  if(statements.length)await env.DB.batch(statements);
  await env.DB.prepare('UPDATE books_scan_jobs SET files_seen=files_seen+?,updated_at=? WHERE id=?').bind((response.files||[]).length,now(),id).run();
  if(response.nextPageToken){await env.DB.prepare("UPDATE books_scan_queue SET status='queued',page_token=?,locked_until=0,lease=NULL WHERE job_id=? AND folder_id=? AND lease=?").bind(response.nextPageToken,id,queue.folder_id,lease).run();}
  else {const count=await finaliseFolder(env,id,queue.folder_id);await env.DB.batch([env.DB.prepare("UPDATE books_scan_queue SET status='done',locked_until=0,lease=NULL WHERE job_id=? AND folder_id=? AND lease=?").bind(id,queue.folder_id,lease),env.DB.prepare('UPDATE books_scan_jobs SET books_seen=books_seen+? WHERE id=?').bind(count,id)]);}
 }catch(e){await env.DB.prepare("UPDATE books_scan_queue SET status='queued',locked_until=0,lease=NULL WHERE job_id=? AND folder_id=? AND lease=?").bind(id,queue.folder_id,lease).run();throw e;}
 return scanStatus(env,id);
}
export async function finaliseFolder(env,jobId,parent){const rows=await query(env.DB,'SELECT metadata_json FROM books_manifest WHERE parent_id=? AND kind=\'file\' AND seen_job=?',parent,jobId);const files=rows.map(r=>JSON.parse(r.metadata_json));const books=files.filter(f=>formatFor(f.name));if(!books.length)return 0;const sidecar=files.find(f=>f.name.toLowerCase()==='metadata.opf');const cover=files.find(f=>/^cover\.(jpe?g|png|webp)$/i.test(f.name));let parsed=null;if(sidecar){try{parsed=parseCalibreOpf(await opfFromDrive(env,sidecar.id));}catch{await warning(env,jobId,'At least one metadata.opf could not be read. The original files are unchanged and filenames were used instead.');}}
 const onePerFormat=new Set(books.map(f=>formatFor(f.name))).size===books.length;
 const groups=parsed&&onePerFormat?[{key:parent,files:books,metadata:parsed,cover}]:books.map(f=>({key:f.id,files:[f],metadata:cleanMetadata({title:f.name.replace(/\.[^.]+$/,'')}),cover:books.length===1?cover:null}));
 for(const g of groups){const bookId='b_'+(await hash('drive:'+g.key)).slice(0,32),m=g.metadata,time=now();await env.DB.prepare(`INSERT INTO books_catalogue(id,source,source_group,title,authors_json,series,series_index,description,language,tags_json,identifiers_json,imported_rating,metadata_json,updated_at,created_at) VALUES(?,'drive',?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(source_group) DO UPDATE SET title=excluded.title,authors_json=excluded.authors_json,series=excluded.series,series_index=excluded.series_index,description=excluded.description,language=excluded.language,tags_json=excluded.tags_json,identifiers_json=excluded.identifiers_json,imported_rating=excluded.imported_rating,metadata_json=excluded.metadata_json,updated_at=excluded.updated_at,unavailable=0`).bind(bookId,'drive:'+g.key,m.title,JSON.stringify(m.authors),m.series,m.seriesIndex,m.description,m.language,JSON.stringify(m.tags),JSON.stringify(m.identifiers),m.importedRating,JSON.stringify(m),time,time).run();for(const f of g.files)await upsertFile(env,bookId,f,parent,formatFor(f.name));if(g.cover){const format=g.cover.name.split('.').pop().toLowerCase().replace('jpeg','jpg');const coverId=await upsertFile(env,bookId,g.cover,parent,format);await env.DB.prepare('UPDATE books_catalogue SET cover_file_id=? WHERE id=?').bind(coverId,bookId).run();}}
 return groups.length;
}
async function upsertFile(env,bookId,f,parent,format){const id='f_'+(await hash('drive:'+f.id)).slice(0,32),version=plain(f.md5Checksum||`${f.modifiedTime||'unknown'}:${f.size||0}`,200);await env.DB.prepare(`INSERT INTO books_files(id,book_id,provider,source_id,parent_id,name,mime,format,version,size,modified_at) VALUES(?,?,'drive',?,?,?,?,?,?,?,?) ON CONFLICT(source_id) DO UPDATE SET book_id=excluded.book_id,parent_id=excluded.parent_id,name=excluded.name,mime=excluded.mime,format=excluded.format,version=excluded.version,size=excluded.size,modified_at=excluded.modified_at,available=1`).bind(id,bookId,f.id,parent,plain(f.name,500),mimeFor(format),format,version,Number(f.size)||0,f.modifiedTime||now()).run();return id;}
