import {plain,fail,safePath} from './util.mjs';
const decode=s=>String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&#(x[\da-f]+|\d+);/gi,(_,v)=>{const n=v[0].toLowerCase()==='x'?parseInt(v.slice(1),16):Number(v);return n>0&&n<=0x10ffff?String.fromCodePoint(n):'';}).replace(/&(amp|lt|gt|quot|apos);/g,(_,n)=>({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"})[n]);
const text=s=>plain(decode(s).replace(/<[^>]*>/g,' '),20000).replace(/\s+/g,' ');
const attrs=s=>Object.fromEntries([...String(s).matchAll(/([\w:.-]+)\s*=\s*(["'])([\s\S]*?)\2/g)].map(m=>[m[1],decode(m[3])]));
export function cleanMetadata(value={}){const v=value&&typeof value==='object'?value:{};const list=(x,max=30)=>Array.isArray(x)?[...new Set(x.map(z=>plain(z,200)).filter(Boolean))].slice(0,max):[];const num=x=>typeof x==='number'&&Number.isFinite(x)?x:null;return {title:plain(v.title,500)||'Untitled book',authors:list(v.authors),series:plain(v.series,300),seriesIndex:num(v.seriesIndex),description:text(v.description).slice(0,12000),language:plain(v.language,32),tags:list(v.tags,80),identifiers:Object.fromEntries(Object.entries(v.identifiers&&typeof v.identifiers==='object'?v.identifiers:{}).slice(0,30).map(([k,x])=>[plain(k,60),plain(x,300)])),importedRating:num(v.importedRating)!==null?Math.max(0,Math.min(5,v.importedRating)):null};}
export function parseCalibreOpf(xml){if(typeof xml!=='string'||xml.length>1048576)fail(413,'The metadata file is too large.');if(/<!\s*(?:DOCTYPE|ENTITY)/i.test(xml))fail(400,'DTD and entity declarations are not accepted.');const fields=name=>[...xml.matchAll(new RegExp(`<(?:(?:[\\w-]+):)?${name}\\b[^>]*>([\\s\\S]*?)<\\/(?:(?:[\\w-]+):)?${name}\\s*>`,'gi'))].map(m=>text(m[1]));const meta={};for(const m of xml.matchAll(/<meta\b([^>]*)\/?\s*>/gi)){const a=attrs(m[1]);if(a.name)meta[a.name]=a.content;}
 const identifiers={};for(const m of xml.matchAll(/<(?:[\w-]+:)?identifier\b([^>]*)>([\s\S]*?)<\/(?:[\w-]+:)?identifier\s*>/gi)){const a=attrs(m[1]);identifiers[a['opf:scheme']||a.scheme||a.id||'identifier']=text(m[2]);}
 return cleanMetadata({title:fields('title')[0],authors:fields('creator'),description:fields('description')[0],language:fields('language')[0],tags:fields('subject'),identifiers,series:meta['calibre:series'],seriesIndex:meta['calibre:series_index']?Number(meta['calibre:series_index']):null,importedRating:meta['calibre:rating']?Number(meta['calibre:rating'])/2:null});}
export function formatFor(name){return ({epub:'epub',pdf:'pdf',mobi:'mobi',azw:'azw',azw3:'azw3',cbz:'cbz'})[String(name).split('.').pop().toLowerCase()]||null;}
export const mimeFor=format=>({epub:'application/epub+zip',pdf:'application/pdf',mobi:'application/x-mobipocket-ebook',azw:'application/octet-stream',azw3:'application/octet-stream',cbz:'application/zip',jpg:'image/jpeg',png:'image/png',webp:'image/webp'})[format]||'application/octet-stream';
// Inspect ZIP directory before attempting decompression. ZIP64/encrypted archives are intentionally rejected.
export function inspectZip(bytes){const data=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);const dv=new DataView(data.buffer,data.byteOffset,data.byteLength);let end=-1;for(let i=data.length-22;i>=Math.max(0,data.length-65557);i--){if(dv.getUint32(i,true)===0x06054b50){end=i;break;}}if(end<0)fail(400,'This EPUB is not a valid ZIP archive.');const entries=dv.getUint16(end+10,true),size=dv.getUint32(end+12,true),start=dv.getUint32(end+16,true);if(dv.getUint16(end+4,true)!==0||entries>10000||start+size>end||entries===65535)fail(400,'This EPUB archive layout is not supported.');let pos=start,total=0;const names=[];const seen=new Set();for(let n=0;n<entries;n++){if(pos+46>data.length||dv.getUint32(pos,true)!==0x02014b50)fail(400,'This EPUB directory is damaged.');const flags=dv.getUint16(pos+8,true),method=dv.getUint16(pos+10,true),compressed=dv.getUint32(pos+20,true),unpacked=dv.getUint32(pos+24,true),nl=dv.getUint16(pos+28,true),el=dv.getUint16(pos+30,true),cl=dv.getUint16(pos+32,true);if(pos+46+nl+el+cl>start+size)fail(400,'This EPUB directory is damaged.');const name=new TextDecoder().decode(data.subarray(pos+46,pos+46+nl));if(!safePath(name)||seen.has(name)||flags&1||![0,8].includes(method)||unpacked>32*1024*1024||unpacked>Math.max(1,compressed)*400)fail(400,'This EPUB contains unsafe or unsupported entries.');seen.add(name);total+=unpacked;if(total>96*1024*1024)fail(413,'The expanded EPUB is too large.');names.push(name);pos+=46+nl+el+cl;}if(!seen.has('META-INF/container.xml'))fail(400,'This archive has no EPUB container.');return {entries,total,names};}
