export const BOOKS_BUILD='books-0.2.1';
export const MAX_FILE_BYTES=32*1024*1024;
export class BooksError extends Error {constructor(status,message,code='books_error',details){super(message);this.status=status;this.code=code;this.details=details;}}
export const fail=(status,message,code,details)=>{throw new BooksError(status,message,code,details);};
export const now=()=>new Date().toISOString();
export const uid=(prefix='')=>prefix+crypto.randomUUID();
export const plain=(value,max=500)=>String(value??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').trim().slice(0,max);
export function privateHeaders(type='application/json; charset=utf-8'){return {'content-type':type,'cache-control':'private, no-store','vary':'Cookie','x-content-type-options':'nosniff','referrer-policy':'no-referrer'};}
export const json=(body,status=200,extra={})=>new Response(JSON.stringify(body),{status,headers:{...privateHeaders(),...extra}});
export function sameOrigin(request){const url=new URL(request.url);if(!['GET','HEAD','OPTIONS'].includes(request.method)&&request.headers.get('origin')!==url.origin)fail(403,'This action must be made from Duck & Bear.','bad_origin');}
export async function boundedBytes(input,limit=65536){const length=Number(input.headers?.get('content-length')||0);if(length>limit)fail(413,'That file or request is too large.','too_large');const reader=input.body?.getReader();if(!reader)return new Uint8Array();const chunks=[];let size=0;try {for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit){await reader.cancel();fail(413,'That file or request is too large.','too_large');}chunks.push(value);}}finally{reader.releaseLock();}const bytes=new Uint8Array(size);let at=0;for(const p of chunks){bytes.set(p,at);at+=p.byteLength;}return bytes;}
export async function body(request,limit=65536){try {const value=JSON.parse(new TextDecoder().decode(await boundedBytes(request,limit)));if(!value||Array.isArray(value)||typeof value!=='object')fail(400,'The request must contain an object.','bad_json');return value;}catch(e){if(e instanceof BooksError)throw e;fail(400,'The request was not valid JSON.','bad_json');}}
export const base64url=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
export function unbase64url(value){if(!/^[\w-]+$/.test(value||''))throw new Error('Invalid encoding');const s=atob(value.replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(s,c=>c.charCodeAt(0));}
export const randomToken=()=>base64url(crypto.getRandomValues(new Uint8Array(32)));
export async function hash(value){const bytes=typeof value==='string'?new TextEncoder().encode(value):value;return base64url(await crypto.subtle.digest('SHA-256',bytes));}
async function encryptionKey(env){const secret=env.BOOKS_TOKEN_ENCRYPTION_KEY||env.GOOGLE_DRIVE_CLIENT_SECRET;if(typeof secret!=='string'||secret.length<20)fail(503,'The Google connection secret has not been configured.','missing_secret');const raw=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),'HKDF',false,['deriveKey']);return crypto.subtle.deriveKey({name:'HKDF',hash:'SHA-256',salt:new TextEncoder().encode('DuckBearBooks-v1'),info:new TextEncoder().encode('google-token-storage')},raw,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function seal(env,value){const iv=crypto.getRandomValues(new Uint8Array(12));const text=new TextEncoder().encode(JSON.stringify(value));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode('books-v1')},await encryptionKey(env),text);return 'v1.'+base64url(iv)+'.'+base64url(cipher);}
export async function unseal(env,encoded){const [version,iv,cipher]=String(encoded||'').split('.');if(version!=='v1'||!iv||!cipher)throw new Error('Unknown token encoding');const text=await crypto.subtle.decrypt({name:'AES-GCM',iv:unbase64url(iv),additionalData:new TextEncoder().encode('books-v1')},await encryptionKey(env),unbase64url(cipher));return JSON.parse(new TextDecoder().decode(text));}
export function folderId(value){let id=plain(value,500);if(id.startsWith('http')){let u;try{u=new URL(id);}catch{fail(400,'Use a Google Drive folder link.');}if(u.protocol!=='https:'||u.hostname!=='drive.google.com'||u.username||u.password)fail(400,'Use a Google Drive folder link.');const match=u.pathname.match(/^\/drive\/(?:u\/\d+\/)?folders\/([\w-]+)\/?$/);if(!match)fail(400,'That link is not a Google Drive folder.');id=match[1];}if(!/^[A-Za-z0-9_-]{10,200}$/.test(id))fail(400,'That Google Drive folder ID is not valid.');return id;}
export function safePath(path){if(typeof path!=='string'||path.length>2000||/^[a-z]+:/i.test(path)||path.startsWith('/')||path.includes('\\')||/[\u0000-\u001f]/.test(path))return false;try{const p=decodeURIComponent(path);return !p.split('/').some(x=>x==='..')&&!p.startsWith('/')&&!p.includes('\\');}catch{return false;}}
export function validateLocator(v){if(!v||typeof v!=='object')fail(400,'A reading position is required.');if(v.type==='epub'){if(!safePath(v.href)||!v.href||!Number.isInteger(v.offset)||v.offset<0||v.offset>100000000)fail(400,'That EPUB position is not valid.');if(v.cfi!==undefined&&(typeof v.cfi!=='string'||v.cfi.length>2048||!/^epubcfi\([\x20-\x7E]+\)$/.test(v.cfi)||/[<>\"']/.test(v.cfi)))fail(400,'That EPUB fragment is not valid.');return {type:'epub',href:v.href,offset:v.offset,...(v.cfi?{cfi:v.cfi}:{})};}if(v.type==='pdf'&&Number.isInteger(v.page)&&v.page>=1&&v.page<=100000)return {type:'pdf',page:v.page};fail(400,'That reading position is not valid.');}
export function byteRange(value,size){if(!value)return null;const match=String(value).match(/^bytes=(\d*)-(\d*)$/);if(!match||(!match[1]&&!match[2])||!Number.isSafeInteger(size)||size<=0)fail(416,'That byte range is not available.','bad_range');let start,end;if(!match[1]){const suffix=Number(match[2]);if(!Number.isSafeInteger(suffix)||suffix<=0)fail(416,'That byte range is not available.');start=Math.max(0,size-suffix);end=size-1;}else{start=Number(match[1]);end=match[2]?Math.min(Number(match[2]),size-1):size-1;}if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||end<start||start>=size)fail(416,'That byte range is not available.','bad_range');return {start,end};}
export function downloadDisposition(name){const fallback=plain(name,180).replace(/[^\w. -]/g,'_').replace(/"/g,'_')||'book';return `attachment; filename="${fallback}"; filename*=UTF-8''${encodeURIComponent(plain(name,180)).replace(/['()*]/g,c=>'%'+c.charCodeAt(0).toString(16).toUpperCase())}`;}
export function cookieValue(request,name){for(const part of (request.headers.get('cookie')||'').split(';')){const at=part.indexOf('=');if(part.slice(0,at).trim()===name)return part.slice(at+1).trim();}return '';}
export async function query(DB,sql,...values){return (await DB.prepare(sql).bind(...values).all()).results||[];}
