import test from 'node:test';import assert from 'node:assert/strict';
import {environment} from './fixtures.mjs';import {query} from '../../src/books/util.mjs';
let state={},handler={};try{state=await import('../../src/books/state.mjs');}catch{}try{handler=await import('../../src/books/handler.mjs');}catch{}
const need=(m,k)=>{assert.equal(typeof m[k],'function',`${k} must be implemented`);return m[k];};
const USERS={zachary:{id:'zachary',display_name:'Zachary',session_id:'session-a'},guannan:{id:'guannan',display_name:'Guannan',session_id:'session-b'},outsider:{id:'outsider',display_name:'Other'}};
export async function seeded(){const {env}=await environment();await env.DB.prepare("INSERT INTO books_catalogue(id,source,source_group,title,authors_json,updated_at,created_at) VALUES('book_test','upload','test','Sea and Sky','[\"Test Author\"]','2026-01-01','2026-01-01')").run();await env.DB.prepare("INSERT INTO books_files(id,book_id,provider,name,mime,format,version,size,object_key,modified_at) VALUES('file_test','book_test','upload','Sea and Sky.pdf','application/pdf','pdf','v1',10,'books/test-file','2026-01-01')").run();await env.MEDIA.put('books/test-file',new TextEncoder().encode('%PDF-TEST!'));return env;}
const progress=(overrides={})=>({version:'v1',revision:0,locator:{type:'pdf',page:2},progress:0.2,deviceId:'device_test_001',opId:crypto.randomUUID(),...overrides});
test('progress is private per user and file version',async()=>{const env=await seeded();const a=await need(state,'saveProgress')(env,USERS.zachary,'file_test',progress());assert.equal(a.revision,1);assert.equal((await need(state,'readProgress')(env,USERS.guannan,'file_test','v1')).revision,0);await assert.rejects(()=>state.saveProgress(env,USERS.zachary,'file_test',progress({version:'v2'})),/version/i);env.DB.close();});
test('progress retries are idempotent and altered duplicate operations are rejected',async()=>{const env=await seeded();const input=progress();const a=await need(state,'saveProgress')(env,USERS.zachary,'file_test',input);const b=await state.saveProgress(env,USERS.zachary,'file_test',input);assert.equal(a.revision,b.revision);await assert.rejects(()=>state.saveProgress(env,USERS.zachary,'file_test',{...input,progress:0.9}));assert.equal((await query(env.DB,'SELECT * FROM books_read_state')).length,1);env.DB.close();});
test('stale offline device cannot silently overwrite newer progress',async()=>{const env=await seeded();await need(state,'saveProgress')(env,USERS.zachary,'file_test',progress());await assert.rejects(()=>state.saveProgress(env,USERS.zachary,'file_test',progress({deviceId:'device-other-002',progress:0.8})),e=>e.status===409&&e.details.current.revision===1);assert.equal((await state.readProgress(env,USERS.zachary,'file_test','v1')).progress,0.2);env.DB.close();});
test('rereading preserves furthest-read progress while last position can move back',async()=>{const env=await seeded();await need(state,'saveProgress')(env,USERS.zachary,'file_test',progress({progress:0.8}));const b=await state.saveProgress(env,USERS.zachary,'file_test',progress({revision:1,progress:0.3}));assert.equal(b.progress,0.3);assert.equal(b.furthest,0.8);env.DB.close();});
test('annotations remain private and retain deletion tombstones',async()=>{const env=await seeded();const id=crypto.randomUUID(),b={fileId:'file_test',version:'v1',kind:'bookmark',locator:{type:'pdf',page:3},note:'Private note',revision:0};await need(state,'saveAnnotation')(env,USERS.zachary,id,b);assert.equal((await need(state,'listAnnotations')(env,USERS.guannan,'file_test','v1')).length,0);await assert.rejects(()=>state.saveAnnotation(env,USERS.zachary,id,{...b,note:'stale'}),e=>e.status===409);await state.saveAnnotation(env,USERS.zachary,id,{...b,revision:1,deleted:true});assert.equal((await state.listAnnotations(env,USERS.zachary,'file_test','v1')).length,0);assert.equal((await env.DB.prepare('SELECT deleted FROM books_annotations').first()).deleted,1);env.DB.close();});
export function testHandler(){return need(handler,'createBooksHandler')({fetch:async r=>new Response('untouched:'+new URL(r.url).pathname)}, {authenticate:async r=>USERS[r.headers.get('x-test-user')]||null,requirePair:async(_e,u)=>{if(!['zachary','guannan'].includes(u.id))throw Object.assign(new Error('Private household only'),{status:403});},requireOwner:async(_e,u)=>{if(u.id!=='zachary')throw Object.assign(new Error('Administrator only'),{status:403});},readerIds:async()=>['zachary','guannan'],isOwner:async(_e,u)=>u.id==='zachary'});}
const req=(path,user='zachary',method='GET',b,origin='https://guannan.party')=>new Request('https://guannan.party'+path,{method,headers:{...(user?{'x-test-user':user}:{}),...(method!=='GET'?{origin,'content-type':'application/json'}:{})},body:b===undefined?undefined:JSON.stringify(b)});
test('disabled module and unrelated routes fall through without touching the database',async()=>{const app=testHandler();assert.equal(await(await app.fetch(req('/our-space/'),{BOOKS_ENABLED:'true'},{})).text(),'untouched:/our-space/');const r=await app.fetch(req('/api/hq/books/catalogue'),{BOOKS_ENABLED:'false'},{});assert.equal(r.status,404);});
test('anonymous and non-household users cannot read books',async()=>{const env=await seeded(),app=testHandler();assert.equal((await app.fetch(req('/api/hq/books/catalogue',null),env,{})).status,401);assert.equal((await app.fetch(req('/api/hq/books/catalogue','outsider'),env,{})).status,403);env.DB.close();});
test('Google connection settings are administrator-only and CSRF protected',async()=>{const env=await seeded(),app=testHandler();assert.equal((await app.fetch(req('/api/hq/integrations/google-drive/status','guannan'),env,{})).status,403);assert.equal((await app.fetch(req('/api/hq/integrations/google-drive/start','zachary','POST',{},'https://evil.test'),env,{})).status,403);env.DB.close();});
test('catalogue exposes no storage keys, Drive IDs or connection tokens',async()=>{const env=await seeded(),app=testHandler();const r=await app.fetch(req('/api/hq/books/catalogue'),env,{});assert.equal(r.status,200);const d=await r.json();assert.equal(d.books[0].title,'Sea and Sky');assert.ok(!JSON.stringify(d).includes('books/test-file'));assert.ok(!JSON.stringify(d).includes('token_cipher'));env.DB.close();});
test('authorised download supports range requests and useful filenames',async()=>{const env=await seeded(),app=testHandler();const r=await app.fetch(new Request('https://guannan.party/api/hq/books/files/file_test/content?download=1',{headers:{'x-test-user':'zachary',range:'bytes=0-3'}}),env,{});assert.equal(r.status,206);assert.equal(await r.text(),'%PDF');assert.match(r.headers.get('content-disposition'),/Sea and Sky.pdf/);assert.equal(r.headers.get('cache-control'),'private, no-store');env.DB.close();});
test('shelves and ratings do not change the other reader’s library choices',async()=>{const env=await seeded(),app=testHandler();const put=await app.fetch(req('/api/hq/books/book_test/user','zachary','PUT',{status:'reading',favourite:true,rating:5}),env,{});assert.equal(put.status,200);const a=await(await app.fetch(req('/api/hq/books/book_test','zachary'),env,{})).json();const b=await(await app.fetch(req('/api/hq/books/book_test','guannan'),env,{})).json();assert.equal(a.book.favourite,true);assert.equal(b.book.favourite,false);env.DB.close();});
