import test from 'node:test';
import assert from 'node:assert/strict';
import {environment,connectedEnv,ROOT} from './fixtures.mjs';
import {testHandler} from './api.test.mjs';
import {readZip} from '../../public/hq/zip.mjs';
import {query,hash} from '../../src/books/util.mjs';
import {saveProgress,saveAnnotation} from '../../src/books/state.mjs';
let backup={};try{backup=await import('../../src/books/backup.mjs');}catch{}
const need=name=>{assert.equal(typeof backup[name],'function',`${name} must be implemented`);return backup[name];};
const user={id:'zachary'},partner={id:'guannan'};
const hooks={requireOwner:async(_e,u)=>{if(u.id!=='zachary')throw Object.assign(new Error('Owner only'),{status:403});},readerIds:async()=>['zachary','guannan']};
const request=(path,method='GET',data,who='zachary')=>new Request('https://guannan.party/api/hq/books'+path,{method,headers:{'x-test-user':who,origin:'https://guannan.party','content-type':'application/json'},...(data!==undefined?{body:JSON.stringify(data)}:{})});
async function sample(){const {env}=await environment();const app=testHandler();const bytes=new TextEncoder().encode('%PDF-1.7\nTest publication.\n%%EOF');const r=await app.fetch(new Request('https://guannan.party/api/hq/books/uploads?name=Sample.pdf',{method:'PUT',headers:{'x-test-user':'zachary',origin:'https://guannan.party'},body:bytes}),env,{});assert.equal(r.status,201);const book=(await r.json()).book,file=book.files[0];await saveProgress(env,user,file.id,{version:file.version,revision:0,locator:{type:'pdf',page:3},progress:0.4,deviceId:'test-device-one',opId:crypto.randomUUID()});await saveAnnotation(env,partner,'partner_note',{fileId:file.id,version:file.version,revision:0,locator:{type:'pdf',page:2},kind:'note',note:'Partner private note'});await env.DB.prepare('INSERT INTO books_preferences VALUES(?,?,?)').bind('zachary',JSON.stringify({theme:'sepia',fontSize:23}),'2026-01-01').run();await env.DB.prepare('INSERT INTO books_shelves VALUES(?,?,?,?)').bind('s_test','guannan','Favourites','2026-01-01').run();await env.DB.prepare('INSERT INTO books_shelf_items VALUES(?,?)').bind('s_test',book.id).run();return {env,book,file,bytes};}
async function archive(env){const response=await need('exportBooksBackup')(env,user,hooks);assert.equal(response.status,200);assert.match(response.headers.get('cache-control'),/private.*no-store/);const entries=readZip(await response.arrayBuffer());return {entries,manifest:JSON.parse(new TextDecoder().decode(entries.get('manifest.json')))};}
async function preview(env,manifest){return need('previewBooksRestore')(env,user,hooks,manifest);}
async function stage(env,job,entries,manifest){for(const file of manifest.objects){await need('stageBooksRestoreFile')(env,user,job.jobId,file.fileId,new Request('https://guannan.party',{method:'PUT',body:entries.get(file.path)}));}}
test('Books backup restores upload bytes, catalogue, separate reader notes and preferences without any Google token',async()=>{const src=await sample();const {env:target}=await environment();try{const {entries,manifest}=await archive(src.env);assert.equal(manifest.format,'duck-bear-books');assert.equal(manifest.driveOriginalsIncluded,false);assert.equal(manifest.objects.length,1);assert.equal(JSON.stringify(manifest).includes('token_cipher'),false);const job=await preview(target,manifest);assert.equal(job.canRestore,true);await stage(target,job,entries,manifest);const result=await need('applyBooksRestore')(target,user,hooks,job.jobId,{confirm:'RESTORE BOOKS'});assert.equal(result.restored,true);const files=await query(target.DB,'SELECT * FROM books_files');assert.deepEqual(new Uint8Array(await(await target.MEDIA.get(files[0].object_key)).arrayBuffer()),src.bytes);assert.equal((await query(target.DB,"SELECT * FROM books_read_state WHERE user_id='guannan'")).length,0);assert.equal((await query(target.DB,"SELECT note FROM books_annotations WHERE user_id='guannan'"))[0].note,'Partner private note');assert.equal((await query(target.DB,'SELECT * FROM books_shelf_items')).length,1);assert.equal(JSON.parse((await query(target.DB,'SELECT data_json FROM books_preferences'))[0].data_json).fontSize,23);assert.equal((await query(target.DB,'SELECT * FROM books_connections')).length,0);await assert.rejects(()=>backup.applyBooksRestore(target,user,hooks,job.jobId,{confirm:'RESTORE BOOKS'}),e=>[400,409].includes(e.status));}finally{src.env.DB.close();target.DB.close();}});
test('Books restore refuses nonempty library and never changes existing progress',async()=>{const src=await sample();try{const {manifest}=await archive(src.env);const job=await preview(src.env,manifest);assert.equal(job.canRestore,false);const before=JSON.stringify(await query(src.env.DB,'SELECT * FROM books_read_state'));await assert.rejects(()=>need('applyBooksRestore')(src.env,user,hooks,job.jobId,{confirm:'RESTORE BOOKS'}));assert.equal(JSON.stringify(await query(src.env.DB,'SELECT * FROM books_read_state')),before);}finally{src.env.DB.close();}});
test('Books restore validates uploaded bytes and refuses missing files before writing catalogue',async()=>{const src=await sample(),{env:target}=await environment();try{const {manifest,entries}=await archive(src.env);const job=await preview(target,manifest);await assert.rejects(()=>need('stageBooksRestoreFile')(target,user,job.jobId,manifest.objects[0].fileId,new Request('https://guannan.party',{method:'PUT',body:'wrong bytes'})),e=>e.status===400);await assert.rejects(()=>need('applyBooksRestore')(target,user,hooks,job.jobId,{confirm:'RESTORE BOOKS'}),e=>e.status===400);assert.equal((await query(target.DB,'SELECT * FROM books_catalogue')).length,0);await stage(target,job,entries,manifest);}finally{src.env.DB.close();target.DB.close();}});
test('Books restore rejects invalid cross-links, MIME tricks, unknown readers and content locators',async()=>{const src=await sample(),{env:target}=await environment();try{const {manifest}=await archive(src.env);for(const alter of [m=>m.tables.books_files[0].book_id='missing',m=>m.tables.books_files[0].mime='text/html',m=>m.tables.books_annotations[0].user_id='stranger',m=>m.tables.books_read_state[0].locator_json='{"type":"epub","href":"javascript:alert(1)","offset":0}',m=>m.tables.books_files.push({...m.tables.books_files[0]}),m=>m.tables.books_connections=[{token_cipher:'stolen'}],m=>m.objects[0].path='../secrets']){const broken=structuredClone(manifest);alter(broken);await assert.rejects(()=>preview(target,broken),e=>e.status===400||e.status===403);}assert.equal((await query(target.DB,'SELECT * FROM books_catalogue')).length,0);}finally{src.env.DB.close();target.DB.close();}});
test('Books backup fails for missing or changed storage bytes instead of presenting a complete archive',async()=>{const src=await sample();try{const f=await src.env.DB.prepare('SELECT * FROM books_files').first();await src.env.MEDIA.delete(f.object_key);await assert.rejects(()=>need('exportBooksBackup')(src.env,user,hooks),e=>e.status===409);await src.env.MEDIA.put(f.object_key,new TextEncoder().encode('changed'));await assert.rejects(async()=>{const r=await backup.exportBooksBackup(src.env,user,hooks);await r.arrayBuffer();});}finally{src.env.DB.close();}});
test('Books restore checks empty state at apply time after preview, and does not touch other website tables',async()=>{const src=await sample(),{env:target}=await environment();try{await target.DB.exec("CREATE TABLE unrelated_notes(id TEXT); INSERT INTO unrelated_notes VALUES('keep');");const {manifest,entries}=await archive(src.env);const job=await preview(target,manifest);await stage(target,job,entries,manifest);await target.DB.prepare('INSERT INTO books_preferences VALUES(?,?,?)').bind('zachary','{}','2026-01-01').run();await assert.rejects(()=>need('applyBooksRestore')(target,user,hooks,job.jobId,{confirm:'RESTORE BOOKS'}),e=>e.status===409);assert.equal((await query(target.DB,'SELECT * FROM unrelated_notes'))[0].id,'keep');assert.equal((await query(target.DB,'SELECT * FROM books_catalogue')).length,0);}finally{src.env.DB.close();target.DB.close();}});
test('Books restore refuses expired jobs and unsafe confirmation',async()=>{const src=await sample(),{env:target}=await environment();try{const {manifest}=await archive(src.env);const job=await preview(target,manifest);await assert.rejects(()=>need('applyBooksRestore')(target,user,hooks,job.jobId,{confirm:'yes'}),e=>e.status===400);await target.DB.prepare('UPDATE books_restore_jobs SET expires_at=0 WHERE id=?').bind(job.jobId).run();await assert.rejects(()=>backup.applyBooksRestore(target,user,hooks,job.jobId,{confirm:'RESTORE BOOKS'}),e=>e.status===400);}finally{src.env.DB.close();target.DB.close();}});
test('Books backup and restore endpoints are owner-only, origin-protected and do not leak records on rejection',async()=>{const {env}=await environment(),app=testHandler();try{let r=await app.fetch(request('/backup','GET',undefined,'guannan'),env,{});assert.equal(r.status,403);r=await app.fetch(request('/restore/preview','POST',{},'guannan'),env,{});assert.equal(r.status,403);r=await app.fetch(new Request('https://guannan.party/api/hq/books/restore/preview',{method:'POST',headers:{'x-test-user':'zachary',origin:'https://elsewhere.test'},body:'{}'}),env,{});assert.equal(r.status,403);}finally{env.DB.close();}});
test('Books backup keeps Drive references and ancestry but never exports Google secrets',async()=>{const {env}=await connectedEnv(),{env:target}=await environment();try{const scan=await import('../../src/books/import.mjs');const job=await scan.startScan(env);for(let n=0;n<20;n++){if((await scan.stepScan(env,job.id)).status==='complete')break;}const {manifest,entries}=await archive(env);assert.equal(manifest.rootId,ROOT);assert.equal(manifest.objects.length,0);assert.ok(!JSON.stringify(manifest).includes('fixture-access'));const recovery=await preview(target,manifest);await need('applyBooksRestore')(target,user,hooks,recovery.jobId,{confirm:'RESTORE BOOKS'});assert.equal((await query(target.DB,'SELECT * FROM books_catalogue')).length,1);assert.equal((await query(target.DB,'SELECT * FROM books_connections')).length,0);}finally{env.DB.close();target.DB.close();}});
test('Books restore rechecks staged checksums, not only equal file lengths',async()=>{const src=await sample(),{env:target}=await environment();try{const {manifest,entries}=await archive(src.env);const job=await preview(target,manifest);await stage(target,job,entries,manifest);const file=await target.DB.prepare('SELECT object_key FROM books_restore_files').first();await target.MEDIA.put(file.object_key,new Uint8Array(src.bytes.length));await assert.rejects(()=>need('applyBooksRestore')(target,user,hooks,job.jobId,{confirm:'RESTORE BOOKS'}),e=>e.status===400);assert.equal((await query(target.DB,'SELECT * FROM books_catalogue')).length,0);}finally{src.env.DB.close();target.DB.close();}});
test('Books restore transaction rolls back earlier table writes when a later insert fails',async()=>{const src=await sample(),{env:target}=await environment();try{const {manifest,entries}=await archive(src.env);const job=await preview(target,manifest);await stage(target,job,entries,manifest);await target.DB.exec("CREATE TRIGGER deny_test_notes BEFORE INSERT ON books_annotations BEGIN SELECT RAISE(ABORT,'synthetic insert failure'); END;");await assert.rejects(()=>need('applyBooksRestore')(target,user,hooks,job.jobId,{confirm:'RESTORE BOOKS'}),e=>e.status===409);assert.equal((await query(target.DB,'SELECT * FROM books_catalogue')).length,0);assert.equal((await query(target.DB,'SELECT * FROM books_files')).length,0);assert.equal((await target.DB.prepare('SELECT used_at FROM books_restore_jobs').first()).used_at,null);}finally{src.env.DB.close();target.DB.close();}});
test('Books restore rejects prototype-named tables rather than ignoring them',async()=>{const src=await sample(),{env:target}=await environment();try{const {manifest}=await archive(src.env);manifest.tables.constructor=[];await assert.rejects(()=>preview(target,manifest),e=>e.status===400);}finally{src.env.DB.close();target.DB.close();}});
