import test from 'node:test';import assert from 'node:assert/strict';
import {makeD1,makeR2} from '../../tools/books/sqlite.mjs';import {ensureBooksSchema} from '../../src/books/schema.mjs';import {seal,query} from '../../src/books/util.mjs';
let google={},scan={};try{google=await import('../../src/books/google.mjs');}catch{}try{scan=await import('../../src/books/import.mjs');}catch{}
const need=(m,k)=>{assert.equal(typeof m[k],'function',`${k} must be implemented`);return m[k];};
import {ROOT,CAL,AUTHOR,BOOK,FILE,OPFXML,environment,connectedEnv} from './fixtures.mjs';

test('OAuth requests only drive.file by default and uses PKCE, offline access and state cookie',async()=>{const {env}=await environment();const r=await need(google,'beginOAuth')(new Request('https://guannan.party/api/hq/integrations/google-drive/start',{method:'POST'}),env,{id:'zachary'},{});const {authorizationUrl}=await r.json();const u=new URL(authorizationUrl);assert.equal(u.searchParams.get('scope'),'https://www.googleapis.com/auth/drive.file');assert.equal(u.searchParams.get('code_challenge_method'),'S256');assert.equal(u.searchParams.get('access_type'),'offline');assert.ok(r.headers.get('set-cookie').includes('HttpOnly'));assert.equal((await query(env.DB,'SELECT * FROM books_oauth_states')).length,1);env.DB.close();});
test('OAuth rejects unconfirmed broader scopes',async()=>{const {env}=await environment();await assert.rejects(()=>need(google,'beginOAuth')(new Request('https://guannan.party/x'),env,{id:'zachary'},{mode:'readonly'}),/confirm/i);env.DB.close();});
test('OAuth callback checks user and cookie before exchanging code, then rejects replay',async()=>{const {env,calls}=await environment();const start=await need(google,'beginOAuth')(new Request('https://guannan.party/x'),env,{id:'zachary'},{});const auth=new URL((await start.json()).authorizationUrl);const callback='https://guannan.party/api/hq/integrations/google-drive/callback?state='+auth.searchParams.get('state')+'&code=fixture-code';const cookie=start.headers.get('set-cookie').split(';')[0];await assert.rejects(()=>need(google,'finishOAuth')(new Request(callback,{headers:{cookie}}),env,{id:'other-user'}));assert.equal(calls.filter(x=>x.url.endsWith('/token')).length,0);
 const result=await google.finishOAuth(new Request(callback,{headers:{cookie}}),env,{id:'zachary'});assert.equal(result.status,303);assert.ok((await env.DB.prepare('SELECT token_cipher FROM books_connections').first()).token_cipher.startsWith('v1.'));await assert.rejects(()=>google.finishOAuth(new Request(callback,{headers:{cookie}}),env,{id:'zachary'}));env.DB.close();});
test('connection status never exposes client secrets or refresh/access tokens',async()=>{const {env}=await connectedEnv();const status=await need(google,'connectionStatus')(env);const s=JSON.stringify(status);assert.ok(!s.includes('fixture-access')&&!s.includes('fixture-refresh')&&!s.includes(env.GOOGLE_DRIVE_CLIENT_SECRET));assert.equal(status.connected,true);env.DB.close();});
test('nested import paginates, reads OPF, preserves files and skips shortcuts',async()=>{const {env,calls}=await connectedEnv();const start=await need(scan,'startScan')(env);for(let n=0;n<30;n++){const s=await need(scan,'stepScan')(env,start.id);if(['complete','empty','failed'].includes(s.status))break;}
 const jobs=await query(env.DB,'SELECT * FROM books_scan_jobs');assert.equal(jobs[0].status,'complete');const books=await query(env.DB,'SELECT * FROM books_catalogue');assert.equal(books.length,1);assert.equal(books[0].title,'Sea & Sky');assert.equal(books[0].series,'Seaside');assert.equal((await query(env.DB,"SELECT * FROM books_files WHERE format='epub'")).length,1);assert.ok(calls.every(x=>(x.method||'GET')==='GET'));assert.ok(calls.every(x=>!x.url.includes('outside_documents')));assert.ok(calls.some(x=>x.url.includes('pageToken=2')));env.DB.close();});
test('repeat import updates catalogue without duplicating files or erasing reader state',async()=>{const {env}=await connectedEnv();for(let pass=0;pass<2;pass++){const job=await need(scan,'startScan')(env);for(let n=0;n<30;n++){const s=await need(scan,'stepScan')(env,job.id);if(['complete','empty','failed'].includes(s.status))break;}}assert.equal((await query(env.DB,'SELECT * FROM books_catalogue')).length,1);assert.equal((await query(env.DB,"SELECT * FROM books_files WHERE format='epub'")).length,1);env.DB.close();});
test('file moved outside selected library is rejected before reading the other folder',async()=>{const {env,data,calls}=await connectedEnv();const job=await need(scan,'startScan')(env);for(let n=0;n<30;n++){const s=await need(scan,'stepScan')(env,job.id);if(s.status==='complete')break;}data.get(FILE).parents=['outside_documents'];const before=calls.length;await assert.rejects(()=>need(google,'verifyFileInLibrary')(env,FILE),/library/i);assert.ok(calls.slice(before).every(x=>!x.url.includes('/files/outside_documents')));env.DB.close();});

test('an OAuth callback cannot be transferred to a different session of the same owner',async()=>{const {env}=await environment();const user={id:'owner',session_id:'session-one'};const start=await google.beginOAuth(new Request('https://guannan.party/api/hq/integrations/google-drive/start'),env,user);const data=await start.json();const state=new URL(data.authorizationUrl).searchParams.get('state');const cookie=start.headers.get('set-cookie').split(';')[0];await assert.rejects(()=>google.finishOAuth(new Request('https://guannan.party/api/hq/integrations/google-drive/callback?code=test&state='+state,{headers:{cookie}}),env,{...user,session_id:'session-two'}),e=>e.status===400&&e.code==='invalid_state');env.DB.close();});
