import test from 'node:test';import assert from 'node:assert/strict';
import * as google from '../../src/books/google.mjs';
import {seal,unseal,query} from '../../src/books/util.mjs';
import {environment,connectedEnv,ROOT,FILE} from './fixtures.mjs';
const owner={id:'zachary',session_id:'session-current'};
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
async function encrypted(env,token='next-access'){return seal(env,{access_token:token,refresh_token:'next-refresh',expires_at:Date.now()+3600000});}
test('a delayed Google refresh cannot return usable credentials after disconnect',async()=>{const {env,fetcher}=await connectedEnv(),entered=deferred(),release=deferred();env.BOOKS_FETCH=async(u,i)=>{if(String(u).endsWith('/token')){entered.resolve();await release.promise;}return fetcher(u,i);};const pending=google.accessToken(env,true);await entered.promise;await google.disconnectGoogle(env);release.resolve();await assert.rejects(()=>pending,e=>e.status===409&&e.code==='connection_changed');assert.equal((await google.connectionStatus(env)).connected,false);env.DB.close();});
test('late token-server failure cannot mark a newly connected account revoked',async()=>{const {env,fetcher}=await connectedEnv(),entered=deferred(),release=deferred();env.BOOKS_FETCH=async(u,i)=>{if(String(u).endsWith('/token')){entered.resolve();await release.promise;return Response.json({error:'invalid_grant'},{status:400});}return fetcher(u,i);};const pending=google.accessToken(env,true);const handled=pending.catch(e=>e);await entered.promise;await env.DB.prepare("UPDATE books_connections SET token_cipher=?,last_error=NULL").bind(await encrypted(env)).run();release.resolve();await handled;assert.equal((await env.DB.prepare('SELECT last_error FROM books_connections').first()).last_error,null);env.DB.close();});
test('transient Google token failure is retryable, not reported as revoked permission',async()=>{const {env}=await connectedEnv();env.BOOKS_FETCH=async()=>Response.json({error:'temporarily_unavailable'},{status:503});await assert.rejects(()=>google.accessToken(env,true),e=>e.status===502&&e.code==='google_temporarily_unavailable');assert.notEqual((await google.connectionStatus(env)).lastError,'Reconnect Google Drive');env.DB.close();});
test('Google invalid_grant requires reconnection and does not expose token details',async()=>{const {env}=await connectedEnv();env.BOOKS_FETCH=async()=>Response.json({error:'invalid_grant',error_description:'secret-in-provider-message'},{status:400});await assert.rejects(()=>google.accessToken(env,true),e=>e.code==='reconnect_required'&&!e.message.includes('secret-in-provider'));env.DB.close();});
test('disconnect removes local access before remote revocation and preserves a subsequent connection',async()=>{const {env,fetcher}=await connectedEnv(),entered=deferred(),release=deferred();env.BOOKS_FETCH=async(u,i)=>{if(String(u).endsWith('/revoke')){entered.resolve();await release.promise;}return fetcher(u,i);};const pending=google.disconnectGoogle(env);await entered.promise;const disconnected=await google.connectionStatus(env);const next=await encrypted(env);await env.DB.prepare("UPDATE books_connections SET token_cipher=?").bind(next).run();release.resolve();await pending;assert.equal(disconnected.connected,false);assert.equal((await env.DB.prepare('SELECT token_cipher FROM books_connections').first()).token_cipher,next);env.DB.close();});
test('a consumed OAuth callback cannot reconnect after disconnect while waiting for Google',async()=>{const {env,fetcher}=await environment();const begin=await google.beginOAuth(new Request('https://guannan.party/x'),env,owner);const auth=new URL((await begin.json()).authorizationUrl);const callback=new Request('https://guannan.party/api/hq/integrations/google-drive/callback?state='+auth.searchParams.get('state')+'&code=fixture',{headers:{cookie:begin.headers.get('set-cookie').split(';')[0]}});const entered=deferred(),release=deferred();env.BOOKS_FETCH=async(u,i)=>{if(String(u).endsWith('/token')){entered.resolve();await release.promise;}return fetcher(u,i);};const pending=google.finishOAuth(callback,env,owner);await entered.promise;await google.disconnectGoogle(env);release.resolve();await assert.rejects(()=>pending,e=>e.status===409&&e.code==='connection_changed');assert.equal((await google.connectionStatus(env)).connected,false);env.DB.close();});
test('Google diagnostic forces refresh, verifies a nested file, and labels coverage as a sample',async()=>{const {env,calls}=await connectedEnv();assert.equal(typeof google.checkGoogleConnection,'function');const result=await google.checkGoogleConnection(new Request('https://guannan.party/x'),env);assert.equal(result.status,'sample_verified');assert.equal(result.fullLibraryVerified,false);assert.equal(result.sample.format,'epub');assert.ok(result.sample.bytesChecked>=4);assert.ok(calls.some(c=>c.url.endsWith('/token')));assert.ok(calls.every(c=>!c.url.includes('outside_documents')));assert.ok(!JSON.stringify(result).includes('fixture-refresh'));assert.equal(result.callback,'https://guannan.party/api/hq/integrations/google-drive/callback');env.DB.close();});
test('Google diagnostic reports missing setup and an empty visibility sample without fabricating success',async()=>{const {env,data}=await connectedEnv();assert.equal(typeof google.checkGoogleConnection,'function');delete env.GOOGLE_DRIVE_CLIENT_SECRET;let r=await google.checkGoogleConnection(new Request('https://guannan.party/x'),env);assert.equal(r.status,'setup_needed');env.GOOGLE_DRIVE_CLIENT_SECRET='test-only-secret-for-encryption-123456789';for(const [id]of data)if(id!==ROOT)data.delete(id);r=await google.checkGoogleConnection(new Request('https://guannan.party/x'),env);assert.equal(r.status,'no_visible_books');assert.equal(r.fullLibraryVerified,false);env.DB.close();});
