/** Authentication uses the existing users/sessions; recovery metadata is transactional D1. */
import {fail,json,body,text,integer,choice,token,sha,b64,unb64,now,id,queryAll,authenticate,safeUser,rate,sameOrigin} from './core.mjs';
import {initialise,schemaReady,requireOwner,permission} from './schema.mjs';
const DEFAULT_ORIGIN='https://duck-bear-hq.zachary-chambers2.workers.dev';
export function normalizeEmail(value){const e=text(value,254).toLowerCase();if(!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(e)||/[\r\n]/.test(e))fail(400,'Enter a valid email address.');return e;}
export function maskEmail(value){if(!value)return '';const [a,b]=value.split('@');return a.slice(0,1)+'***@'+b;}
function origin(env){try{const u=new URL(env.SITE_ORIGIN||DEFAULT_ORIGIN);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error();return u.origin;}catch{return DEFAULT_ORIGIN;}}
export async function passwordHash(password,saltValue=null,iterations=100000){const salt=saltValue?unb64(saltValue):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const hash=b64(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256));return {hash,salt:b64(salt),iterations};}
function newPassword(value){if(typeof value!=='string'||value.length<12||value.length>128)fail(400,'Use a password between 12 and 128 characters.');return value;}
function equals(a,b){if(a.length!==b.length)return false;let diff=0;for(let n=0;n<a.length;n++)diff|=a.charCodeAt(n)^b.charCodeAt(n);return diff===0;}
async function checkPassword(user,password){if(typeof password!=='string'||password.length>128)return false;const test=await passwordHash(password,user.password_salt,user.password_iterations);return equals(test.hash,user.password_hash);}
export async function reauthenticate(env,user,password){await rate(env,'reauth:'+user.id,8,600);if(!await checkPassword(user,password))fail(403,'Current password is incorrect.');}
const sessionCookie=(t,max=30*86400)=>`db_session=${t}; Path=/; Max-Age=${max}; HttpOnly; Secure; SameSite=Strict`;
export const mailReady=env=>Boolean(env.EMAIL?.send&&env.PASSWORD_RESET_FROM);
async function sendMail(env,to,subject,message){if(!mailReady(env))return false;try{await env.EMAIL.send({to,from:String(env.PASSWORD_RESET_FROM),subject,text:message});return true;}catch{return false;}}
async function createToken(env,user,kind,payload={},seconds=3600){const raw=token(),hashed=await sha(raw),expires=Date.now()+seconds*1000;await env.DB.prepare('INSERT INTO hq_tokens(token_hash,user_id,kind,payload,credential_tag,expires_at,created_at) VALUES(?,?,?,?,?,?,?)').bind(hashed,user.id,kind,JSON.stringify(payload),user.password_hash,expires,now()).run();return {raw,hashed,expires};}
async function tokenRow(env,raw,kind){if(typeof raw!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(raw))fail(400,'This link is invalid or has expired.');const row=await env.DB.prepare('SELECT t.*,u.password_hash,u.password_salt,u.password_iterations,u.active,u.username,u.display_name,u.role FROM hq_tokens t JOIN users u ON u.id=t.user_id WHERE t.token_hash=? AND t.kind=? AND t.used IS NULL AND t.expires_at>? AND t.credential_tag=u.password_hash').bind(await sha(raw),kind,Date.now()).first();if(!row||(kind==='invite'?row.active!==0:row.active!==1))fail(400,'This link is invalid or has expired.');return row;}
async function login(request,env){
 const b=await body(request),identifier=text(b.username||b.identifier,254,{required:true}).toLowerCase(),ready=await schemaReady(env),ip=request.headers.get('cf-connecting-ip')||'unknown';
 if(ready){await rate(env,'login-ip:'+ip,35,600);await rate(env,'login-id:'+identifier,10,600);}else{const count=await env.DB.prepare('SELECT COUNT(*) AS n FROM login_attempts WHERE success=0 AND created_at>? AND (lower(username)=? OR ip_hash=?)').bind(new Date(Date.now()-600000).toISOString(),identifier,await sha(ip)).first();if(count.n>=10)fail(429,'Too many attempts. Please try again later.');}
 let user=await env.DB.prepare('SELECT * FROM users WHERE lower(username)=? AND active=1').bind(identifier).first();
 if(!user&&identifier.includes('@')){if(ready){const identity=await env.DB.prepare('SELECT user_id FROM hq_identity WHERE email=?').bind(identifier).first();if(identity)user=await env.DB.prepare('SELECT * FROM users WHERE id=? AND active=1').bind(identity.user_id).first();}else{const object=await env.MEDIA.get('account-security/private-v1.json');if(object){let saved;try{saved=JSON.parse(await object.text());}catch{fail(503,'Account recovery data needs owner attention.');}const profile=saved.profiles?.find(p=>p.email_normalized===identifier);if(profile)user=await env.DB.prepare('SELECT * FROM users WHERE id=? AND active=1').bind(profile.user_id).first();}}}
 const ok=user?await checkPassword(user,b.password):Boolean(await passwordHash(String(b.password||'').slice(0,128),'AAAAAAAAAAAAAAAAAAAAAA').then(()=>false));
 await env.DB.prepare('INSERT INTO login_attempts(id,username,ip_hash,success,created_at) VALUES(?,?,?,?,?)').bind(id('attempt'),identifier,await sha(ip),ok?1:0,now()).run();
 if(!ok)fail(401,'Invalid username/email or password.');await initialise(env,user);
 const raw=token(),stamp=now(),sid=id('session');await env.DB.batch([env.DB.prepare('DELETE FROM sessions WHERE expires_at<?').bind(stamp),env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at,last_seen_at,user_agent,ip_hash) VALUES(?,?,?,?,?,?,?,?)').bind(sid,user.id,await sha(raw),new Date(Date.now()+30*86400000).toISOString(),stamp,stamp,text(request.headers.get('user-agent')||'',250),await sha(ip))]);
 return json({ok:true,user:safeUser(user)},200,{'set-cookie':sessionCookie(raw)});
}
async function requestRecovery(request,env){const b=await body(request),email=normalizeEmail(b.email);const generic={ok:true,message:'If this email belongs to an active account, its recovery request has been recorded.',emailConfigured:mailReady(env)};if(!await schemaReady(env))return json(generic);await rate(env,'reset-ip:'+(request.headers.get('cf-connecting-ip')||'unknown'),15,600);await rate(env,'reset-email:'+email,3,600);
 const user=await env.DB.prepare('SELECT u.*,i.verified FROM hq_identity i JOIN users u ON u.id=i.user_id WHERE i.email=? AND u.active=1').bind(email).first();if(!user)return json(generic);
 const existing=await env.DB.prepare("SELECT id FROM hq_recovery WHERE user_id=? AND status='pending'").bind(user.id).first();if(!existing)await env.DB.prepare('INSERT INTO hq_recovery(id,user_id,status,created_at) VALUES(?,?,?,?)').bind(id('recovery'),user.id,'pending',now()).run();
 if(user.verified&&mailReady(env)){const t=await createToken(env,user,'reset');const link=origin(env)+'/reset-password/#token='+t.raw;const sent=await sendMail(env,email,'Duck & Bear — reset your password',`A password reset was requested for Duck & Bear.\n\n${link}\n\nThe link can be used once within 60 minutes. Ignore this email if you did not request it.`);if(!sent)await env.DB.prepare('UPDATE hq_tokens SET used=? WHERE token_hash=?').bind('delivery-failed',t.hashed).run();}
 return json(generic);
}
async function consumePassword(request,env,kind){if(!await schemaReady(env))fail(400,'This link is invalid or has expired.');const b=await body(request),next=newPassword(b.newPassword);await rate(env,kind+'-ip:'+(request.headers.get('cf-connecting-ip')||'unknown'),12,600);const r=await tokenRow(env,b.token,kind),h=await passwordHash(next),nonce=id('used'),stamp=now();const payload=JSON.parse(r.payload);
 const consume=env.DB.prepare('UPDATE hq_tokens SET used=? WHERE token_hash=? AND used IS NULL AND expires_at>? AND credential_tag=(SELECT password_hash FROM users WHERE id=hq_tokens.user_id)').bind(nonce,r.token_hash,Date.now());
 const steps=[consume,env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,password_iterations=?,active=1,updated_at=? WHERE id=? AND EXISTS(SELECT 1 FROM hq_tokens WHERE token_hash=? AND used=?)').bind(h.hash,h.salt,h.iterations,stamp,r.user_id,r.token_hash,nonce),env.DB.prepare('DELETE FROM sessions WHERE user_id=? AND EXISTS(SELECT 1 FROM hq_tokens WHERE token_hash=? AND used=?)').bind(r.user_id,r.token_hash,nonce),env.DB.prepare("UPDATE hq_recovery SET status='resolved' WHERE user_id=? AND EXISTS(SELECT 1 FROM hq_tokens WHERE token_hash=? AND used=?)").bind(r.user_id,r.token_hash,nonce),env.DB.prepare('UPDATE hq_tokens SET used=? WHERE user_id=? AND used IS NULL AND EXISTS(SELECT 1 FROM hq_tokens WHERE token_hash=? AND used=?)').bind('revoked-'+nonce,r.user_id,r.token_hash,nonce)];
 if(kind==='invite'&&payload.emailSent)steps.push(env.DB.prepare('UPDATE hq_identity SET verified=1,updated_at=? WHERE user_id=? AND EXISTS(SELECT 1 FROM hq_tokens WHERE token_hash=? AND used=?)').bind(stamp,r.user_id,r.token_hash,nonce));
 const result=await env.DB.batch(steps);if(!result[0].meta.changes)fail(400,'This link has already been used.');return json({ok:true,message:kind==='invite'?'Account activated. Sign in with your new password.':'Password reset. Sign in again on each device.'},200,{'set-cookie':sessionCookie('',0)});
}
async function verifyEmail(request,env){if(!await schemaReady(env))fail(400,'This link is invalid or has expired.');const b=await body(request);await rate(env,'verify-ip:'+(request.headers.get('cf-connecting-ip')||'unknown'),20,600);const r=await tokenRow(env,b.token,'verify');const email=normalizeEmail(JSON.parse(r.payload).email);const identity=await env.DB.prepare('SELECT pending_email,email FROM hq_identity WHERE user_id=?').bind(r.user_id).first();if(identity?.pending_email!==email)fail(400,'This email request was replaced. Use the newest link.');const nonce=id('verified');let out;try{out=await env.DB.batch([env.DB.prepare('UPDATE hq_tokens SET used=? WHERE token_hash=? AND used IS NULL AND expires_at>? AND credential_tag=(SELECT password_hash FROM users WHERE id=hq_tokens.user_id)').bind(nonce,r.token_hash,Date.now()),env.DB.prepare('UPDATE hq_identity SET email=?,verified=1,pending_email=NULL,updated_at=? WHERE user_id=? AND pending_email=? AND EXISTS(SELECT 1 FROM hq_tokens WHERE token_hash=? AND used=?)').bind(email,now(),r.user_id,email,r.token_hash,nonce)]);}catch(e){if(/UNIQUE/i.test(String(e)))fail(409,'That email is already registered.');throw e;}if(!out[0].meta.changes||!out[1].meta.changes)fail(400,'This link has already been used.');return json({ok:true,message:'Email address verified.'});}
export async function publicAuth(request,env,url){const path=url.pathname;
 if(path==='/api/hq/auth/status'&&request.method==='GET')return json({emailConfigured:mailReady(env),registration:'invite-only'});
 const mapping={'/api/auth/login':'login','/api/auth/recovery/request':'recovery','/api/auth/recovery/reset':'reset','/api/hq/auth/verify':'verify','/api/hq/auth/accept':'invite'};
 const action=mapping[path];if(!action)return null;if(request.method!=='POST')fail(405,'Use POST.');sameOrigin(request);
 if(action==='login')return login(request,env);if(action==='recovery')return requestRecovery(request,env);if(action==='verify')return verifyEmail(request,env);return consumePassword(request,env,action);
}
export async function saveEmail(request,env,user){const b=await body(request),email=normalizeEmail(b.email);await reauthenticate(env,user,b.currentPassword);const existing=await env.DB.prepare('SELECT * FROM hq_identity WHERE user_id=?').bind(user.id).first();const occupied=await env.DB.prepare('SELECT user_id FROM hq_identity WHERE email=? AND user_id<>?').bind(email,user.id).first();if(occupied)fail(409,'That email is already registered to another account.');const stamp=now();
 await env.DB.batch([env.DB.prepare('INSERT INTO hq_identity(user_id,email,verified,pending_email,updated_at) VALUES(?,?,0,?,?) ON CONFLICT(user_id) DO UPDATE SET pending_email=excluded.pending_email,updated_at=excluded.updated_at').bind(user.id,existing?.email||email,email,stamp),env.DB.prepare("UPDATE hq_tokens SET used='email-changed' WHERE user_id=? AND used IS NULL").bind(user.id)]);
 let delivery='unconfigured';if(mailReady(env)){const t=await createToken(env,user,'verify',{email});const sent=await sendMail(env,email,'Duck & Bear — verify your email',`Confirm your email address for Duck & Bear.\n\n${origin(env)}/verify-email/#token=${t.raw}\n\nThis link expires in 60 minutes. Ignore it if you did not request the change.`);delivery=sent?'sent':'failed';if(!sent)await env.DB.prepare("UPDATE hq_tokens SET used='delivery-failed' WHERE token_hash=?").bind(t.hashed).run();}
 const saved=await env.DB.prepare('SELECT email,verified,pending_email FROM hq_identity WHERE user_id=?').bind(user.id).first();return json({ok:true,email:saved,delivery,accountSecurity:{email:saved.email||'',emailRegistered:Boolean(saved.email)},message:delivery==='sent'?'Check the new address for its verification link.':'Email saved, but email delivery is not configured or failed. Owner-assisted recovery remains available.'});}
export async function changePassword(request,env,user){const b=await body(request),next=newPassword(b.newPassword);await reauthenticate(env,user,b.currentPassword);const h=await passwordHash(next),stamp=now();const out=await env.DB.batch([env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,password_iterations=?,updated_at=? WHERE id=? AND password_hash=?').bind(h.hash,h.salt,h.iterations,stamp,user.id,user.password_hash),env.DB.prepare('DELETE FROM sessions WHERE user_id=? AND id<>? AND EXISTS(SELECT 1 FROM users WHERE id=? AND password_hash=?)').bind(user.id,user.session_id,user.id,h.hash),env.DB.prepare('UPDATE hq_tokens SET used=? WHERE user_id=? AND used IS NULL AND EXISTS(SELECT 1 FROM users WHERE id=? AND password_hash=?)').bind('password-changed',user.id,user.id,h.hash)]);if(!out[0].meta.changes)fail(409,'Your account changed. Sign in again.');return json({ok:true,message:'Password changed. Other devices are signed out.'});}
export async function accountApi(request,env,user,url){const path=url.pathname,method=request.method;
 if(path==='/api/account/email'&&method==='POST')return saveEmail(request,env,user);
 if(path==='/api/account/password'&&method==='POST')return changePassword(request,env,user);
 if(path==='/api/auth/logout'&&method==='POST'){await env.DB.prepare('DELETE FROM sessions WHERE id=? AND user_id=?').bind(user.session_id,user.id).run();return json({ok:true},200,{'set-cookie':sessionCookie('',0)});}
 if(path==='/api/hq/sessions'&&method==='GET'){const rows=await queryAll(env.DB,'SELECT id,user_agent AS device,created_at AS createdAt,last_seen_at AS lastSeenAt,expires_at AS expiresAt FROM sessions WHERE user_id=? AND expires_at>? ORDER BY created_at DESC',user.id,now());return json({sessions:rows.map(x=>({...x,current:x.id===user.session_id}))});}
 let m=path.match(/^\/api\/hq\/sessions\/([\w-]+)$/);if(m&&method==='DELETE'){const out=await env.DB.prepare('DELETE FROM sessions WHERE id=? AND user_id=?').bind(m[1],user.id).run();if(!out.meta.changes)fail(404,'That session is not yours.');return json({ok:true},200,m[1]===user.session_id?{'set-cookie':sessionCookie('',0)}:{});}
 if(path==='/api/hq/profile'&&method==='PUT'){const b=await body(request),name=text(b.displayName,80,{required:true});await env.DB.prepare('UPDATE users SET display_name=?,updated_at=? WHERE id=?').bind(name,now(),user.id).run();return json({ok:true,user:{...safeUser(user),displayName:name}});}
 if(path==='/api/hq/preferences'&&method==='PUT'){const b=await body(request),revision=integer(b.revision,0,1e9,'Revision');const data=b.data||{};const clean={theme:choice(data.theme,['paper','night','system'],'paper'),reducedMotion:data.reducedMotion===true,language:choice(data.language,['en','zh'],'en'),notifications:data.notifications!==false,avatarId:text(data.avatarId||'',160)};if(clean.avatarId){const a=await env.DB.prepare('SELECT * FROM hq_assets WHERE id=? AND deleted_at IS NULL').bind(clean.avatarId).first();if(!a||(a.section!=='personal:'+user.id&&a.creator_id!==user.id))fail(400,'Choose one of your own profile photos.');}
 let out;if(!revision){try{out=await env.DB.prepare('INSERT INTO hq_prefs(user_id,revision,data) VALUES(?,1,?)').bind(user.id,JSON.stringify(clean)).run();}catch(e){if(/UNIQUE/.test(String(e)))fail(409,'Settings changed on another device. Reload them.');throw e;}}else out=await env.DB.prepare('UPDATE hq_prefs SET data=?,revision=revision+1 WHERE user_id=? AND revision=?').bind(JSON.stringify(clean),user.id,revision).run();if(!out.meta.changes)fail(409,'Settings changed on another device. Reload them.');return json({ok:true,preferences:clean,revision:revision+1});}
 if(path.startsWith('/api/hq/admin/'))return adminApi(request,env,user,url);
 return null;
}
async function adminApi(request,env,user,url){await requireOwner(env,user);const path=url.pathname,method=request.method;let m;
 if(path==='/api/hq/admin/users'&&method==='GET'){const rows=await queryAll(env.DB,"SELECT u.id,u.username,u.display_name,u.role,u.active,u.created_at,i.email,i.verified,p.role AS household_role FROM users u LEFT JOIN hq_identity i ON i.user_id=u.id LEFT JOIN hq_pair p ON p.user_id=u.id WHERE NOT EXISTS(SELECT 1 FROM hq_removed d WHERE d.user_id=u.id) ORDER BY u.created_at,u.id");return json({users:rows.map(u=>({...safeUser(u),createdAt:u.created_at,email:u.email||'',verified:Boolean(u.verified),householdRole:u.household_role||null}))});}
 if(path==='/api/hq/admin/users'&&method==='POST'){const b=await body(request),displayName=text(b.displayName,80,{required:true}),email=normalizeEmail(b.email),username=text(b.username,30,{required:true}).toLowerCase();if(!/^[a-z0-9_.-]{3,30}$/.test(username))fail(400,'Use 3–30 letters, numbers, dots, dashes or underscores for the username.');const uid=id('user'),stamp=now(),h=await passwordHash(token());try{await env.DB.batch([env.DB.prepare('INSERT INTO users(id,username,display_name,role,password_hash,password_salt,password_iterations,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,0,?,?)').bind(uid,username,displayName,'member',h.hash,h.salt,h.iterations,stamp,stamp),env.DB.prepare('INSERT INTO hq_identity(user_id,email,verified,updated_at) VALUES(?,?,0,?)').bind(uid,email,stamp)]);}catch(e){if(/UNIQUE/.test(String(e)))fail(409,'That username or email is already in use.');throw e;}const target=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(uid).first();const invitation=await invite(env,target,email);return json({user:safeUser(target),invitation},201);}
 m=path.match(/^\/api\/hq\/admin\/users\/([\w-]+)(?:\/(invite|reset-link))?$/);
 if(m){const target=await env.DB.prepare('SELECT * FROM users WHERE id=? AND NOT EXISTS(SELECT 1 FROM hq_removed d WHERE d.user_id=users.id)').bind(m[1]).first();if(!target)fail(404,'User not found.');const protectedOwner=(await permission(env,target,'intimate')).owner;
  if(m[2]==='invite'&&method==='POST'){if(target.active)fail(409,'This account is already active.');const identity=await env.DB.prepare('SELECT email FROM hq_identity WHERE user_id=?').bind(target.id).first();if(!identity?.email)fail(400,'The invitation needs an email address.');return json({invitation:await invite(env,target,identity.email)});}
  if(m[2]==='reset-link'&&method==='POST'){const b=await body(request);await reauthenticate(env,user,b.currentPassword);if(protectedOwner)fail(403,'Use verified email recovery for an owner account.');if(!target.active)fail(400,'Enable or invite this account first.');const t=await createToken(env,target,'reset');return json({url:origin(env)+'/reset-password/#token='+t.raw,expiresAt:new Date(t.expires).toISOString(),message:'Share this private link only after checking who is requesting it.'});}
  if(!m[2]&&method==='PUT'){const b=await body(request),name=text(b.displayName??target.display_name,80,{required:true});if(b.active===false){await reauthenticate(env,user,b.currentPassword);if(protectedOwner)fail(403,'The owner account cannot be disabled.');}
   const active=b.active===undefined?target.active:b.active?1:0;if(active===1&&target.active===0){const pending=await env.DB.prepare("SELECT 1 AS x FROM hq_tokens WHERE user_id=? AND kind='invite' AND used IS NULL").bind(target.id).first();if(pending)fail(400,'The invited person must first choose a password using their invitation.');}
   await env.DB.batch([env.DB.prepare('UPDATE users SET display_name=?,active=?,updated_at=? WHERE id=?').bind(name,active,now(),target.id),...(active===0?[env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(target.id),env.DB.prepare("UPDATE hq_tokens SET used='disabled' WHERE user_id=? AND used IS NULL").bind(target.id)]:[])]);return json({ok:true});}
  if(!m[2]&&method==='DELETE'){const b=await body(request);await reauthenticate(env,user,b.currentPassword);if(protectedOwner)fail(403,'The owner account cannot be deleted.');if(b.confirm!=='DELETE')fail(400,'Type DELETE to confirm. Shared contributions will remain.');const h=await passwordHash(token()),stamp=now();await env.DB.batch([env.DB.prepare("UPDATE users SET username=?,display_name='Former member',active=0,password_hash=?,password_salt=?,updated_at=? WHERE id=?").bind('deleted_'+id().slice(0,20),h.hash,h.salt,stamp,target.id),env.DB.prepare('INSERT OR IGNORE INTO hq_removed VALUES(?,?,?)').bind(target.id,user.id,stamp),...['sessions','hq_tokens','hq_identity','hq_grants','hq_prefs','hq_favourites','hq_recovery','hq_pair'].map(table=>env.DB.prepare(`DELETE FROM ${table} WHERE user_id=?`).bind(target.id))]);return json({ok:true,message:'Account access and personal details removed. Shared contributions remain.'});}
 }
 if(path==='/api/hq/admin/recovery'&&method==='GET'){const rows=await queryAll(env.DB,"SELECT r.id,r.user_id AS userId,r.created_at AS requestedAt,u.display_name AS displayName,i.email FROM hq_recovery r JOIN users u ON u.id=r.user_id LEFT JOIN hq_identity i ON i.user_id=u.id WHERE r.status='pending' AND u.active=1 ORDER BY r.created_at DESC");return json({requests:rows.map(r=>({...r,email:maskEmail(r.email)}))});}
 if(path==='/api/hq/admin/system'&&method==='GET')return json({emailConfigured:mailReady(env),emailSender:env.PASSWORD_RESET_FROM||'',database:'D1',media:'private R2',registration:'invite-only',automaticEmail:mailReady(env)?'Configured; delivery must be tested.':'Not configured. Recovery requests are visible to the owner.'});
 return null;
}
async function invite(env,target,email){await env.DB.prepare("UPDATE hq_tokens SET used='replaced' WHERE user_id=? AND kind='invite' AND used IS NULL").bind(target.id).run();const t=await createToken(env,target,'invite',{emailSent:false},7*86400);const link=origin(env)+'/accept-invitation/#token='+t.raw;const sent=await sendMail(env,email,'You are invited to Duck & Bear',`You have been invited to Duck & Bear. Choose your password using this private link:\n\n${link}\n\nThis invitation expires in seven days. Access to private sections is granted separately by the owner.`);if(sent)await env.DB.prepare('UPDATE hq_tokens SET payload=? WHERE token_hash=?').bind(JSON.stringify({emailSent:true}),t.hashed).run();return {url:link,expiresAt:new Date(t.expires).toISOString(),delivery:sent?'sent':'manual'};}
