import {fail,json,headers,body,bytes,text,ref,integer,now,id,sha,queryAll,parseData,deepAssetIds} from './core.mjs';
import {permission,requireOwner} from './schema.mjs';
import {KINDS} from './records.mjs';
import {inspectFile} from './media.mjs';
import {zipStream} from '../../public/hq/zip.mjs';
const te=new TextEncoder();
async function exportedSections(env,user,wanted=''){const out=[];for(const s of ['family','scrapbook','menus','plans','intimate']){const p=await permission(env,user,s);if(p.read&&p.export&&(!wanted||wanted===s))out.push(s);}if(!out.length)fail(403,'You do not have permission to export these records.');return out;}
async function exportBackup(env,user,wanted){const sections=await exportedSections(env,user,wanted),where=sections.map(()=>'?').join(',');
 const counts=await env.DB.prepare(`SELECT COUNT(*) AS n,COALESCE(SUM(length(data)),0) AS bytes FROM hq_records WHERE section IN (${where})`).bind(...sections).first();if(counts.n>10000||counts.bytes>8*1024*1024)fail(413,'Export one section at a time; this backup is too large for one file.');
 const rows=await queryAll(env.DB,`SELECT * FROM hq_records WHERE section IN (${where}) ORDER BY id`,...sections);
 const revisionSize=await env.DB.prepare(`SELECT COALESCE(SUM(length(h.data)),0) AS bytes FROM hq_revisions h JOIN hq_records r ON r.id=h.record_id WHERE r.section IN (${where})`).bind(...sections).first();if(revisionSize.bytes>16*1024*1024)fail(413,'Version history is too large for this single export. Export a section separately.');
 const revisions=await queryAll(env.DB,`SELECT h.* FROM hq_revisions h JOIN hq_records r ON r.id=h.record_id WHERE r.section IN (${where}) ORDER BY h.record_id,h.revision`,...sections);
 const assets=await queryAll(env.DB,`SELECT * FROM hq_assets WHERE section IN (${where}) ORDER BY id`,...sections);const entries=[],safeAssets=[];
 for(const a of assets){const original=await env.MEDIA.head(a.original_key),preview=await env.MEDIA.get(a.preview_key);if(!original||!preview)fail(409,'Backup stopped: an original or preview file is missing from storage.');const previewBytes=new Uint8Array(await preview.arrayBuffer());safeAssets.push({id:a.id,section:a.section,creatorId:a.creator_id,name:a.name,type:a.type,size:a.size,sha256:a.sha256,previewSha256:await sha(previewBytes),previewType:preview.httpMetadata?.contentType||a.type,width:a.width,height:a.height,createdAt:a.created_at,deletedAt:a.deleted_at||null});entries.push({name:'files/'+a.id+'/original',data:async()=>{const o=await env.MEDIA.get(a.original_key);if(!o)throw Error('Original file disappeared during export.');return new Uint8Array(await o.arrayBuffer());}},{name:'files/'+a.id+'/preview',data:async()=>{const p=await env.MEDIA.get(a.preview_key);if(!p)throw Error('Preview disappeared during export.');return new Uint8Array(await p.arrayBuffer());}});}
 const manifest={format:'duck-bear-hq',version:1,exportedAt:now(),records:rows.map(parseData),revisions,assets:safeAssets,permissions:'Access grants, passwords, reset tokens and public visibility are intentionally excluded.'};
 const content=te.encode(JSON.stringify(manifest));if(content.length>24*1024*1024)fail(413,'Export one section at a time.');entries.unshift({name:'manifest.json',data:content});return new Response(zipStream(entries),{headers:{...headers('application/zip'),'content-disposition':'attachment; filename="duck-bear-private-backup.zip"'}});
}
function iso(value){if(value===null||value===undefined)return null;const s=text(value,40);if(!Number.isFinite(Date.parse(s)))fail(400,'Backup has an invalid date.');return s;}
async function validateManifest(env,manifest){
 if(!manifest||manifest.format!=='duck-bear-hq'||manifest.version!==1||!Array.isArray(manifest.records)||!Array.isArray(manifest.assets)||!Array.isArray(manifest.revisions)||manifest.records.length>10000||manifest.assets.length>5000||manifest.revisions.length>50000)fail(400,'This is not a supported Duck & Bear backup.');
 const records=[],assets=[],ids=new Set(),assetIds=new Set();
 for(const r of manifest.records){const rid=ref(r.id,{required:true});if(ids.has(rid)||!(r.kind in KINDS))fail(400,'Backup has duplicate IDs or unknown record types.');ids.add(rid);if(!r.data||Array.isArray(r.data)||typeof r.data!=='object'||JSON.stringify(r.data).length>50000)fail(400,'Invalid backup content.');records.push({id:rid,kind:r.kind,section:KINDS[r.kind],parentId:r.parentId?ref(r.parentId):null,creatorId:ref(r.creatorId||'unknown'),revision:integer(r.revision||1,1,1e9),data:r.data,createdAt:iso(r.createdAt)||now(),updatedAt:iso(r.updatedAt)||now(),deletedAt:iso(r.deletedAt)});}
 const map=new Map(records.map(r=>[r.id,r]));
 const resolve=async rid=>map.get(rid)||parseData(await env.DB.prepare('SELECT * FROM hq_records WHERE id=?').bind(rid).first());
 for(const r of records){if(r.kind==='comment'){const p=await resolve(r.parentId);if(!p||!p.section||p.kind==='comment')fail(400,'Backup comment has no parent.');r.section=p.section;}if(!r.section)fail(400,'Invalid backup section.');if(r.parentId){const p=await resolve(r.parentId);if(!p)fail(400,'A linked backup record is missing.');if(p.section!==r.section&&!(r.kind==='review'&&p.kind==='serving'))fail(400,'Backup includes an invalid cross-section link.');}if(r.kind==='relationship'){for(const key of ['from','to']){const p=await resolve(ref(r.data[key],{required:true}));if(p?.kind!=='person')fail(400,'Backup relationship has no person.');}if(r.data.from===r.data.to)fail(400,'Backup has a self-relationship.');}if(r.kind==='week'&&!/^\d{4}-\d{2}-\d{2}$/.test(r.data.start))fail(400,'Backup has an invalid week.');}
 for(const a of manifest.assets){const aid=ref(a.id,{required:true});if(assetIds.has(aid)||!['family','scrapbook','menus','plans','intimate'].includes(a.section)||!['image/png','image/jpeg','image/webp','image/gif','application/pdf'].includes(a.type))fail(400,'Invalid backup asset.');assetIds.add(aid);if(!/^[A-Za-z0-9_-]{43}$/.test(a.sha256)||!/^[A-Za-z0-9_-]{43}$/.test(a.previewSha256))fail(400,'Backup files must have checksums.');assets.push({id:aid,section:a.section,creatorId:ref(a.creatorId||'unknown'),name:text(a.name,180,{required:true}),type:a.type,size:integer(a.size,1,8*1024*1024),sha256:a.sha256,previewSha256:a.previewSha256,previewType:a.previewType||a.type,width:a.width||null,height:a.height||null,createdAt:iso(a.createdAt)||now(),deletedAt:iso(a.deletedAt)});}
 for(const r of records)for(const aid of deepAssetIds(r.data)){const a=assets.find(x=>x.id===aid)||await env.DB.prepare('SELECT section FROM hq_assets WHERE id=?').bind(aid).first();if(!a||a.section!==r.section)fail(400,'A backup photo belongs to a different or missing section.');}
 const revisions=[];for(const h of manifest.revisions){if(!ids.has(h.record_id))fail(400,'Version history refers to an absent record.');const data=typeof h.data==='string'?h.data:JSON.stringify(h.data);try{JSON.parse(data);}catch{fail(400,'Invalid backup history.');}if(data.length>50000)fail(400,'Backup history is too large.');revisions.push({record_id:h.record_id,revision:integer(h.revision,1,1e9),data,actor_id:ref(h.actor_id||'unknown'),created_at:iso(h.created_at)||now(),deleted_at:iso(h.deleted_at)});}
 return {format:'duck-bear-hq',version:1,records,assets,revisions};
}
async function differences(env,manifest){const conflicts=[],newRecords=[],newAssets=[];for(const r of manifest.records){const old=await env.DB.prepare('SELECT kind,section,data,deleted_at FROM hq_records WHERE id=?').bind(r.id).first();if(!old)newRecords.push(r.id);else if(old.kind!==r.kind||old.section!==r.section||JSON.stringify(JSON.parse(old.data))!==JSON.stringify(r.data)||Boolean(old.deleted_at)!==Boolean(r.deletedAt))conflicts.push({id:r.id,title:r.data.title||r.data.name||r.kind,reason:'A different record already uses this ID.'});}for(const a of manifest.assets){const old=await env.DB.prepare('SELECT sha256,section FROM hq_assets WHERE id=?').bind(a.id).first();if(!old)newAssets.push(a.id);else if(old.sha256!==a.sha256||old.section!==a.section)conflicts.push({id:a.id,title:a.name,reason:'A different image already uses this ID.'});}return {conflicts,newRecords,newAssets};}
async function restoreJob(env,user,jid){await requireOwner(env,user);const job=await env.DB.prepare('SELECT * FROM hq_restore_jobs WHERE id=? AND user_id=? AND used IS NULL AND expires_at>?').bind(ref(jid,{required:true}),user.id,Date.now()).first();if(!job)fail(400,'This restore session expired or was already used.');return {...job,manifest:JSON.parse(job.manifest)};}
export async function backupApi(request,env,user,url){const path=url.pathname,method=request.method;let m;
 if(path==='/api/hq/backup'&&method==='GET')return exportBackup(env,user,url.searchParams.get('section')||'');
 if(path==='/api/hq/restore/preview'&&method==='POST'){await requireOwner(env,user);const b=await body(request,25*1024*1024);const manifest=await validateManifest(env,b.manifest);const diff=await differences(env,manifest),jid=id('restore');await env.DB.prepare('INSERT INTO hq_restore_jobs(id,user_id,manifest,expires_at,created_at) VALUES(?,?,?,?,?)').bind(jid,user.id,JSON.stringify(manifest),Date.now()+3600000,now()).run();return json({jobId:jid,...diff,createCount:diff.newRecords.length,keepCount:manifest.records.length-diff.newRecords.length,privateByDefault:true});}
 m=path.match(/^\/api\/hq\/restore\/([\w-]+)\/files\/([\w-]+)\/(original|preview)$/);if(m&&method==='POST'){const job=await restoreJob(env,user,m[1]);const a=job.manifest.assets.find(x=>x.id===m[2]);if(!a)fail(400,'This file is not part of the backup.');const binary=await bytes(request,8*1024*1024);const expected=m[3]==='original'?a.sha256:a.previewSha256;if(await sha(binary)!==expected)fail(400,'File checksum does not match the backup.');inspectFile(binary,m[3]==='original'?a.type:a.previewType);const key='hq-imports/'+job.id+'/'+a.id+'/'+m[3];await env.MEDIA.put(key,binary,{httpMetadata:{contentType:m[3]==='original'?a.type:a.previewType},customMetadata:{section:a.section,uploadedBy:user.id}});await env.DB.prepare('INSERT INTO hq_restore_files(job_id,asset_id,variant,r2_key) VALUES(?,?,?,?) ON CONFLICT(job_id,asset_id,variant) DO UPDATE SET r2_key=excluded.r2_key').bind(job.id,a.id,m[3],key).run();return json({ok:true});}
 m=path.match(/^\/api\/hq\/restore\/([\w-]+)\/apply$/);if(m&&method==='POST'){const job=await restoreJob(env,user,m[1]);const b=await body(request);if(b.confirm!=='RESTORE')fail(400,'Confirm this restore.');const diff=await differences(env,job.manifest);if(diff.conflicts.length)fail(409,'Restore stopped: existing records differ. Nothing has been overwritten.');const staging=await queryAll(env.DB,'SELECT * FROM hq_restore_files WHERE job_id=?',job.id);const allUsers=new Set((await queryAll(env.DB,'SELECT id FROM users')).map(x=>x.id));const author=x=>allUsers.has(x)?x:user.id;const nonce=id('applied');const guard='EXISTS(SELECT 1 FROM hq_restore_jobs WHERE id=? AND used=?)';const steps=[env.DB.prepare('UPDATE hq_restore_jobs SET used=? WHERE id=? AND used IS NULL AND expires_at>?').bind(nonce,job.id,Date.now())];
  for(const aid of diff.newAssets){const a=job.manifest.assets.find(x=>x.id===aid),original=staging.find(x=>x.asset_id===aid&&x.variant==='original'),preview=staging.find(x=>x.asset_id===aid&&x.variant==='preview');if(!original||!preview)fail(400,'Upload all original and preview files before restoring.');steps.push(env.DB.prepare(`INSERT INTO hq_assets(id,section,creator_id,name,type,size,original_key,preview_key,sha256,width,height,is_public,created_at,deleted_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,0,?,? WHERE ${guard}`).bind(a.id,a.section,author(a.creatorId),a.name,a.type,a.size,original.r2_key,preview.r2_key,a.sha256,a.width,a.height,a.createdAt,a.deletedAt,job.id,nonce));}
  // Servings go in before their archived week so the normal freeze trigger still protects future edits.
  const records=job.manifest.records.filter(r=>diff.newRecords.includes(r.id)).sort((a,b)=>(a.kind==='week'?1:0)-(b.kind==='week'?1:0));
  for(const r of records)steps.push(env.DB.prepare(`INSERT INTO hq_records(id,kind,section,parent_id,creator_id,updated_by,revision,data,created_at,updated_at,deleted_at) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE ${guard}`).bind(r.id,r.kind,r.section,r.parentId,author(r.creatorId),user.id,r.revision,JSON.stringify(r.data),r.createdAt,r.updatedAt,r.deletedAt,job.id,nonce));
  for(const r of job.manifest.revisions.filter(x=>diff.newRecords.includes(x.record_id)))steps.push(env.DB.prepare(`INSERT OR IGNORE INTO hq_revisions(record_id,revision,data,actor_id,created_at,deleted_at) SELECT ?,?,?,?,?,? WHERE ${guard}`).bind(r.record_id,r.revision,r.data,author(r.actor_id),r.created_at,r.deleted_at,job.id,nonce));
  let out;try{out=await env.DB.batch(steps);}catch(e){if(/UNIQUE|family_cycle|week_published/.test(String(e)))fail(409,'Restore stopped because a record conflicts. Nothing has been overwritten.');throw e;}if(!out[0].meta.changes)fail(409,'That restore session was already used.');return json({ok:true,created:diff.newRecords.length,assets:diff.newAssets.length,message:'Restored privately. Existing records and access permissions were not changed.'});
 }
 return null;
}
