import {fail,json,headers,bytes,body,text,ref,id,sha,now,queryAll,integer} from './core.mjs';
import {permission,requireAccess,requireOwner} from './schema.mjs';
const LIMIT=8*1024*1024,MAX_PIXELS=40000000;
const TYPES={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif','application/pdf':'pdf'};
const ascii=(a,start,end)=>String.fromCharCode(...a.slice(start,end));
export function inspectFile(a,type){
 if(!(a instanceof Uint8Array)||a.length<8||a.length>LIMIT||!TYPES[type])fail(400,'Use JPG, PNG, WebP, GIF or PDF, up to 8 MB.');
 const view=new DataView(a.buffer,a.byteOffset,a.byteLength);let w=0,h=0;
 if(type==='image/png'){if(ascii(a,1,4)!=='PNG'||a[0]!==137||ascii(a,12,16)!=='IHDR'||a.length<24)fail(400,'This is not a valid PNG image.');w=view.getUint32(16);h=view.getUint32(20);}
 else if(type==='image/gif'){if(!['GIF87a','GIF89a'].includes(ascii(a,0,6)))fail(400,'This is not a valid GIF.');w=view.getUint16(6,true);h=view.getUint16(8,true);}
 else if(type==='image/jpeg'){if(a[0]!==255||a[1]!==216||a[2]!==255)fail(400,'This is not a valid JPEG.');let i=2;while(i<a.length-8){if(a[i++]!==255)continue;while(a[i]===255)i++;const marker=a[i++];if(marker===217||marker===218)break;if(marker===1||marker>=208&&marker<=215)continue;const size=view.getUint16(i);if(size<2||i+size>a.length)break;if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(marker)){h=view.getUint16(i+3);w=view.getUint16(i+5);break;}i+=size;}if(!w||!h)fail(400,'The JPEG dimensions could not be read.');}
 else if(type==='image/webp'){if(ascii(a,0,4)!=='RIFF'||ascii(a,8,12)!=='WEBP')fail(400,'This is not a valid WebP image.');const chunk=ascii(a,12,16);if(chunk==='VP8X'&&a.length>=30){w=1+a[24]+(a[25]<<8)+(a[26]<<16);h=1+a[27]+(a[28]<<8)+(a[29]<<16);}else if(chunk==='VP8L'&&a.length>=25&&a[20]===47){const n=view.getUint32(21,true);w=(n&16383)+1;h=((n>>>14)&16383)+1;}else if(chunk==='VP8 '&&a.length>=30&&a[23]===157&&a[24]===1&&a[25]===42){w=view.getUint16(26,true)&16383;h=view.getUint16(28,true)&16383;}else fail(400,'The WebP dimensions could not be read.');}
 else if(type==='application/pdf'){if(ascii(a,0,5)!=='%PDF-')fail(400,'This is not a valid PDF.');return {width:null,height:null};}
 if(!w||!h||w>20000||h>20000||w*h>MAX_PIXELS)fail(400,'Choose an image smaller than 40 megapixels.');return {width:w,height:h};
}
export async function assetAccess(env,user,section,action='read'){if(section==='personal:'+user.id)return {read:true,contribute:true,edit:true,export:true,owner:false};return requireAccess(env,user,section,action);}
function safeAsset(a){return {id:a.id,section:a.section,name:a.name,type:a.type,size:a.size,width:a.width,height:a.height,isPublic:Boolean(a.is_public),creatorId:a.creator_id,createdAt:a.created_at,deletedAt:a.deleted_at,url:'/api/hq/assets/'+a.id+'/content'};}
async function load(env,rid){const a=await env.DB.prepare('SELECT * FROM hq_assets WHERE id=?').bind(ref(rid,{required:true})).first();if(!a)fail(404,'Photo not found.');return a;}
export async function upload(request,env,user){const raw=await bytes(request,12*1024*1024);let f;try{f=await new Request(request.url,{method:'POST',headers:{'content-type':request.headers.get('content-type')||''},body:raw}).formData();}catch{fail(400,'Choose a file to upload.');}const file=f.get('file'),section=text(f.get('section'),100,{required:true});await assetAccess(env,user,section,'contribute');if(!file||typeof file.arrayBuffer!=='function'||typeof file.type!=='string')fail(400,'Choose a file to upload.');const binary=new Uint8Array(await file.arrayBuffer());const dimensions=inspectFile(binary,file.type);
 const usage=await env.DB.prepare('SELECT COALESCE(SUM(size),0) AS total FROM hq_assets WHERE creator_id=?').bind(user.id).first();if(usage.total+file.size>1024*1024*1024)fail(413,'The personal upload limit has been reached. Ask the owner to review storage.');
 let preview=binary,previewType=file.type;const p=f.get('preview');if(p&&typeof p.arrayBuffer==='function'){preview=new Uint8Array(await p.arrayBuffer());if(preview.length>2*1024*1024||!p.type.startsWith('image/'))fail(400,'Preview must be an image under 2 MB.');inspectFile(preview,p.type);previewType=p.type;}
 if(file.type==='application/pdf')preview=binary;
 const rid=id('asset'),originalKey='hq-assets/'+rid+'/original.'+TYPES[file.type],previewKey=(p&&file.type!=='application/pdf')?'hq-assets/'+rid+'/preview.'+TYPES[previewType]:originalKey;
 await env.MEDIA.put(originalKey,binary,{httpMetadata:{contentType:file.type},customMetadata:{uploadedBy:user.id,section}});
 try{if(previewKey!==originalKey)await env.MEDIA.put(previewKey,preview,{httpMetadata:{contentType:previewType},customMetadata:{uploadedBy:user.id,section}});await env.DB.prepare('INSERT INTO hq_assets(id,section,creator_id,name,type,size,original_key,preview_key,sha256,width,height,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(rid,section,user.id,text(file.name||'Upload',180),file.type,binary.length,originalKey,previewKey,await sha(binary),dimensions.width,dimensions.height,now()).run();}catch(e){await env.MEDIA.delete([originalKey,...(previewKey!==originalKey?[previewKey]:[])]).catch(()=>{});throw e;}
 return safeAsset(await load(env,rid));
}
async function content(env,a,{original=false,publicRead=false}={}){if(a.deleted_at)fail(404,'Photo is in the recycle bin.');const object=await env.MEDIA.get(original?a.original_key:a.preview_key);if(!object)fail(404,'The file is missing from storage.');const h={...headers(object.httpMetadata?.contentType||a.type),'content-security-policy':"default-src 'none'; sandbox"};if(original||a.type==='application/pdf')h['content-disposition']="attachment; filename*=UTF-8''"+encodeURIComponent(a.name);else h['content-disposition']='inline';if(publicRead)h['cache-control']='public, max-age=60';return new Response(object.body,{headers:h});}
export async function publicMedia(request,env,url){const m=url.pathname.match(/^\/api\/public\/hq\/assets\/([\w-]+)$/);if(!m)return null;if(request.method!=='GET')fail(405,'Use GET.');if(url.searchParams.has('original'))fail(404,'Not found.');const a=await env.DB.prepare('SELECT * FROM hq_assets WHERE id=? AND is_public=1 AND deleted_at IS NULL').bind(m[1]).first();if(!a||!a.type.startsWith('image/'))fail(404,'Not found.');return content(env,a,{publicRead:true});}
export async function mediaApi(request,env,user,url){const path=url.pathname,method=request.method;
 if(path==='/api/hq/assets'&&method==='POST')return json({asset:await upload(request,env,user)},201);
 if(path==='/api/hq/assets'&&method==='GET'){const section=url.searchParams.get('section')||'scrapbook';await assetAccess(env,user,section);const cursor=integer(Number(url.searchParams.get('cursor')||0),0,10000000);const trash=url.searchParams.get('trash')==='1';const rows=await queryAll(env.DB,`SELECT * FROM hq_assets WHERE section=? AND deleted_at IS ${trash?'NOT ':''}NULL ORDER BY created_at DESC,id DESC LIMIT 61 OFFSET ?`,section,cursor);return json({assets:rows.slice(0,60).map(safeAsset),nextCursor:rows.length>60?String(cursor+60):null});}
 const m=path.match(/^\/api\/hq\/assets\/([\w-]+)(?:\/(content|restore))?$/);if(!m)return null;const a=await load(env,m[1]);const access=await assetAccess(env,user,a.section);const owner=(await permission(env,user,'intimate')).owner;
 if(m[2]==='content'&&method==='GET'){const original=url.searchParams.get('original')==='1';if(original&&!access.export&&a.creator_id!==user.id)fail(403,'Original-file downloads are not permitted.');return content(env,a,{original});}
 if(!m[2]&&method==='GET')return json({asset:safeAsset(a)});
 if(['PUT','DELETE','POST'].includes(method)){const b=await body(request);if(!access.edit&&!(access.contribute&&a.creator_id===user.id))fail(403,'You can only edit your own uploads.');
  if(method==='PUT'&&!m[2]){if(b.isPublic!==undefined){await requireOwner(env,user);if(b.isPublic&&b.confirm!=='PUBLISH')fail(400,'Confirm publication. This preview will be visible to anyone.');if(b.isPublic&&!a.type.startsWith('image/'))fail(400,'Only image previews can be published.');if(b.isPublic&&a.preview_key===a.original_key)fail(400,'Create a clean preview before publishing this original.');await env.DB.prepare('UPDATE hq_assets SET is_public=? WHERE id=?').bind(b.isPublic===true?1:0,a.id).run();}if(b.name!==undefined)await env.DB.prepare('UPDATE hq_assets SET name=? WHERE id=?').bind(text(b.name,180,{required:true}),a.id).run();return json({asset:safeAsset(await load(env,a.id))});}
  if(method==='DELETE'&&!m[2]){const uses=await env.DB.prepare("SELECT COUNT(*) AS n FROM hq_records r,json_tree(r.data) j WHERE r.deleted_at IS NULL AND j.type='text' AND j.value=?").bind(a.id).first();const prefs=await env.DB.prepare("SELECT COUNT(*) AS n FROM hq_site s,json_tree(s.data) j WHERE j.value=?").bind(a.id).first();const avatars=await env.DB.prepare("SELECT COUNT(*) AS n FROM hq_prefs p,json_tree(p.data) j WHERE j.value=?").bind(a.id).first();if(uses.n||prefs.n||avatars.n)fail(409,'This image is still used by a record or cover. Replace it there first.');await env.DB.prepare('UPDATE hq_assets SET deleted_at=?,is_public=0 WHERE id=?').bind(now(),a.id).run();return json({ok:true});}
  if(method==='POST'&&m[2]==='restore'){await env.DB.prepare('UPDATE hq_assets SET deleted_at=NULL WHERE id=?').bind(a.id).run();return json({asset:safeAsset(await load(env,a.id))});}
 }
 fail(405,'Unsupported file action.');
}
