import {fail,id,sha,now,queryAll} from './core.mjs';
import {LEGACY_MEALS} from './seed.mjs';
import {permission} from './schema.mjs';

async function oldJson(env,key){const object=await env.MEDIA.get(key);if(!object)return null;let data;try{data=JSON.parse(await object.text());}catch{fail(503,'Saved legacy data needs owner review. Nothing has been overwritten.','legacy_data');}if(!data||typeof data!=='object'||Array.isArray(data))fail(503,'Saved legacy data has an unexpected format. Nothing has been overwritten.','legacy_data');return data;}
export async function importLegacy(env,user){
 if(!(await permission(env,user,'intimate')).pair)return;
 if(await env.DB.prepare("SELECT 1 AS ok FROM hq_meta WHERE key='legacy-imported-v1'").first())return;
 const menus=await oldJson(env,'menu-room/private-data-v1.json'),security=await oldJson(env,'account-security/private-v1.json');
 if(menus&&(!Array.isArray(menus.suggestions)||!Array.isArray(menus.reviews)))fail(503,'Saved menu records need owner review. They have not been changed.');
 const users=await queryAll(env.DB,'SELECT id FROM users'),known=new Set(users.map(u=>u.id));
 const pair=await env.DB.prepare("SELECT user_id FROM hq_pair WHERE role='owner' ORDER BY user_id LIMIT 1").first();const owner=pair.user_id;
 const actor=uid=>known.has(uid)?uid:owner;const steps=[];
 function record(rid,kind,section,parent,creator,data,stamp='2026-09-28T00:00:00.000Z'){steps.push(env.DB.prepare('INSERT OR IGNORE INTO hq_records(id,kind,section,parent_id,creator_id,updated_by,revision,data,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?,?)').bind(rid,kind,section,parent,actor(creator),actor(creator),JSON.stringify(data),stamp,stamp));}
 const weekId='week-2026-09-28';const meals=[];
 for(const m of LEGACY_MEALS){const data={weekId,date:m.meal_date,course:m.meal_type,title:m.display_name,description:m.description,recipeId:'',ingredients:[],ingredientsConfirmed:false,served:Boolean(m.served),photos:[],order:0};meals.push({id:m.id,...data});record(m.id,'serving','menus',weekId,owner,data);}
 record(weekId,'week','menus',null,owner,{start:'2026-09-28',title:'The Dungeon Menu',status:'published',snapshot:{start:'2026-09-28',title:'The Dungeon Menu',publishedAt:'2026-09-28T00:00:00.000Z',meals}});
 async function oldAsset(key,name,type,size,creator,section){if(!key||!/^memories\/|^menu-reviews\//.test(key))return null;const obj=await env.MEDIA.get(key);if(!obj)return null;const binary=new Uint8Array(await obj.arrayBuffer()),aid='legacy-asset-'+(await sha(key)).slice(0,24);steps.push(env.DB.prepare('INSERT OR IGNORE INTO hq_assets(id,section,creator_id,name,type,size,original_key,preview_key,sha256,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(aid,section,actor(creator),String(name||'Saved attachment').slice(0,180),obj.httpMetadata?.contentType||type||'application/octet-stream',binary.length,key,key,await sha(binary),now()));return aid;}
 for(const s of menus?.suggestions||[]){const rid='legacy-'+String(s.id).replace(/[^\w-]/g,'').slice(0,100);record(rid,'idea','menus',null,s.user_id,{title:s.title||'Saved meal idea',description:[s.description,s.notes].filter(Boolean).join('\n\n'),course:s.meal_type||'dinner',cuisine:'',minutes:30,servings:2,ingredients:[],instructions:'',link:'',week:s.target_week_start||'',status:String(s.status||'suggested').toLowerCase(),photos:[],coverId:'',attachmentId:''},s.created_at||now());}
 for(const r of menus?.reviews||[]){let meal=meals.find(m=>m.id===r.meal_id);if(!meal&&r.meal_snapshot?.id){const s=r.meal_snapshot,wid='week-'+s.week_start;meal={id:s.id,weekId:wid,date:s.meal_date,course:s.meal_type,title:s.display_name,description:s.description||'',served:Boolean(s.served),ingredients:[],ingredientsConfirmed:false,photos:[],order:0};record(s.id,'serving','menus',wid,r.user_id,meal,r.created_at||now());record(wid,'week','menus',null,owner,{start:s.week_start,title:'Saved weekly menu',status:'published',snapshot:{start:s.week_start,title:'Saved weekly menu',publishedAt:r.created_at||now(),meals:[meal]}},r.created_at||now());}
  if(!meal)fail(503,'A saved review refers to a missing meal. Owner review is needed before migration.');const photos=[];for(const p of r.photos||[]){const aid=await oldAsset(p.r2_key,p.file_name,p.mime_type,p.file_size,r.user_id,'intimate');if(aid)photos.push({assetId:aid,caption:'',x:50,y:50,zoom:1});}
  record('legacy-'+String(r.id).replace(/[^\w-]/g,'').slice(0,100),'review','intimate',meal.id,r.user_id,{servingId:meal.id,mealSnapshot:meal,overall:r.overall_rating,taste:r.taste_rating,plating:r.plating_rating,comment:r.comment||'',makeAgain:false,photos},r.created_at||now());
 }
 const memories=await queryAll(env.DB,'SELECT * FROM memories ORDER BY created_at,id');
 if(memories.length){record('legacy-scrapbook','album','scrapbook',null,owner,{title:'Our earlier memories',description:'Preserved from the original Duck & Bear account.',date:'',coverId:'',layout:'notebook'});for(const m of memories){const aid=await oldAsset(m.attachment_key,m.attachment_name,m.attachment_type,m.attachment_size,m.user_id,'scrapbook');record('legacy-'+m.id,'memory','scrapbook','legacy-scrapbook',m.user_id,{title:m.title,text:m.body||'',date:m.happened_on||'',albumId:'legacy-scrapbook',planId:'',status:'saved',layout:'notebook',photos:aid&&String(m.attachment_type).startsWith('image/')?[{assetId:aid,caption:'',x:50,y:50,zoom:1}]:[],coverId:'',attachmentId:aid&&!String(m.attachment_type).startsWith('image/')?aid:'',stickers:[]},m.created_at);}}
 for(const p of security?.profiles||[]){if(!known.has(p.user_id)||!p.email)continue;const email=String(p.email_normalized||p.email).trim().toLowerCase();steps.push(env.DB.prepare('INSERT OR IGNORE INTO hq_identity(user_id,email,verified,pending_email,updated_at) VALUES(?,?,0,NULL,?)').bind(p.user_id,email,p.updated_at||now()));}
 steps.push(env.DB.prepare("INSERT OR IGNORE INTO hq_meta(key,value) VALUES('legacy-imported-v1',?)").bind(now()));await env.DB.batch(steps);
}
