import {fail,text,integer,choice,date,ref,url,id,now,parseData,queryAll,deepAssetIds} from './core.mjs';
import {permission,requireAccess} from './schema.mjs';
import {FAMILY_KINDS,RELATION_TYPES,personFields,familyData,provenance,period} from './family-fields.mjs';

export const KINDS={lifeEvent:'family',familyPlace:'family',familySource:'family',familyResearch:'family',familyPrivate:'intimate',person:'family',relationship:'family',story:'family',change:'family',album:'scrapbook',memory:'scrapbook',idea:'menus',recipe:'menus',week:'menus',serving:'menus',shopping:'menus',review:'intimate',plan:'plans',planIdea:'plans',poll:'plans',vote:'plans',bucket:'plans',note:'intimate',info:'library',comment:null};
const RELATIONS=RELATION_TYPES;
const PARENTS=['parent','adoptive-parent','step-parent'];
const course=v=>choice(v,['breakfast','lunch','dinner','other'],'dinner');
const bool=v=>v===true;
const str=(v,max=200,required=false)=>text(v,max,{required});
function lines(v,max=40){if(v===undefined)return [];if(typeof v==='string')v=v.split('\n');if(!Array.isArray(v)||v.length>max)fail(400,'Too many lines.');return v.map(x=>str(x,500)).filter(Boolean);}
function photos(v=[]){if(!Array.isArray(v)||v.length>12)fail(400,'Use no more than 12 photos.');return v.map(x=>{if(!x||typeof x!=='object')fail(400,'Invalid photo.');return {assetId:ref(x.assetId,{required:true}),caption:str(x.caption,500),x:integer(x.x??50,0,100,'Crop position'),y:integer(x.y??50,0,100,'Crop position'),zoom:Math.max(1,Math.min(3,Number(x.zoom)||1))};});}
export async function getRow(env,recordId,includeDeleted=false){return env.DB.prepare(`SELECT * FROM hq_records WHERE id=? ${includeDeleted?'':'AND deleted_at IS NULL'}`).bind(ref(recordId,{required:true})).first();}
export async function getRecord(env,user,recordId,{deleted=false}={}){const row=await getRow(env,recordId,deleted);if(!row)fail(404,'That record is not available.');await requireAccess(env,user,row.section);return parseData(row);}
async function linked(env,user,rid,kinds){const row=await getRow(env,ref(rid,{required:true}));if(!row||!kinds.includes(row.kind))fail(400,'A linked record is missing.');await requireAccess(env,user,row.section);return parseData(row);}
async function checkAssets(env,user,section,data){for(const assetId of deepAssetIds(data)){const a=await env.DB.prepare('SELECT section FROM hq_assets WHERE id=? AND deleted_at IS NULL').bind(assetId).first();if(!a||a.section!==section)fail(400,'Choose a photo belonging to this section.');await requireAccess(env,user,a.section);}}
async function mutableWeek(env,parentId){const w=await getRow(env,parentId);if(!w||w.kind!=='week')fail(400,'Choose a week.');if(JSON.parse(w.data).status==='published')fail(409,'This week is published. Copy it to a new draft; the archive stays unchanged.');return parseData(w);}
export async function validate(env,user,kind,input,existing=null){
 if(!(kind in KINDS)||!input||Array.isArray(input)||typeof input!=='object')fail(400,'Invalid record type or content.');
 let section=KINDS[kind],parentId=null,d={};
 switch(kind){
 case 'info':d={title:str(input.title,200,true),category:str(input.category,100),summary:str(input.summary,500),text:str(input.text,20000,true),tags:lines(input.tags,20),sourceUrl:url(input.sourceUrl)};break;
 case 'person':d={name:str(input.name,160,true),alternateName:str(input.alternateName,160),birth:str(input.birth,100),death:str(input.death,100),birthPlace:str(input.birthPlace,200),relationLabel:str(input.relationLabel,160),branch:str(input.branch,100),notes:str(input.notes,6000),confidence:choice(input.confidence,['confirmed','recollection','unknown'],'unknown'),photos:photos(input.photos),coverId:ref(input.coverId),...personFields(input)};break;
 case 'relationship':{
  const from=await linked(env,user,input.from,['person']),to=await linked(env,user,input.to,['person']);if(from.id===to.id)fail(400,'A person cannot be linked to themselves.');const type=choice(input.type,RELATIONS);
  const relations=await queryAll(env.DB,"SELECT id,data FROM hq_records WHERE kind='relationship' AND deleted_at IS NULL");
  const r=relations.filter(x=>x.id!==existing?.id).map(x=>JSON.parse(x.data));
  if(r.some(x=>x.type===type&&((x.from===from.id&&x.to===to.id)||(['partner','former-partner','sibling','half-sibling','adoptive-sibling','cousin'].includes(type)&&x.to===from.id&&x.from===to.id))))fail(409,'That relationship already exists.');
  if(PARENTS.includes(type)){const visited=new Set(),queue=[to.id];while(queue.length){const current=queue.shift();if(current===from.id)fail(400,'That parent relationship would create a loop.');if(visited.has(current))continue;visited.add(current);for(const edge of r)if(PARENTS.includes(edge.type)&&edge.from===current)queue.push(edge.to);}}
  d={from:from.id,to:to.id,type,note:str(input.note,3000),...period(input),endedBy:choice(input.endedBy,['','separation','divorce','death','unknown'],''),...provenance(input)};break;}
 case 'story':{const person=await linked(env,user,input.personId,['person']);parentId=person.id;d={personId:person.id,title:str(input.title,200,true),text:str(input.text,10000,true),date:date(input.date),photos:photos(input.photos),...provenance(input)};break;}
 case 'lifeEvent':case 'familyPlace':case 'familySource':case 'familyResearch':case 'familyPrivate':{d=familyData(kind,input);if(d.personId){const person=await linked(env,user,d.personId,['person']);parentId=person.id;}if(kind==='lifeEvent'){for(const rid of d.participants)await linked(env,user,rid,['person']);d.photos=photos(input.photos);}break;}
 case 'change':{const target=await linked(env,user,input.targetId,['person','relationship','story']);parentId=target.id;d={targetId:target.id,title:str(input.title,200,true),proposal:str(input.proposal,5000,true),status:existing?.data.status||'suggested'};break;}
 case 'album':d={title:str(input.title,200,true),description:str(input.description,3000),date:date(input.date),coverId:ref(input.coverId),layout:choice(input.layout,['notebook','postcard','gallery','story'],'notebook')};break;
 case 'memory':{if(input.albumId){const album=await linked(env,user,input.albumId,['album']);parentId=album.id;}let planId='';if(input.planId){await linked(env,user,input.planId,['plan','bucket']);planId=input.planId;}d={title:str(input.title,200,true),text:str(input.text,12000),date:date(input.date),albumId:parentId||'',planId,attachmentId:ref(input.attachmentId),status:choice(input.status,['draft','saved'],'saved'),layout:choice(input.layout,['notebook','postcard','gallery','story'],'notebook'),photos:photos(input.photos),coverId:ref(input.coverId),stickers:lines(input.stickers,8)};break;}
 case 'idea':case 'recipe':d={title:str(input.title,200,true),description:str(input.description,5000),course:course(input.course),cuisine:str(input.cuisine,100),tags:lines(input.tags,20),minutes:integer(input.minutes??30,1,1440,'Minutes'),servings:integer(input.servings??2,1,100,'Servings'),ingredients:lines(input.ingredients),instructions:str(input.instructions,12000),link:url(input.link),week:date(input.week,{monday:true}),status:choice(input.status,['suggested','shortlisted','planned','skipped'],'suggested'),photos:photos(input.photos),coverId:ref(input.coverId),attachmentId:ref(input.attachmentId)};break;
 case 'week':d={start:date(input.start,{required:true,monday:true}),title:str(input.title||'Our weekly menu',200),notes:str(input.notes,5000),status:existing?.data.status||'draft',snapshot:existing?.data.snapshot||null};if(existing?.data.status==='published')fail(409,'Archived menus cannot be overwritten.');break;
 case 'serving':{const w=await linked(env,user,input.weekId,['week']);await mutableWeek(env,w.id);parentId=w.id;const mealDate=date(input.date,{required:true});const gap=(Date.parse(mealDate)-Date.parse(w.data.start))/86400000;if(gap<0||gap>6)fail(400,'Choose a day within this week.');let recipeId='';if(input.recipeId){await linked(env,user,input.recipeId,['idea','recipe']);recipeId=input.recipeId;}d={weekId:w.id,date:mealDate,course:course(input.course),title:str(input.title,200,true),description:str(input.description,5000),recipeId,ingredients:lines(input.ingredients),ingredientsConfirmed:bool(input.ingredientsConfirmed),served:bool(input.served),photos:photos(input.photos),order:integer(input.order??0,0,100)};break;}
 case 'shopping':{const w=await linked(env,user,input.weekId,['week']);parentId=w.id;d={weekId:w.id,title:str(input.title,500,true),checked:bool(input.checked),note:str(input.note,500),sourceId:ref(input.sourceId)};break;}
 case 'review':{const meal=await linked(env,user,input.servingId,['serving']);parentId=meal.id;const ps=photos(input.photos);if(ps.length>4)fail(400,'Use no more than four review photos.');d={servingId:meal.id,mealSnapshot:existing?.data.mealSnapshot||Object.fromEntries(['weekId','date','course','title','description','recipeId','ingredients'].filter(k=>meal.data[k]!==undefined).map(k=>[k,meal.data[k]])),overall:integer(input.overall,1,6,'Overall rating'),taste:integer(input.taste,1,5,'Taste rating'),plating:integer(input.plating,1,5,'Plating rating'),comment:str(input.comment,5000),makeAgain:bool(input.makeAgain),photos:ps};break;}
 case 'plan':d={trip:bool(input.trip),title:str(input.title,200,true),description:str(input.description,6000),date:date(input.date),endDate:date(input.endDate),time:str(input.time,5),place:str(input.place,300),link:url(input.link),status:choice(input.status,['idea','planned','done'],'planned'),photos:photos(input.photos),sourceId:ref(input.sourceId)};if(d.time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(d.time))fail(400,'Enter a valid time.');if(d.date&&d.endDate&&d.endDate<d.date)fail(400,'End date cannot be before the start date.');break;
 case 'planIdea':case 'bucket':d={title:str(input.title,200,true),description:str(input.description,5000),category:choice(input.category,['food','outdoors','travel','home','other'],'other'),status:choice(input.status,['someday','planned','done'],'someday'),date:date(input.date),link:url(input.link),photos:photos(input.photos)};break;
 case 'poll':{const options=lines(input.options,12);if(options.length<2||new Set(options).size!==options.length)fail(400,'Add at least two different choices.');d={title:str(input.title,200,true),description:str(input.description,2000),options,closed:bool(input.closed)};if(existing){const votes=await env.DB.prepare("SELECT COUNT(*) AS n FROM hq_records WHERE kind='vote' AND parent_id=? AND deleted_at IS NULL").bind(existing.id).first();if(votes.n&&JSON.stringify(options)!==JSON.stringify(existing.data.options))fail(409,'Choices cannot change once voting starts. Create another poll.');}break;}
 case 'vote':fail(400,'Use the voting control.');break;
 case 'note':d={title:str(input.title||'A little note',200),text:str(input.text,6000,true),date:date(input.date),colour:choice(input.colour,['yellow','pink','blue','green'],'yellow')};break;
 case 'comment':{const parent=await getRecord(env,user,ref(input.recordId,{required:true}));if(parent.kind==='comment'||parent.kind==='vote')fail(400,'Choose a main record for this comment.');section=parent.section;parentId=parent.id;d={recordId:parent.id,text:str(input.text,3000,true)};break;}
 }
 if(FAMILY_KINDS.includes(kind)){for(const sourceId of d.sourceIds||[])await linked(env,user,sourceId,['familySource']);for(const key of ['placeId','birthPlaceId','currentPlaceId','deathPlaceId'])if(d[key])await linked(env,user,d[key],['familyPlace']);}
 if(existing&&parentId!==existing.parentId&&['review','story','change','comment','lifeEvent','familyPrivate'].includes(kind))fail(400,'The linked record cannot change.');
 await requireAccess(env,user,section,existing?'read':'contribute');await checkAssets(env,user,section,d);
 return {section,parentId,data:d};
}
export async function listRecords(env,user,{kind,section,parent,search='',cursor='0',limit=60,trash=false,favourites=false}={}){
 if(kind&&!(kind in KINDS))fail(404,'Unknown section.');const allowed=[];
 if(section){await requireAccess(env,user,section);allowed.push(section);}else if(kind&&KINDS[kind]){await requireAccess(env,user,KINDS[kind]);allowed.push(KINDS[kind]);}else{for(const s of ['family','scrapbook','menus','plans','intimate','library'])if((await permission(env,user,s)).read)allowed.push(s);}
 if(!allowed.length)return {records:[],nextCursor:null};
 const offset=Number(cursor);integer(offset,0,10000000,'Page');integer(Number(limit),1,100,'Page size');
 const bind=[...allowed];let where=`r.section IN (${allowed.map(()=>'?').join(',')}) AND r.deleted_at IS ${trash?'NOT ':''}NULL`;
 if(kind){where+=' AND r.kind=?';bind.push(kind);}if(parent){where+=' AND r.parent_id=?';bind.push(ref(parent));}
 if(search){where+=" AND (r.data LIKE ? ESCAPE '\\')";bind.push('%'+str(search,200).replace(/[\\%_]/g,'\\$&')+'%');}
 if(favourites){where+=' AND EXISTS(SELECT 1 FROM hq_favourites f WHERE f.record_id=r.id AND f.user_id=?)';bind.push(user.id);}
 const rows=await queryAll(env.DB,`SELECT r.*,u.display_name AS author FROM hq_records r LEFT JOIN users u ON u.id=r.creator_id WHERE ${where} ORDER BY r.updated_at DESC,r.id DESC LIMIT ? OFFSET ?`,...bind,Number(limit)+1,offset);
 const more=rows.length>limit;return {records:rows.slice(0,limit).map(r=>({...parseData(r),author:r.author||'Former member'})),nextCursor:more?String(offset+Number(limit)):null};
}
export function insertStatement(env,user,kind,v,recordId=id(kind),stamp=now()){return env.DB.prepare('INSERT INTO hq_records(id,kind,section,parent_id,creator_id,updated_by,revision,data,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?,?)').bind(recordId,kind,v.section,v.parentId,user.id,user.id,JSON.stringify(v.data),stamp,stamp);}
export async function createRecord(env,user,kind,input){const v=await validate(env,user,kind,input);const rid=id(kind);try{await env.DB.batch([insertStatement(env,user,kind,v,rid),env.DB.prepare('INSERT INTO hq_events(section,record_id,actor_id,action,created_at) VALUES(?,?,?,?,?)').bind(v.section,rid,user.id,'created',now())]);}catch(e){constraint(e);}return getRecord(env,user,rid);}
export async function editAccess(env,user,record){if(record.kind==='review'&&record.creatorId!==user.id)fail(403,'Only the reviewer can change their own verdict.');const p=await requireAccess(env,user,record.section);if(!p.edit&&!(p.contribute&&record.creatorId===user.id))fail(403,'You can only edit your own contributions.');return p;}
export async function updateRecord(env,user,recordId,revision,input){const r=await getRecord(env,user,recordId);await editAccess(env,user,r);integer(revision,1,1e9,'Revision');if(revision!==r.revision)fail(409,'Someone changed this record. Reload it before saving.','revision');const v=await validate(env,user,r.kind,input,r);const stamp=now();let result;try{result=await env.DB.batch([env.DB.prepare('UPDATE hq_records SET parent_id=?,data=?,revision=revision+1,updated_by=?,updated_at=? WHERE id=? AND revision=? AND deleted_at IS NULL').bind(v.parentId,JSON.stringify(v.data),user.id,stamp,r.id,revision),env.DB.prepare('INSERT INTO hq_events(section,record_id,actor_id,action,created_at) SELECT ?,?,?,?,? WHERE changes()>0').bind(r.section,r.id,user.id,'updated',stamp)]);}catch(e){constraint(e);}if(!result[0].meta.changes)fail(409,'Someone changed this record. Your text has not been discarded.','revision');return getRecord(env,user,r.id);}
function constraint(e){const msg=String(e);if(/poll_closed/.test(msg))fail(409,'Voting is closed.');if(/family_cycle/.test(msg))fail(400,'That relationship would create a family loop.');if(/week_published/.test(msg))fail(409,'Published weeks stay unchanged.');if(/UNIQUE constraint/i.test(msg))fail(409,'That entry already exists.');throw e;}
export async function deleteRecord(env,user,rid,revision){const r=await getRecord(env,user,rid);await editAccess(env,user,r);integer(revision,1,1e9,'Revision');if(r.kind==='week'&&r.data.status==='published')fail(409,'Published menu archives cannot be deleted.');if(r.kind==='serving')await mutableWeek(env,r.parentId);
 if(['person','album','familyPlace','familySource'].includes(r.kind)){const refs=await env.DB.prepare("SELECT COUNT(*) AS n FROM hq_records r,json_tree(r.data) j WHERE r.deleted_at IS NULL AND r.id<>? AND j.type='text' AND j.value=?").bind(r.id,r.id).first();if(refs.n)fail(409,'This entry is still linked to other records. Remove or move those links first.');}
 const stamp=now();let out;try{out=await env.DB.batch([env.DB.prepare('UPDATE hq_records SET deleted_at=?,revision=revision+1,updated_by=?,updated_at=? WHERE id=? AND revision=? AND deleted_at IS NULL').bind(stamp,user.id,stamp,r.id,revision),env.DB.prepare('INSERT INTO hq_events(section,record_id,actor_id,action,created_at) SELECT ?,?,?,?,? WHERE changes()>0').bind(r.section,r.id,user.id,'moved to recycle bin',stamp)]);}catch(e){constraint(e);}if(!out[0].meta.changes)fail(409,'This record changed. Reload it.');return {ok:true};}
export async function restoreRecord(env,user,rid,revision,sourceRevision=null){const r=await getRecord(env,user,rid,{deleted:true});await editAccess(env,user,r);integer(revision,1,1e9,'Revision');if(r.kind==='week'&&r.data.status==='published')fail(409,'Published archives cannot be overwritten.');let data=r.data;if(sourceRevision){integer(sourceRevision,1,r.revision,'Version');const old=await env.DB.prepare('SELECT data FROM hq_revisions WHERE record_id=? AND revision=?').bind(r.id,sourceRevision).first();if(!old)fail(404,'That version is missing.');data=JSON.parse(old.data);}const v=await validate(env,user,r.kind,data,r);const stamp=now();let out;try{out=await env.DB.batch([env.DB.prepare('UPDATE hq_records SET data=?,parent_id=?,deleted_at=NULL,revision=revision+1,updated_by=?,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify(v.data),v.parentId,user.id,stamp,r.id,revision),env.DB.prepare('INSERT INTO hq_events(section,record_id,actor_id,action,created_at) SELECT ?,?,?,?,? WHERE changes()>0').bind(r.section,r.id,user.id,'restored',stamp)]);}catch(e){constraint(e);}if(!out[0].meta.changes)fail(409,'This record changed. Reload it.');return getRecord(env,user,r.id);}
export async function history(env,user,rid){const r=await getRecord(env,user,rid,{deleted:true});const rows=await queryAll(env.DB,'SELECT revision,data,actor_id AS actorId,created_at AS createdAt,deleted_at AS deletedAt FROM hq_revisions WHERE record_id=? ORDER BY revision DESC',r.id);return {record:r,revisions:rows.map(x=>({...x,data:JSON.parse(x.data)}))};}
export async function publishWeek(env,user,rid,revision){const w=await getRecord(env,user,rid);if(w.kind!=='week')fail(400,'Choose a week.');await requireAccess(env,user,'menus','edit');if(w.data.status==='published')fail(409,'This menu is already archived.');integer(revision,1,1e9,'Revision');
 if(await env.DB.prepare("SELECT id FROM hq_records WHERE kind='week' AND deleted_at IS NULL AND json_extract(data,'$.start')=? AND json_extract(data,'$.status')='published'").bind(w.data.start).first())fail(409,'This date already has a published menu. Copy your draft to another week; the original archive stays unchanged.');
 const meals=(await queryAll(env.DB,"SELECT * FROM hq_records WHERE kind='serving' AND parent_id=? AND deleted_at IS NULL ORDER BY id",w.id)).map(parseData);if(!meals.length)fail(400,'Add meals before publishing.');
 const stamp=now(),snapshot={start:w.data.start,title:w.data.title,publishedAt:stamp,meals:meals.map(r=>({id:r.id,...r.data})).sort((a,b)=>a.date.localeCompare(b.date)||({breakfast:0,lunch:1,dinner:2,other:3}[a.course]-{breakfast:0,lunch:1,dinner:2,other:3}[b.course]))};
 const signature=meals.map(x=>x.id+':'+x.revision).join(',');const out=await env.DB.batch([env.DB.prepare("UPDATE hq_records SET data=?,revision=revision+1,updated_at=?,updated_by=? WHERE id=? AND revision=? AND deleted_at IS NULL AND ?=(SELECT COALESCE(group_concat(sig), '') FROM (SELECT id||':'||revision AS sig FROM hq_records WHERE kind='serving' AND parent_id=? AND deleted_at IS NULL ORDER BY id))").bind(JSON.stringify({...w.data,status:'published',snapshot}),stamp,user.id,w.id,revision,signature,w.id),env.DB.prepare('INSERT INTO hq_events(section,record_id,actor_id,action,created_at) SELECT ?,?,?,?,? WHERE changes()>0').bind('menus',w.id,user.id,'published week',stamp)]);if(!out[0].meta.changes)fail(409,'The planner changed while publishing. Review it again.');return getRecord(env,user,w.id);}
export async function copyWeek(env,user,rid,start){const w=await getRecord(env,user,rid);if(w.kind!=='week')fail(400,'Choose a week.');await requireAccess(env,user,'menus','contribute');const target=date(start,{required:true,monday:true}),wid=id('week');const draft={section:'menus',parentId:null,data:{start:target,title:w.data.title,status:'draft',snapshot:null}};const meals=w.data.snapshot?.meals||(await queryAll(env.DB,"SELECT * FROM hq_records WHERE kind='serving' AND parent_id=? AND deleted_at IS NULL ORDER BY id",w.id)).map(x=>parseData(x).data);const diff=Date.parse(target)-Date.parse(w.data.start);const steps=[insertStatement(env,user,'week',draft,wid)];for(const meal of meals){const data={...meal,weekId:wid,date:new Date(Date.parse(meal.date)+diff).toISOString().slice(0,10),served:false};delete data.id;steps.push(insertStatement(env,user,'serving',{section:'menus',parentId:wid,data}));}try{await env.DB.batch(steps);}catch(e){constraint(e);}return getRecord(env,user,wid);}
export async function vote(env,user,rid,v){const poll=await getRecord(env,user,rid);if(poll.kind!=='poll')fail(400,'Choose a poll.');await requireAccess(env,user,'plans','contribute');if(poll.data.closed)fail(409,'Voting is closed.');integer(v,0,poll.data.options.length-1,'Choice');const old=await env.DB.prepare("SELECT * FROM hq_records WHERE kind='vote' AND parent_id=? AND creator_id=?").bind(rid,user.id).first();const stamp=now();if(old){try{await env.DB.prepare('UPDATE hq_records SET data=?,deleted_at=NULL,revision=revision+1,updated_at=?,updated_by=? WHERE id=?').bind(JSON.stringify({pollId:rid,choice:v}),stamp,user.id,old.id).run();}catch(e){constraint(e);}}else{try{await insertStatement(env,user,'vote',{section:'plans',parentId:rid,data:{pollId:rid,choice:v}},'vote_'+rid+'_'+user.id).run();}catch(e){constraint(e);}}return pollResults(env,user,rid);}
export async function pollResults(env,user,rid){const poll=await getRecord(env,user,rid);if(poll.kind!=='poll')fail(400,'Choose a poll.');const rows=await queryAll(env.DB,"SELECT data,creator_id FROM hq_records WHERE kind='vote' AND parent_id=? AND deleted_at IS NULL",rid);const totals=poll.data.options.map(()=>0);for(const r of rows){const n=JSON.parse(r.data).choice;if(Number.isInteger(n)&&n>=0&&n<totals.length)totals[n]++;}const mine=rows.find(x=>x.creator_id===user.id);return {poll,totals,mine:mine?JSON.parse(mine.data).choice:null};}
