/** LOCAL TEST HARNESS ONLY. Binds loopback; never deploy this server. */
import http from 'node:http';import {readFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';
import {makeD1,makeR2} from './sqlite.mjs';import {createBooksHandler} from '../../src/books/handler.mjs';
const root=resolve('public'),port=Number(process.env.BOOKS_TEST_PORT||8788);
const USERS={zachary:{id:'test-zachary',display_name:'Zachary',session_id:'test-session-1'},guannan:{id:'test-guannan',display_name:'Guannan',session_id:'test-session-2'}};
const mime={'.html':'text/html','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.txt':'text/plain','.wasm':'application/wasm'};
const assets={async fetch(r){let name=decodeURIComponent(new URL(r.url).pathname);const path=resolve(root,'.'+name);if(!path.startsWith(root+'/'))return new Response('Not found',{status:404});try{const bytes=await readFile(path);return new Response(bytes,{headers:{'content-type':mime[extname(path)]||'application/octet-stream'}});}catch{return new Response('Not found',{status:404});}}};
const env={DB:makeD1(),MEDIA:makeR2(),ASSETS:assets,BOOKS_ENABLED:'true',SITE_ORIGIN:`http://127.0.0.1:${port}`};
const app=createBooksHandler({fetch:async r=>new URL(r.url).pathname==='/hq/zip.mjs'?assets.fetch(r):new Response('Existing website is untouched')},{authenticate:async r=>USERS[(r.headers.get('cookie')||'').match(/(?:^|;\s*)test_reader=(\w+)/)?.[1]]||null,requirePair:async()=>{},requireOwner:async(_e,u)=>{if(u.id!==USERS.zachary.id)throw Object.assign(new Error('Administrator only'),{status:403});},readerIds:async()=>Object.values(USERS).map(u=>u.id),isOwner:async(_e,u)=>u.id===USERS.zachary.id});
http.createServer(async(req,res)=>{try{const u=new URL(req.url,env.SITE_ORIGIN);const chunks=[];for await(const chunk of req)chunks.push(chunk);const request=new Request(u,{method:req.method,headers:req.headers,body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(chunks)});const response=await app.fetch(request,env,{});res.writeHead(response.status,Object.fromEntries(response.headers));if(response.body)for await(const chunk of response.body)res.write(chunk);res.end();}catch(e){console.error(e);res.writeHead(500);res.end('Local harness error');}}).listen(port,'127.0.0.1',()=>console.log('Books test server '+env.SITE_ORIGIN));
