import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {PortalStore} from '../../src/portal/store.mjs';
let createPortalHandler;try{({createPortalHandler}=await import('../../src/portal/server.mjs'));}catch{}
const origin='https://duck-bear.test';
function database(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT PRIMARY KEY,username TEXT UNIQUE,display_name TEXT,role TEXT,password_hash TEXT,password_salt TEXT,password_iterations INTEGER,active INTEGER DEFAULT 1,created_at TEXT,updated_at TEXT);CREATE TABLE sessions(id TEXT PRIMARY KEY,user_id TEXT,token_hash TEXT UNIQUE,expires_at TEXT,created_at TEXT,last_seen_at TEXT,user_agent TEXT,ip_hash TEXT);CREATE TABLE audit_log(id TEXT PRIMARY KEY,actor_user_id TEXT,action TEXT,entity_type TEXT,entity_id TEXT,detail_json TEXT,created_at TEXT);CREATE TABLE memories(id TEXT,user_id TEXT,title TEXT,body TEXT,happened_on TEXT,attachment_key TEXT,attachment_name TEXT,attachment_type TEXT,attachment_size INTEGER,created_at TEXT);`);const prepare=sql=>({values:[],bind(...v){this.values=v;return this;},async first(){return db.prepare(sql).get(...this.values)||null;},async all(){return {results:db.prepare(sql).all(...this.values)};},async run(){const x=db.prepare(sql).run(...this.values);return {meta:{changes:Number(x.changes)}};}});return {db,prepare,async batch(items){const out=[];for(const x of items)out.push(await x.run());return out;}};}
const base64=buf=>Buffer.from(buf).toString('base64url');const sha=async s=>base64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));
export async function fixture(){assert.equal(typeof createPortalHandler,'function','HTTP integration must exist');const DB=database(),sql=new DatabaseSync(':memory:');const store=new PortalStore({storage:{sql:{exec(q,...v){const rows=sql.prepare(q).all(...v);return {toArray:()=>rows};}},transactionSync(fn){sql.exec('BEGIN');try{const r=fn();sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}}},{});const files=new Map();const env={DB,SITE_ORIGIN:origin,PORTAL:{idFromName:()=>1,get:()=>store},MEDIA:{async get(k){return files.get(k)||null;},async put(k,bytes,opts){const buf=typeof bytes==='string'?new TextEncoder().encode(bytes):bytes;files.set(k,{body:buf,httpMetadata:opts?.httpMetadata,size:buf.byteLength,async text(){return new TextDecoder().decode(buf);},async arrayBuffer(){return buf;}});},async delete(k){files.delete(k);}},ASSETS:{async fetch(){return new Response('<!doctype html><title>Portal</title>',{headers:{'Content-Type':'text/html'}});}}};
for(const [id,role] of [['owner','admin'],['duck','member'],['guest','member'],['disabled','member']]){DB.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,id,id,role,'hash','salt',100000,id==='disabled'?0:1,'2026-09-28','2026-09-28');DB.db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?,?,?,?)').run(id+'session',id,await sha(id),new Date(Date.now()+86400000).toISOString(),'2026-09-28','2026-09-28','','');}
DB.db.prepare('INSERT INTO audit_log VALUES(?,?,?,?,?,?,?)').run('setup','owner','setup.complete','system',null,JSON.stringify({memberUserId:'duck'}),'2026-09-28');const handler=createPortalHandler({async fetch(){return new Response('LEGACY PRIVATE',{status:209});}});
const call=async(path,{user='owner',method='GET',body,headers={}}={})=>{const h=new Headers({Origin:origin,...headers});if(user)h.set('Cookie','db_session='+user);let payload;if(body instanceof FormData)payload=body;else if(body!==undefined){h.set('Content-Type','application/json');payload=JSON.stringify(body);}const r=await handler.fetch(new Request(origin+path,{method,headers:h,body:payload}),env,{});return {res:r,status:r.status,data:(r.headers.get('Content-Type')||'').includes('json')?await r.json():await r.text()};};await call('/api/portal/session');return {env,handler,call,store,files};}
